### ISSUE TITLE
Elaboração do TAP

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#10]
Elaborar documento de termo de abertura de projeto - TAP

**Tarefas**

- [x] Criar estrutura de documento no drive
- [x] Levantar dados do documento com o grupo de EPS
- [x] Revisar documento 
- [x] Passar documento para Github Pages

**Critérios de aceitação**

- [x] O documento deve estar devidamente revisado e adicionado ao Github pages do grupo
- [x] Documentar na issue o  link do arquivo onde se pode encontrar o documento.

**Comment by KahCosta** [comment]
Documento do drive [Aqui](https://docs.google.com/document/d/1A-4ckUxAkToLK2cqKu1TDajcQghxOK9Ygd7CvGgaQcs/edit#heading=h.4xmdgdv0eglk)

**Comment by Lucas362** [comment]
Adicionado estrutura inicial do documento na pasta doc na branch issue_10_tap

**Comment by Lucas362** [comment]
Falta definir o preço médio de um freelancer na região de Brasília, para a definição de custo de pessoal

**Comment by KahCosta** [comment]
Vamos seguir esse modelo disponível [Aqui](https://materiais.resultadosdigitais.com.br/planejamento-orcamento-ti) que a @RochaCarla sugeriu!
