### ISSUE TITLE
Elaboração do EAP

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#11]
Elaborar documento de Estrutura Analítica do Projeto

**Tarefas**

- [x] Criar estrutura de documento no drive
- [x] Levantar dados do documento com o grupo de EPS
- [x] Revisar documento 
- [x] Passar documento para Github Pages

**Critérios de aceitação**

- [x] O documento deve estar devidamente revisado e adicionado ao Github pages do grupo
- [x] Documentar na issue o  link do arquivo onde se pode encontrar o documento.

**Comment by Lucas362** [comment]
Versão inicial já criada pela @KahCosta
