### ISSUE TITLE
Definir tecnologias a serem utilizadas

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#12]
Definir as tecnologias que serão utilizadas no desenvolvimento do projeto.

**Tarefas**

- [x] Definir com o arquiteto quais as tecnologias que serão utilizadas.
- [x] Documentar as tecnologias que foram selecionadas
- [x] Adicionar as tecnologias ao quadro de conhecimento do grupo

**Critérios de aceitação**

- [x] As decisões tomadas devem estar devidamente documentadas no Github Pages do grupo
- [x] Documentar na issue o link de onde o arquivo pode ser encontrado.

**Comment by GuiMarques98** [comment]
As tecnologias que estão em pauta são Flask e Django.

**Comment by GuiMarques98** [comment]
Foi decidido a utilização da tecnologia [Flask](http://flask.pocoo.org/) para se fazer a API, [Rasa](https://rasa.com/) para o bot.

**Comment by Yoshida-Eduardo** [comment]
Galera quais vão ser os serviços da API e como eles vão conversar entre si? Tá muito superficial essa definição das tecnologias, só pra lembrar que é uma arquitetura de microserviços, é muito importante dar uma descrição mais precisa, principalmente pois as issues #19 e #17 são dependentes dessas informações.
Andei dando uma lida na documentação do Rasa, eles possuem um NLU(interpretador de linguagem natural) e um Core(define as ações tomadas pelo bot), com a opção por utilizar o Flask e Rasa ficaria algo dessa forma então?(só pra lembrar meu conhecimento de chatbot é superficial)
![imagem](https://user-images.githubusercontent.com/37124267/54945319-4c53a080-4f14-11e9-84cb-ec4eadf6b551.png)

**Comment by GuiMarques98** [comment]
A @KahCosta explicou como funciona o Rasa CORE e NLU então serão mais ou menos essas APIs que existirão. O _Message Handler_ lida com comunicação entre os serviços internos, interpretar linguagem natural e escolher a melhor maneira de responder o usuário, e os serviços externos, mostrar o chat do bot para o _Jupyter Notebook_. 


![Modelo dos Microsserviços](https://user-images.githubusercontent.com/23389315/55021863-3e675380-4fd8-11e9-9f7c-d89b840b845e.png)

**Comment by GuiMarques98** [comment]
O time foi conversar com a Carla e estamos decidindo se usaremos um Broker ([RabbitMQ](https://www.rabbitmq.com/)) para controle do fluxo de envio e recebimento de mensagens substituindo o _Flask Message Handler_.

**Comment by GuiMarques98** [comment]
Para definir as técnologias utilizadas iremos utilizar o Plano de Gerenciamento de Configuração de Software.

**Comment by Lucas362** [comment]
No documento Plano de Gerenciamento de Configuração de Software, ficarei responsável pelas políticas

**Comment by Lucas362** [comment]
As tecnologias foram adicionadas ao quadro de conhecimento :+1:
