### ISSUE TITLE
Definir testes de acordo com a arquitetura

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#127]
Definir testes de acordo com a arquitetura que serem utilizados no pipeline de homologação e produção.

**Tarefas**

- [x] Definir testes
- [x] Documentar Testes

**Critérios de aceitação**

- [x] Documento criado no Github Pages
- [x] Docuemntar link do documento na issue

**Comment by Lucas362** [comment]
@GuiMarques98 Quais os testes necessário para definirmos a integração contínua e deploy? (teste unitário, ...)

**Comment by KahCosta** [comment]
Vamos documentar as escolhas feitas no documento de GCS

**Comment by KahCosta** [comment]
@GuiMarques98 e @Yoshida-Eduardo precisamos que vocês definam os testes de integração e adicionem no documento de GCS
