### ISSUE TITLE
Adicionar tópico com exemplos de utilização de estruturas de repetição

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#129]
Adicionar conteúdo referente ao tópico com exemplos de utilização de estruturas de repetição

**Tarefas**

- [x] Criar conteúdo referente a ação de apresentar exemplos de utilização de Estruturas de repetição na linguagem python.
- [x] Inserir conteúdo referente a ação de apresentar exemplos de Estruturas de repetição. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by heylisten64** [comment]
Acho que na issue primária de laços eu poderia refatorá-la pois na definição eu acabei colocando um exemplo que pode ser encaixado aqui, segue o trecho:

    Laços são funções capazes de reproduzir determinada ação.
    Béem, vou explicar de outra forma. Imagine que eu, Aix,
    estou no celeiro e meu feno do lado de fora, no campado.
    Para chegar lá, precisarei de alguns passos. Cada passo 
    será uma ação minha. No caso, eu terei que executar uma
    quantia de passos finitos até chegar ao meu objetivo.
    Repetirei então a minha ação "dar um passo" até chegar
    ao meu feno de cada dia. Funciona mais ou menos assim!


acabaria que reduziria um pouco o conteúdo da outra issue, o que estávamos preocupados... o que acha? @gustable42 @KahCosta

**Comment by heylisten64** [comment]
Ah! E a minha ideia era adicionar nessa issue também o conteudo visual exemplificando o caso!

**Comment by gustable42** [comment]
Achei legal, só não sei se tá mt grande. A Kamilla tem q passar o feedback pra gnt saber se tá indo bem ou não

**Comment by heylisten64** [comment]
qualquer ideia que tiver, joga aqui, que a gente tenta elaborar ela! e eu tento bolar um recurso visual...

**Comment by heylisten64** [comment]
# Exemplo de laços

## Intent:

```
 exemplo_laços


```

## utter

```
 utter_exemplo_laços


```

## template:

    Imagine que eu, Aix, estou no celeiro e meu feno do lado
    de fora, no campado. Para chegar lá, precisarei de alguns
    passos. Cada passo será uma ação minha. No caso, eu terei
    que executar uma quantia de passos finitos até chegar ao
    meu objetivo. Repetirei então a minha ação "dar um passo"
    até chegar ao meu feno. Funciona mais ou menos assim!

**Comment by heylisten64** [comment]
foi o conteúdo que adicionei até então, mas lembrando que podemos adicionar vários exemplos, para que o bot escolha randomicamente... Acho que é o ideal, então vamos trabalhar nisso! **E lembrando tentar deixar o mais compacto possível.** Ainda estou vendo a ideia da arte (que adicionaria a parte da sintaxe), tô com uns gargalos em design pra fazer o que planejo...

e caso esse modelo persista: lembrar de refatorar a issue #87 

coisas p/ não esquecer:
* sintaxe
* exemplos compactos
* arte
* refatoração

**Comment by gustable42** [comment]
Gabi, essa parte de escolher a resposta randomicamente, já tem uma solução para fazer isso? Vou dar uma pesquisada sobre isso

**Comment by heylisten64** [comment]
> Gabi, essa parte de escolher a resposta randomicamente, já tem uma solução para fazer isso? Vou dar uma pesquisada sobre isso

tem sim! o rasa disponibiliza essa função! https://www.youtube.com/watch?v=tW4x-R82hNc&list=PLo2mbJ5niURawJ9wJ_FX62N0VzneV3nyV&index=2 nesse webinar do lappis nos minutos 29:00 é abordado isso =)

**Comment by heylisten64** [comment]
https://www.youtube.com/watch?v=tW4x-R82hNc&list=PLo2mbJ5niURawJ9wJ_FX62N0VzneV3nyV&index=2 nesse webinar do lappis nos minutos 29:00 é abordado isso =)

**Comment by KahCosta** [comment]
Gabi acho que essa explicação está legal sim! para deixar o conteúdo mais completo seria legal se vcs conseguirem adicionar uma imagem explicativa

**Comment by heylisten64** [comment]
sim sim! só tava esperando o @gustable42 bolar alguns templates mais pra poder finalizar nas artes!

**Comment by heylisten64** [comment]
![laços_pronto](https://user-images.githubusercontent.com/43069991/56447441-c3dfda00-62de-11e9-8cea-9ad7a6d95fb4.png)

a arte elaborada pro tópico

**Comment by heylisten64** [comment]
segue a arte para o tópico:
![laços_pronto](https://user-images.githubusercontent.com/43069991/56447542-48caf380-62df-11e9-9c16-97937894e921.png)

**Comment by heylisten64** [comment]
* Segue a arte para o tópico:

![laços_pronta](https://user-images.githubusercontent.com/43069991/56447561-626c3b00-62df-11e9-81f3-77963cf19bd5.png)

@KahCosta 
@gustable42 adiciona pra mim a imagem junto ao template q a gente tem? pq to tendo problemas quanto ao docker, tentando arrumar isso... e pode abrir o pr
