### ISSUE TITLE
Adicionar tópico com linkagem estática para conteúdo extra sobre estruturas de repetição

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#130]
Adicionar conteúdo referente ao tópico linkagem estática para conteúdo extra sobre estruturas de repetição

**Tarefas**

- [x] Pesquisar link referente a utilização de Estruturas de repetição na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre a utilização de Estruturas de repetição. 

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by Andreabenf** [comment]
Achei esse link aqui bem bom
https://curso-intro-python.readthedocs.io/repeticao.html
o que acha?
