### ISSUE TITLE
Adicionar tópico com linkagem estática para sugestão de exercício sobre uso de estruturas de repetição

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#131]
Adicionar conteúdo referente ao tópico linkagem estática para sugestão de exercício sobre uso de estruturas de repetição

**Tarefas**

- [x] Pesquisar link referente a sugestão de exercícios referentes ao uso de Estruturas de repetição na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre sugestão de exercício sobre utilização de Estruturas de repetição. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by pedroeagle** [comment]
vou adicionar 3 exercícios. um fácil, um médio e um difícil. segue os link que serão utilizados em ordem de dificuldade crescente:
Números Pares - https://www.urionlinejudge.com.br/judge/pt/problems/view/
Maior e Posição - https://www.urionlinejudge.com.br/judge/pt/problems/view/
Sequência IJ 4 - https://www.urionlinejudge.com.br/judge/pt/problems/view/1098

**Comment by pedroeagle** [comment]
### Linkagem estática para sugestão de exercício sobre uso de estruturas de repetição
## intent
     links_exercicios_repeticao

## utter
     utter_links_exercicios_repeticao

## template
     Ahh, então você quer praticar estruturas de repetição? Fico tãããoo feliz em saber disso
        A única forma dééé aprender uma linguagem de forma eficaz é treinando!
        Veja esses 3 exercícios:
          Números Pares - https://www.urionlinejudge.com.br/judge/pt/problems/view/1059
          Maior e Posição - https://www.urionlinejudge.com.br/judge/pt/problems/view/1080
          Sequência IJ 4 - https://www.urionlinejudge.com.br/judge/pt/problems/view/1098
