### ISSUE TITLE
Integrar a Aix ao Telegram

### ISSUE THREAD

**Issue by GuiMarques98** [fga-eps-mds/2019.1-Grupo-1#136]
O usuário deve chamar o bot no aplicativo do Telegram.

**Tarefas**
- [x] Criar Docker para a API.
- [x] Criar um API Gateway em Flask para comunicar com o Telegram.

**Critérios de aceitação**
- [x] O usário deve conseguir se comunicar com a Aix pelo Telegram.
- [x] A chave secreta não deve aparecer no código do GitHub
- [x] Deve mostrar a imagem da Aix.
- [x] O código deve estar testado.

**Comment by GuiMarques98** [comment]
Um bom matérial pra começarem a ler seria esse site:
https://www.xfgeek.com/view-xfgeek-blog?title=Building-AI-chatbot-using-Rasa-NLU%2C-Flask-and-Telegram

**Comment by Yoshida-Eduardo** [comment]
Adicionei o container com flask conforme definido pelo Guilherme na issue e no grupo do telegram. Também atualizei o script do travis para checar esse novo container. Podem começar a codar galera de mds.

**Comment by Andreabenf** [comment]
Belezinha. Iremos começar hoje

**Comment by Andreabenf** [comment]
Tem que criar o bot no BotFather.
Ai precisa de nome e username.
Pretendo colocar Aix como nome e Aix_chatbot como username.
Pode ser?

**Comment by GuiMarques98** [comment]
Não tem problema nenhum colocar Aix_chatbot como username!

**Comment by Andreabenf** [comment]
Criei nosso bot no BotFather.
o nome é Aix
e o username é Aix_chatbodebot

**Comment by Andreabenf** [comment]
Enquanto não upamos o bot pra um servidor, eu to usando o ngrok como webhook, ok?
Ta dando tudo certo até agora

**Comment by KahCosta** [comment]
@Andreabenf e @gustable42 podem abrir o PR? 
documentem aqui na issue o que ficou de pendência desta issue pfv

**Comment by KahCosta** [comment]
as dependências serão mapeadas para a próxima sprint

**Comment by Andreabenf** [comment]
Abri o PR!
Faltou a parte de Testes, pois decidimos não utilizar mais o Flask.
Também faltou a parte de esconder a key.
