### ISSUE TITLE
Comunicação da Aix com a API do StackOverflow

### ISSUE THREAD

**Issue by GuiMarques98** [fga-eps-mds/2019.1-Grupo-1#137]
A Aix deve conseguir se comunicar com a API do StackOverflow para conseguir para pesquisar duvidas parecidas.
**Tarefas**

- [x] Criar end-points no Rasa Actions Server para o StackOverflow.
- [x] Criar queries para buscar perguntas respondidas no StackOverflow.

**Critérios de aceitação**

- [x] O end-point do StackOverflow deve estar funcionando.
- [x] A Aix deve ser capaz de buscar e responder perguntas gerais do usuário.

**Comment by GuiMarques98** [comment]
Documentação da API do StackOverflow?
https://api.stackexchange.com/docs

**Comment by iurisevero** [comment]
Estava estudando um pouco da API do StackOverflow, olhando os métodos disponíveis... Acredito que o método [Search](https://api.stackexchange.com/docs/search) seja exatamente o que precisamos para o bot. Em resumo, ele pega um texto e compara com os títulos das perguntas que tem no site, todas instâncias dele, e retorna uma lista com elas. Na lista você tem informado se a questão foi respondida e o link para ela, então daria para verificá-las e passar para usuário o link das respondidas.

**Comment by heylisten64** [comment]
De acordo!

**Comment by heylisten64** [comment]
Só evidenciando na issue os termos de uso, info de copyright:
```
API Attribution
All Applications must ensure they visually indicate 
that the Stack Exchange Network is the source of the
content provided through the API Services. Applications
which may in any way be indexed by search engines must
adhere to all Attribution rules defined in the Stack Exchange 
Terms of Service. For applications that lack access to
web browsing services, simple text versions of URLs
(instead of hyperlinks) will be sufficient. Exceptions
to these attribution rules must be requested in advance
of deploying any Applications.
```

**Comment by iurisevero** [comment]
Falei com a Kamilla e consegui o link do slide usado no webnar da Lappis sobre Slots. Podemos usar de base para tirar dúvidas.
[Slide Slots e Entidades](https://docs.google.com/presentation/d/1aONU1R_0mgxnya-1U4-Fd0rqfAfAsM6Rz7fe3aIs6P0/edit)

Tem o documento oficial do Rasa também, em casos de desespero.
[Rasa Slots](https://rasa.com/docs/core/slots/)

**Comment by heylisten64** [comment]
Tô tentando resolver o problema dos slots, estudando aqui!

**Comment by KahCosta** [comment]
@heylisten64 @iurisevero @pedroeagle estou fechando a issue! iremos criar uma nova issue para terminar a dependência dos slots na sprint 5. Documentem aqui pfv até onde prosseguiram no desenvolvimento da issue

**Comment by KahCosta** [comment]
Não esqueçam de abrir o PR desta!

**Comment by KahCosta** [comment]
Galera! a issue de vcs vai ficar como pendência!
Então documentem aqui o que ficou faltando para fechar e podem continuar trabalhando na mesma issue que criaram na sprint 4 na sprint 5

**Comment by heylisten64** [comment]
o problema em questão é que as entidades não aceitam trechos randômicos em texto
deve ser igual a que está nas intents...
bolamos um plano b, de utilizar uma utter intermediária perguntando novamente o tópico da pesquisa, e assim pegariamos todo o trecho digitado pelo usuário pra implementar na parte já feita
porém não consegui implementar devido ao problema no docker :(

**Comment by Yoshida-Eduardo** [comment]
Como algumas pessoas estavam com problema com o docker de actions fiz algumas alterações nele na branch dessa issue, creio que esteja tudo certo agora. Passamos a utilizar uma imagem oficial do rasa.

**Comment by iurisevero** [comment]
> Galera! a issue de vcs vai ficar como pendência!
> Então documentem aqui o que ficou faltando para fechar e podem continuar trabalhando na mesma issue que criaram na sprint 4 na sprint 5

Tivemos diversos problemas na issue durante essa sprint. 
* CustomActions: 
    * Problema: Ao começar a trabalhar com custom actions reparamos que estávamos com problema para conectar o bot com a server de actions ao rodar o docker.
    * Solução: Depois de diversos teste, descobrimos que seria possível acessar as actions rodando o comando `$sudo docker-compose up --build actions` e deixando o terminal executando o servidor em paralelo.

* Slots:
    * Problema: Durante o uso de Slots e Entities percebemos que a captação de strings não era muito boa. O processador não conseguia identificar para o slot strings que fossem diferentes das do exemplo. Após diversas pesquisas e consultas com outros estudantes da área descobrimos que esse problema já havia acontecido no [Lappisudo](https://github.com/lappis-unb/lappisudo), bot do Lappis-UnB, onde o slot não era preenchido se a string fugisse o padrão dos exemplos da intent.
    * Possível solução: Uma possível solução debatida pela equipe foi a de retirar todo o texto da intent, não apenas o slot, e criar uma intent intermediário para isso, porém não conseguimos implementar essa ideia.

* Docker:
    * Problema: Diversos membros da equipe tiveram problemas ao tentar executar o docker, o que os impediu de fazerem testes e rodar códigos, atrapalhando o progresso da issue.
    * Solução: O @Yoshida-Eduardo fez alguma alterações no docker da branch para solucionar esse problema.

Apesar de todos os problemas, conseguimos implementar parte do que foi pedido pela issue. Criamos um custon action que se conecta com a API do StackOverflow na função search, pesquisa pelo o que o slot passou para action e retorna para o usuário o link para as cinco primeiras perguntas respondidas no site.

* Pendências: Apesar da conexão com a API estar funcionando, não foi possível estabelecer um meio de comunicação entre o usuário e a action de pesquisa. A resolução desse problema ficará para a próxima sprint.

**Comment by iurisevero** [comment]
Após a daily de hoje ficou decidido que a pesquisa seria feita a partir da indução do usuário, levando-o a escrever a frase de forma que conseguíssemos alterá-la e aplicá-la na busca.
Ficou definido que teríamos uma utter explicando ao usuário como deveria ser feito a pesquisa e outra que, a partir da sentença _"pesquise sobre "_, faria a busca por meio de uma **Custon Action**.

A ideia final foi dada pela @KahCosta  a partir do que já havia sido discutido e testado na issue.

**Comment by iurisevero** [comment]
Resolvido o problema de identificar o que o usuário queria pesquisar a partir da indicação de como a frase deveria ser apresentada para o bot.
Corrigido um pequeno bug no request.
