### ISSUE TITLE
Documentar Sprint 0

### ISSUE THREAD

**Issue by Yoshida-Eduardo** [fga-eps-mds/2019.1-Grupo-1#14]
Escrever documentação da issue 0

**Tarefas**
- [x] Escrever a documentação relativa a revisão da sprint 0
- [x] Escrever a retrospectiva da sprint 0
- [x] Adicionar o burndown da sprint a documentação
- [x] Adicionar o velocity da sprint a documentação
- [x] Adicionar o planejamento de riscos e o burndown de riscos
- [x] Adicionar o quadro de conhecimentos
- [x] Disponibilizar a documentação no github pages

**Critérios de aceitação**

- [x] Todas os pontos elencados nas tarefas devem estar concluídos
- [x] A documentação deve estar disponível no github pages

**Comment by Lucas362** [comment]
Adicionada a estrutura básica do documento, na branch issue_14_sprint_report

**Comment by Lucas362** [comment]
Documentação criada e aguardando revisão de PR

**Comment by Lucas362** [comment]
Links para acesso dos documentos de [abertura](https://fga-eps-mds.github.io/2019.1-Aix/sprint/2019/03/27/abertura-sprint-0/) e [fechamento](https://fga-eps-mds.github.io/2019.1-Aix/sprint/2019/03/27/fechamento-sprint-0/) da sprint

**Comment by Lucas362** [comment]
Links para acesso dos documentos de [abertura](https://fga-eps-mds.github.io/2019.1-Aix/sprint/2019/03/27/fechamento-sprint-0/) e [fechamento](https://fga-eps-mds.github.io/2019.1-Aix/sprint/2019/03/27/abertura-sprint-0/) da sprint
