### ISSUE TITLE
Formatar padrões em intents, utters e stories

### ISSUE THREAD

**Issue by pedroeagle** [fga-eps-mds/2019.1-Grupo-1#148]
**Tarefas**

- [x] Estabelecer uma padrão entre todas as utters, stories e intents.

**Critérios de aceitação**

- [x] A definição do padrão não deve afetar no funcionamento do bot.
- [x] Todas as utters, intents e stories devem seguir o padrão definido.

**Comment by pedroeagle** [comment]
# Formatação
## Intents de conteúdo:
     sobre_x
## Intents de conteúdo extra:
     conteudo_extra_x
## Intents de exercícios:
     exercicios_x
## Utters:
     utter_nome_da_intent
## Stories:
     nome_da_intent

**Comment by KahCosta** [comment]
Certinho! essa issue entrará para nossa sprint 5!

**Comment by heylisten64** [comment]
- Acredito que na parte de intents esteja ok, só adicionar um novo padrão para ser seguido, quantos aos exemplos.
- Tomei a liberdade de reorganizar os tópicos de forma que a gente possa acompanhar melhor os conteúdos já inseridos. Separei eles por blocos nas intents e ordenei os templates e etc (domain.yml).
- Alterei também a utter/intent de links extras do conteúdo de repetição para utter_conteudo_extra_repeticao (domain.yml).

## Intents de exemplos:

    exemplo_x

**Comment by heylisten64** [comment]
Quanto a organização dos tópicos, montei um bloco para conteúdos de:
* diálogo do chatbot
* conteúdos aleatórios, curiosidades e menu ajuda
* sobre determinado conteúdo
* exemplo de determinado conteúdo
* exercicios de determinado conteúdo
* conteúdo extra de determinado conteúdo
* outros

**Comment by iurisevero** [comment]
> Quanto a organização dos tópicos, montei um bloco para conteúdos de:
> 
> * diálogo do chatbot
> * conteúdos aleatórios, curiosidades e menu ajuda
> * sobre determinado conteúdo
> * exemplo de determinado conteúdo
> * exercicios de determinado conteúdo
> * conteúdo extra de determinado conteúdo
> * outros

Tu é incrível vei \o/
Dps q essas issues forem fechadas, a gente abre uma para separar os arquivos de utter, intents e stories e aproveita essa divisão q vc fez \o

**Comment by heylisten64** [comment]
askksaksa <3 então nessa nova issue seria para organizar os conteúdos de intents e stories seguindo o mesmo fluxo da domain, para ficar de fácil leitura se algum conteúdo faltar em algum dos arquivos...
assim, acredito não ter mais alterações para fazer nessa issue. Apenas seguir o padrão que aqui se encontra. Revisem para ver se está tudo certinho, se não passei batido por nada, por favor... o último a revisar dá o PR ahahah ;*

**Comment by iurisevero** [comment]
> askksaksa <3 então nessa nova issue seria para organizar os conteúdos de intents e stories seguindo o mesmo fluxo da domain, para ficar de fácil leitura se algum conteúdo faltar em algum dos arquivos...
> assim, acredito não ter mais alterações para fazer nessa issue. Apenas seguir o padrão que aqui se encontra. Revisem para ver se está tudo certinho, se não passei batido por nada, por favor... o último a revisar dá o PR ahahah ;*

Acho q já dá pra separar os arquivos nessa Issue então. A gente vê com a @KahCosta e se ela aprovar, a gente já separa

**Comment by heylisten64** [comment]
Certo, então o que falta aqui é:
* seguir o fluxo da domain no arquivo de intents
* seguir o fluxo da domain no arquivo de stories
* revisar e na carência de algum conteúdo, até essa sprint, elaborar o conteúdo que esteja faltando.

aguardamos sua revisão @KahCosta ! :+1:

**Comment by Andreabenf** [comment]
Boua Gabi!

**Comment by Andreabenf** [comment]
Só passando aqui pra lembrar que essa issue ta sendo feita na branch #issue_162_refatorar_conteudos_inseridos
Logo, quando fecharmos a  #162 , fechamos essa também
