### ISSUE TITLE
Definição da arquitetura inicial

### ISSUE THREAD

**Issue by Yoshida-Eduardo** [fga-eps-mds/2019.1-Grupo-1#15]
Definir e documentar o fluxo eas tecnologias que serão utilizadas na arquitetura do projeto

**Tarefas**

- [x] Fazer diagrama de fluxo
- [x] Definir as tecnologias
- [x] Definição inicial dos endpoints das apis

**Critérios de aceitação**
- [x] A definição das tecnologias devem estar documentadas e disponíveis no github pages

**Comment by GuiMarques98** [comment]
A conclusão dessa _issue_ depende diretamente da _issue_ #12.

**Comment by GuiMarques98** [comment]
Documentar os endpoints foi decidido em não se entregar essa sprint.
