### ISSUE TITLE
Refatoração geral da Pages

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#154]
Refatoração geral do github Pages afim de refinar visualmente a página de documentação

**Tarefas**

- [x] Alterar cores da parte de documentação
- [x] Adicionar tags nos documentos afim de organizar sidebar
- [x] Alterar página inicial de documentação 
- [x] Adicionar histórico de versionamento 
- [x] Arrumar imagens que estão quebrando no doc de plano do comunicação
- [x] Alterar título da sprint 1 para abertura e fechamento
- [x] Alterar distância de um fluxograma para o outro no doc de fluxograma

**Critérios de aceitação**

- [x] Documentos listados na sidebar
- [x] github Pages atualizado e refatorado

**Comment by Lucas362** [comment]
Para as cores do título será escolhido a cor #936f92, caso alguém tenha algo contra, é só falar
![Captura de tela de 2019-04-22 15-27-12](https://user-images.githubusercontent.com/27078392/56517381-320ce280-6513-11e9-8778-2c3b67dcf644.png)

**Comment by Lucas362** [comment]
O link para a documentação fica assim, todo mundo de acordo?
![Captura de tela de 2019-04-22 16-44-38](https://user-images.githubusercontent.com/27078392/56523635-2377f880-651e-11e9-8774-fff5b29b35b9.png)
