### ISSUE TITLE
Refatorar documento de arquitetura

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#155]
Refatorar documento de arquitetura de acordo com novo escopo vigente.

**Tarefas**

- [x] Alterar documento de arquitetura segundo a nova arquitetura e escopo do projeto

**Critérios de aceitação**

- [x] Documento revisado pela equipe de EPS
- [x] Documento atualizado no githubPages

**Comment by heylisten64** [comment]
Irei revisar os tópicos 1 e 2 do nosso documento de arquitetura!
Além de, claro, dar uma olhada no restante, e caso seja preciso, dar algumas sugestões.
E se alguém se disponibilizar para me ajudar quanto ao tópico 2, aceito ajuda ^~

**Comment by iurisevero** [comment]
> Irei revisar os tópicos 1 e 2 do nosso documento de arquitetura!
> Além de, claro, dar uma olhada no restante, e caso seja preciso, dar algumas sugestões.
> E se alguém se disponibilizar para me ajudar quanto ao tópico 2, aceito ajuda ^~

Te ajudo no tópico 2 e posso revisar os tópicos 3 e 4.

**Comment by pedroeagle** [comment]
digramas de pacotes já deveriam estar na r1?

**Comment by pedroeagle** [comment]
@iurisevero e @heylisten64 , li o documento de arquitetura e vi que tem uns errinhos de português. tentem encontrar e corrigir, se precisar posso ajudar

**Comment by heylisten64** [comment]
Dei uma olhada e repassei alguns erros mínimos para arrumar. Como eram coisas pequenas, a alteração coube na mudança do Iuri no tópico 2.
