### ISSUE TITLE
Refatorar documento de visão

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#156]
Refatorar documento de visão de acordo com novo escopo vigente.

**Tarefas**

- [x] Alterar documento de visão segundo novo escopo do projeto

**Critérios de aceitação**

- [x] Docuemnto revisado pela equipe de EPS
- [x] Documento atualizado no githubPages

**Comment by heylisten64** [comment]
Irei revisar os tópicos 1 e 2 do nosso documento de visão!
Além de, claro, dar uma olhada no restante, e caso seja preciso, dar algumas sugestões.

**Comment by pedroeagle** [comment]
estava relendo o documento de visão aqui e no tópico 4 diz que o nosso bot sugeriria bibliotecas úteis
posso remover essa parte, certo? até o momento não inserimos isso, caso seja inserido readicionamos

**Comment by pedroeagle** [comment]
outra coisa, não foi mencionado entre os custos que todos já tinham notebook e que um dos integrantes precisou comprar outro para poder rodar as paradas lá. seria bom adicionar?

**Comment by heylisten64** [comment]
Da minha parte levantada, acho que está tudo ok. Só ficou faltando refatorar o tópico de definições, acrônimos e abreviações que levantarei hoje mesmo. E tenho algumas sugestões quanto ao resto do documento, que também levantarei hoje.

**Comment by heylisten64** [comment]
Estou olhando aqui o tópico 3 e tenho algumas sugestões:
* colocar em texto o que está em tópico e pegar esses tópicos e organizar em tabela na parte de resumo (pt. 3)
* arrumar repetição de expressões como "Nos últimos anos" (pt. 3.1)
* formatação, por ex, negritar "tabela 1" etc
* adição de mais exemplos (pt. 3.5)
* verificar se há mais tópicos relevantes que constam na documentação da [IBM](https://www.ibm.com/support/knowledgecenter/pt-br/SSYMRC_6.0.5/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html)

**Comment by heylisten64** [comment]
Observando o tópico 4, minhas sugestões são:
* colocar como inovação no projeto a parte de aprendizado de forma dinâmica, com o uso de ilustrações, etc e etc (pt 4.1)
* arrumar "o Aix bot" (pt. 4.2)

**Comment by heylisten64** [comment]
Tô refatorando, mas vi que foram criadas duas branches pra essa issue... não sei qual utilizar, mas se eu estiver na errada é só jogar as mudanças lá depois dos tópicos 1,2,4,5. E daqui a pouco, as mudanças que farei também no tópico 3.

**Comment by heylisten64** [comment]
No tema 3, os tópicos seguintes não foram abordados na documentação, mas seria bom adicionar mais pra frente... Não adicionei pois esperarei pelo feedback de vocês!
### 3.4 Ambiente do Usuário
### 3.5 Perfis das Partes Interessadas
### 3.6 Perfis do Usuário

**Comment by heylisten64** [comment]
## 3. Descrições da Parte Interessada e do Usuário
<p align="justify"> &emsp;&emsp;Neste tópico serão descritos os perfis da parte interessada e do usuário. Ademais, serão abordados também serviços que apresentam-se como concorrência para o nosso produto. </p>

### 3.1 Demográficos de Mercado

<p align="justify"> &emsp;&emsp;Nos últimos anos, a quantidade de programadores cresceu substancialmente, principalmente devido ao grande sucesso da área no mercado de trabalho. Além disso, diversas disciplinas necessitam da interação de noções básicas do
setor de software, de linguagens de programação, em especial. </p>

<p align="justify"> &emsp;&emsp;Uma das linguagens mais utilizadas atualmente é o Python. Desde a sua concepção, houve um grande crescimento em seu uso devido a variedade de aplicações da linguagem. Porém, aprender a programar para muitos discentes aparenta ser um imenso empecilho. Na Universidade de Brasília vários alunos se sentem desmotivados a programar e em diversos casos isso pode ser intensificado por dificuldades em aprender a linguagem em si.</p>

<p align="justify"> &emsp;&emsp;Desse modo, a Aix surge como uma ferramenta não só de aprendizado, mas também de motivação para os iniciantes em software. Assim, esperamos conseguir um êxito na formação de excelentes profissionais sem que seja necessário custos absurdos para que o serviço seja oferecido.</p>

### 3.2 Resumo da parte interessada

<p align="justify"> &emsp;&emsp;Instituições de ensino, assim como empresas comerciais, se adaptam aos avanços tecnológicos existentes de modo a tornar seus dependentes mais aptos as necessidades cotidianas. Umas das possíveis adaptações atuais é o ensino dinâmico de uma linguagem de programação, como o Python, aos seus funcionários e estudantes. </p>

### 3.3 Resumo do usuário
<p align="justify"> &emsp;&emsp;
O alvo beneficiário principal do nosso projeto são pessoas iniciantes no aprendizado da linguagem de programação Python, funcionários de empresas e estudantes que estão entrando na área de tecnologia, professores interessados em alternativas para o processo de ensino da matéria em questão, usuários da plataforma Jupyter que focam no desenvolvimento em Python e profissionais autônomos que desejam aumentar seus conhecimentos.</p>

**Comment by heylisten64** [comment]
###  3.4 Ambiente do Usuário
<p align="justify"> &emsp;&emsp;
A esfera de ação do projeto se encontra atualmente no aplicativo social denominado Telegram. O objetivo da equipe é deixar o programa disponível tanto na rede supracitada, quanto no ambiente Jupyter, visando uma maior acessibilidade do usuário. Este, por sua vez, será capaz de acessar os serviços da Aix enquanto estuda na sua mesa de trabalho ou em qualquer lugar que estiver pelo seu celular. Tal característica garante o maior alcance da ferramenta e consequentemente um maior sucesso desta.</p>
<p align="justify"> &emsp;&emsp;
Dessa forma, no momento atual, é necessário para o usuário apenas um dispositivo eletrônico apropriado para acessar o aplicativo Telegram.</p>

**Comment by heylisten64** [comment]
### 3.5 Perfis das Partes Interessadas: 

|Representante|Descrição|Tipo|Responsabilidades|Critérios de Sucesso|Envolvimento|Entregas|Comentários ou Problemas|
|--|--|--|--|--|--|--|--|--|--|
|Entidades de ensino.|Instituições físicas, empresas privadas, professores, plataformas digitais.|Guias intelectuais para aprendizes da linguagem de programação Python. |Garantir a conquista da formação de seus pupilos no conteúdo em questão e buscar alternativas que fogem ao estilo engessado de transmitir conhecimento. Inovar ao ensinar para alcançar o objetivo final. |Maior adesão ao serviço da parte interessada, graças aos bons resultados alcançados através de programas inovadores de ensino. Grandes profissionais que podem ser formados por estas entidades que darão nome a essas instituições.|Revisor de requisitos. Confere se é abordado no projeto todos os temas que a entidade busca propagar aos usuários, todo o conteúdo necessário para o pupilo em determinado período. Em caso de ausência de algum tema, contacta a equipe para que o tópico seja implementado.|Entregas adicionais que podem ser requeridas pela parte interessada serão os temas não abordados pela equipe mas que carecem na hora da revisão da parte interessada. Conteúdos relacionados ao estudo da linguagem Python|

-   Comentários ou Problemas: Determina os problemas que interferem com o sucesso e quaisquer outras informações relevantes.

Tentando bolar algo para esse último tópico!

**Comment by heylisten64** [comment]
### 3.5 Perfis das Partes Interessadas: 

|Representante|Descrição|Tipo|Responsabilidades|
|--|--|--|--|--|--|--|--|--|--|
|Entidades de ensino.|Instituições físicas, empresas privadas, professores, plataformas digitais.|Guias intelectuais para aprendizes da linguagem de programação Python. |Garantir a conquista da formação de seus pupilos no conteúdo em questão e buscar alternativas que fogem ao estilo engessado de transmitir conhecimento. Inovar ao ensinar para alcançar o objetivo final. 


Critérios de Sucesso|Envolvimento|Entregas|
|--|--|--|--|--|--|--|--|--|--|
|Maior adesão ao serviço da parte interessada, graças aos bons resultados alcançados através de programas inovadores de ensino. Grandes profissionais que podem ser formados por estas entidades que darão nome a essas instituições.|Revisor de requisitos. Confere se é abordado no projeto todos os temas que a entidade busca propagar aos usuários, todo o conteúdo necessário para o pupilo em determinado período. Em caso de ausência de algum tema, contacta a equipe para que o tópico seja implementado.|Entregas adicionais que podem ser requeridas pela parte interessada serão os temas não abordados pela equipe mas que carecem na hora da revisão da parte interessada. Conteúdos relacionados ao estudo da linguagem Python|

-   Comentários ou Problemas: Determina os problemas que interferem com o sucesso e quaisquer outras informações relevantes.

**Comment by heylisten64** [comment]
### 3.5 Perfis das Partes Interessadas

|Representante|Descrição|Tipo|Responsabilidades|
|--|--|--|--|
|Entidades de ensino.|Instituições físicas, empresas privadas, professores, plataformas digitais.|Guias intelectuais para aprendizes da linguagem de programação Python. |Garantir a conquista da formação de seus pupilos no conteúdo em questão e buscar alternativas que fogem ao estilo engessado de transmitir conhecimento. Inovar ao ensinar para alcançar o objetivo final.

**Comment by heylisten64** [comment]
Critérios de Sucesso|Envolvimento|Entregas|
|--|--|--|
|Maior adesão ao serviço da parte interessada, graças aos bons resultados alcançados através de programas inovadores de ensino e grandes profissionais que podem ser formados por estas entidades que darão nome a essas instituições.|Revisor de requisitos. Confere se é abordado no projeto todos os temas que a entidade busca propagar aos usuários, todo o conteúdo necessário para o pupilo em determinado período. Em caso de ausência de algum tema, contacta a equipe para que o tópico seja implementado.|Entregas adicionais que podem ser requeridas pela parte interessada serão os temas não abordados pela equipe mas que carecem na hora da revisão da parte interessada. Conteúdos relacionados ao estudo da linguagem Python.|

**Comment by heylisten64** [comment]
-   Comentários ou Problemas: Determina os problemas que interferem com o sucesso e quaisquer outras informações relevantes.

**Comment by heylisten64** [comment]
Caso necessário adicionar o tópico, se encontrar algum problema ou tiver algum comentário:
 -   Comentários ou Problemas: Determina os problemas que interferem com o sucesso e quaisquer outras informações relevantes.

Não encontrei então desconsiderei até essa parte do projeto.

**Comment by heylisten64** [comment]
### 3.6 Perfis das Partes Interessadas

|Representante|Descrição|Tipo|Responsabilidades|
|--|--|--|--|
|Indivíduos interessados em linguagem de programação Python.|Estudantes de cursos da computação, alunos de outras áreas interessados na interdisciplinariedade, profissionais autônomos. | Usuários informais que apresentam um nível baixo ou intermediário de conhecimento sobre Python. | Além de usar com responsabilidade o programa, tentando respeitar ao máximo a língua portuguesa mesmo que de forma coloquial, o usuário deve relatar qualquer problema técnico encontrado à parte interessada, para que esta alerte a equipe de desenvolvimento, que resolverá o problema.

**Comment by heylisten64** [comment]
Critérios de Sucesso|Envolvimento|Entregas|
|--|--|--|
|Reconhecimento pelo usuário de noções básicas da linguagem, identificação pelo beneficente de capítulos recorrentes de conteúdos bibliográficos, capacidade de solucionar problemas propostos pela Aix e outros demais empecilhos. | Construtor das dúvidas e receptor de conhecimento. Dialoga com o simulador de maneira informal e envia interrogações para que assim o chatbot retorne uma explicação correspondente.|As entregas do usuário são as dúvidas enviadas que deverão ser elaboradas por ele durante o processo de aprendizagem.|

**Comment by heylisten64** [comment]
Acredito que esteja ok para o PR. :100: 

Caso seja levantada novamente essa issue, seria legal **porém não essencial** preencher os tópicos 2, 4, 5, 7 com uma breve explicação dos tópicos. E também mais exemplos no tópico 4. Além disso, acrescentar os tópicos que não conseguimos preencher, que consta na documentação da IBM.

Porém muitas mudanças já foram feitas, e como estamos correndo contra o tempo, acho que já está devidamente pronto por enquanto.

**Comment by heylisten64** [comment]
Acredito que esteja ok para o PR. :100: 

Caso seja levantada novamente essa issue, seria legal **porém não essencial** preencher os tópicos 2, 4, 5, 7 com uma breve explicação dos tópicos. E também mais exemplos no tópico 4. Além disso, acrescentar os tópicos que não conseguimos preencher, que consta na documentação da IBM.

Porém muitas mudanças já foram feitas, e como estamos correndo contra o tempo, acho que já está devidamente pronto por enquanto.
