### ISSUE TITLE
Elaborar documento de visão

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#16]
Elaborar documento de visão

**Tarefas**

- [x] Criar estrutura de documento no Github Pages
- [x] Levantar dados do documento com o grupo de MDS
- [x] Utilizar documento da [IBM](https://www.ibm.com/support/knowledgecenter/pt-br/SSYMRC_6.0.5/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html) como apoio

**Critérios de aceitação**

- [x] O documento deve estar devidamente adicionado ao Github pages do grupo
- [x] Documentar na issue o  link do arquivo onde se pode encontrar o documento.

**Comment by Andreabenf** [comment]
Vamos dividir em topicos pra cada um fazer uma parte.
Que tal?

**Comment by pedroeagle** [comment]
acho uma ótima ideia

**Comment by gustable42** [comment]
Beleza

**Comment by Andreabenf** [comment]
Galera, após a gente dividir, bora editar por aqui:

https://hackmd.io/hAu1Q-GqROyFNIYJHLdfAQ#

**Comment by iurisevero** [comment]
Li aqui, os pontos 1,2, 3 e 4 da IBM são muito importantes, o 4 não totalmente, mais os primeiros tópicos dele.
O 5, 7 e 8 são descartáveis, assim como boa parte do 9 (acho que só o primeiro tópico é importante pra gente)
O 10 e 11 talvez sejam úteis no futuro, mas não agora
O 6 também é necessário
O ponto 3 tem alguns tópicos descartáveis, tipo o 4

Se todos concordarem, fazemos a divisão em cima desses tópicos e começamos a editar pelo link que o André mandou

**Comment by pedroeagle** [comment]
quem vcs acreditam ser os nossos clientes? só para confirmar o que coloquei no documento de visão, rs

**Comment by iurisevero** [comment]
> quem vcs acreditam ser os nossos clientes? só para confirmar o que coloquei no documento de visão, rs

O cliente eu n sei ainda, mas acredito que os usuários seriam alunos principalmente e pessoas com interesse em programação, mais específico, em python

**Comment by Andreabenf** [comment]
Ja podem ir commitando na branch issue 16 no documento de visão

**Comment by heylisten64** [comment]
Beleza, dei uma olhada aqui na documentação de visão de um trabalho exemplo, no documento de especificações básicas (IBM) e nos comentários de vocês... eu concordo com o que foi dito pelo Iuri, exceto pela parte do tópico 5 (recursos) ser descartável. Acho que ele é bem importante pra descrever cada serviço solicitado e a razão de utilizarmos determinada implementação pra garantir total funcionamento desse serviço. Nele a gente pode descrever cada função e os problemas de usabilidade que são tratados no decorrer do projeto, tratando apenas de funcionalidades, como manda a documentação de exemplo. Porém acredito que vamos trabalhar continuamente (e juntos!) nesse tópico e não tão no início assim. @iurisevero 
            Quanto a clientela eu acho que cabe não só aos alunos como também professores e instituições de ensino que desejam passar o conteúdo de programação. @pedroeagle 
            Na parte de divisão, achei que pelos tópicos 1 e 2 (introdução e posicionando) serem relativamente fáceis, posso juntar ambos pra um mesmo membro realizar enquanto que pela complexidade dos tópicos 3 e 4, caberiam dois membros para escreverem sobre cada um. Desses últimos dois penso que ele vai ser continuamente atualizado com a ajuda dos gpp, preservando, claro, sua perspectiva básica. Já os temas 9, 10, 11 são bem importantes mas serão trabalhados mais pra frente pelo que vi. O 7, 8 a princípio concordo de serem descartados mas seria bom trabalhar na inclusão deles pra ficar uma documentação bem completinha, já que temos que ter muitooo cuidado nessa parte. Com isso organizei da seguinte maneira a divisão:

**MEMBRO 1: @heylisten64  **     **MEMBRO 2: @pedroeagle **               **MEMBRO 3: @iurisevero **
1. Introdução                             3. Descrições da parte interessada        3. Descrições da parte interessada
2. Posicionando                         6. Restrições                                           9. Outros Requisitos
5. Recursos                                5. Recursos                                             5. Recursos
- Revisão geral                   

**MEMBRO 4: @Andreabenf **               **MEMBRO 5: @gustable42 **
  4. Visão geral do produto                        4. Visão Geral do produto
10. Requisitos de Documentação             11. Apêndice - atributos do recurso 
  5. Recursos                                                5. Recursos

A parte de recursos coloquei como tarefa de todos pra irmos complementando se necessário, cada um escrevendo sobre sua parte. Coloquei como revisão da escrita e de dados na minha parte, porque tô disposta a ir atrás e ajudar vocês caso seja preciso.Nos tópicos de duas pessoas vocês se juntam e organizam subtópicos pra cada um. Preciso saber se todos concordam ou se possuem outra sugestão, se está ok pra todo mundo!

**Comment by heylisten64** [comment]
Beleza, dei uma olhada aqui na documentação de visão de um trabalho exemplo, no documento de especificações básicas (IBM) e nos comentários de vocês... eu concordo com o que foi dito pelo Iuri, exceto pela parte do tópico 5 (recursos) ser descartável. Acho que ele é bem importante pra descrever cada serviço solicitado e a razão de utilizarmos determinada implementação pra garantir total funcionamento desse serviço. Nele a gente pode descrever cada função e os problemas de usabilidade que são tratados no decorrer do projeto, tratando apenas de funcionalidades, como manda a documentação de exemplo. Porém acredito que vamos trabalhar continuamente (e juntos!) nesse tópico e não tão no início assim. @iurisevero 
            Quanto a clientela eu acho que cabe não só aos alunos como também professores e instituições de ensino que desejam passar o conteúdo de programação. @pedroeagle 
            Na parte de divisão, achei que pelos tópicos 1 e 2 (introdução e posicionando) serem relativamente fáceis, posso juntar ambos pra um mesmo membro realizar enquanto que pela complexidade dos tópicos 3 e 4, caberiam dois membros para escreverem sobre cada um. Desses últimos dois penso que ele vai ser continuamente atualizado com a ajuda dos gpp, preservando, claro, sua perspectiva básica. Já os temas 9, 10, 11 são bem importantes mas serão trabalhados mais pra frente pelo que vi. O 7, 8 a princípio concordo de serem descartados mas seria bom trabalhar na inclusão deles pra ficar uma documentação bem completinha, já que temos que ter muitooo cuidado nessa parte. Com isso organizei da seguinte maneira a divisão:

MEMBRO 1: @heylisten64       MEMBRO 2: @pedroeagle                    MEMBRO 3: @iurisevero 
1. Introdução                             3. Descrições da parte interessada        3. Descrições da parte interessada
2. Posicionando                         6. Restrições                                           9. Outros Requisitos
5. Recursos                                5. Recursos                                             5. Recursos
- Revisão geral                   

MEMBRO 4: @Andreabenf                  MEMBRO 5: @gustable42 
  4. Visão geral do produto                        4. Visão Geral do produto
10. Requisitos de Documentação             11. Apêndice - atributos do recurso 
  5. Recursos                                                5. Recursos

A parte de recursos coloquei como tarefa de todos pra irmos complementando se necessário, cada um escrevendo sobre sua parte. Coloquei como revisão da escrita e de dados na minha parte, porque tô disposta a ir atrás e ajudar vocês caso seja preciso.Nos tópicos de duas pessoas vocês se juntam e organizam subtópicos pra cada um. Preciso saber se todos concordam ou se possuem outra sugestão, se está ok pra todo mundo!

**Comment by heylisten64** [comment]
Beleza, dei uma olhada aqui na documentação de visão de um trabalho exemplo, no documento de especificações básicas (IBM) e nos comentários de vocês... eu concordo com o que foi dito pelo Iuri, exceto pela parte do tópico 5 (recursos) ser descartável. Acho que ele é bem importante pra descrever cada serviço solicitado e a razão de utilizarmos determinada implementação pra garantir total funcionamento desse serviço. Nele a gente pode descrever cada função e os problemas de usabilidade que são tratados no decorrer do projeto, tratando apenas de funcionalidades, como manda a documentação de exemplo. Porém acredito que vamos trabalhar continuamente (e juntos!) nesse tópico e não tão no início assim. @iurisevero 
            Quanto a clientela eu acho que cabe não só aos alunos como também professores e instituições de ensino que desejam passar o conteúdo de programação. @pedroeagle 
            Na parte de divisão, achei que pelos tópicos 1 e 2 (introdução e posicionando) serem relativamente fáceis, posso juntar ambos pra um mesmo membro realizar enquanto que pela complexidade dos tópicos 3 e 4, caberiam dois membros para escreverem sobre cada um. Desses últimos dois penso que ele vai ser continuamente atualizado com a ajuda dos gpp, preservando, claro, sua perspectiva básica. Já os temas 9, 10, 11 são bem importantes mas serão trabalhados mais pra frente pelo que vi. O 7, 8 a princípio concordo de serem descartados mas seria bom trabalhar na inclusão deles pra ficar uma documentação bem completinha, já que temos que ter muitooo cuidado nessa parte. Com isso organizei da seguinte maneira a divisão:

**MEMBRO 1: @heylisten64  **                   
1. Introdução                                
2. Posicionando                                                             
5. Recursos                                                                       
- Revisão geral
              
    **MEMBRO 2: @pedroeagle ** 
 3. Descrições da parte interessada
 6. Restrições
 5. Recursos

 **MEMBRO 3: @iurisevero **
3. Descrições da parte interessada
9. Outros Requisitos
5. Recursos

**MEMBRO 4: @Andreabenf **
  4. Visão geral do produto
10. Requisitos de Documentação
  5. Recursos
                                    
 **MEMBRO 5: @gustable42 **
4. Visão Geral do produto
11. Apêndice - atributos do recurso 
5. Recursos

            A parte de recursos coloquei como tarefa de todos pra irmos complementando se necessário, cada um escrevendo sobre sua parte. Coloquei como revisão da escrita e de dados na minha parte, porque tô disposta a ir atrás e ajudar vocês caso seja preciso.Nos tópicos de duas pessoas vocês se juntam e organizam subtópicos pra cada um. Preciso saber se todos concordam ou se possuem outra sugestão, se está ok pra todo mundo!

**Comment by heylisten64** [comment]
Beleza, vi aqui os documentos de exemplo (IBM, Dulce) e o comentário de vocês. Acho que da fala do Iuri só discordo de descartar o tópico 5, que acho que ele é importante pra descrever cada serviço solicitado e a razão de x implementação pra garantir o total funcionamento daquele serviço, nele que a gente descreve cada função e os problemas de usabilidade que serão tratados no decorrer do projeto (tratando só de funcionalidades, no caso). Porém acredito que seja algo que vamos trabalhar continuamente e não tão no início assim.

**Comment by heylisten64** [comment]
Quanto a clientela, acredito que seja não só para os estudantes, que recebem a informação como também para os professores e instituições de ensino que dispersam o conhecimento.

**Comment by heylisten64** [comment]
Pensando na divisão, pelos tópicos 1 e 2 serem relativamente fáceis pensei em juntá-los para um membro só trabalhar neles. Já os temas 3 (por ter algumas estimações) e 4 (por ter edições contínuas preservando entretanto sua base) pela maior complexidade separei duas pessoas pra cuidar de cada um e os dois membros dividem o tema em subtópicos de forma justa. 9, 10 e 11 são bem importantes mas serão trabalhados mais na frente. 7,8 concordo de serem descartáveis mas se possível seria bom incluí-los na documentação, pra ficar uma coisa bem completinha! Daí pensei que eu, @heylisten64 poderia ficar com as partes 1, 2, 5 e revisão geral; @pedroeagle com as partes 3, 6, 5; @iurisevero 3, 9, 5; @Andreabenf 4,10, 5; @gustable42 4, 11, 5. Os números conforme os tópicos estudados no material d IBM. Se tiverem outra sugestão é só falar, mas se tiver ok pra vocês já podemos começar a documentação dessa maneira!

**Comment by gustable42** [comment]
@Andreabenf podemos fazer o tópico "Visão Geral de Produto" amanhã no almoço?

**Comment by Andreabenf** [comment]
@gustable42  Bora sim. Já vai lendo o exemplo da IBM

**Comment by gustable42** [comment]
@Andreabenf já dei uma lida, vou reler e tentar já ir construindo algumas ideias pra quando formos fazer, sair mais fácil

**Comment by pedroeagle** [comment]
uma dúvida: mantenho os títulos do exemplo da IBM? tive a impressão que são genéricos mas não tenho certeza. ex: Descrições da Parte Interessada e do Usuário, Demográficos de Mercado, Resumo da Parte Interessada

**Comment by iurisevero** [comment]
Dei uma olhada rápida no doc da Dulce, eles não mudaram muito do que estava na IBM. Confirma com o da Kalkuli, vê se eles alteraram muito ou não

**Comment by Andreabenf** [comment]
Galera, o tópico 10 é meio avançado pra começar a escever agora.
Achp que teremos que deixar pra uma sprint mais avançada

**Comment by iurisevero** [comment]
@pedroeagle Li a parte que você escreveu do tópico 3, pretendo alterar alguma coisas, tudo bem?
Mais em relação a parte interessada e aos usuários. Vou tentar detalhar um pouco mais esses pontos.

**Comment by pedroeagle** [comment]
> @pedroeagle Li a parte que você escreveu do tópico 3, pretendo alterar alguma coisas, tudo bem?
> Mais em relação a parte interessada e aos usuários. Vou tentar detalhar um pouco mais esses pontos.

tudo bem

**Comment by iurisevero** [comment]
Percebi aqui que para redimensionar uma imagem é melhor usar o método:
< img src="drawing.jpg" alt="drawing" width="200"/ >
 (remove os espacos entre os simbolos de menor e maior)
ao invés de:
![](./pic/pic1_50.png =WIDTHxHEIGHT)

Ambos funcionam no hackmd, mas só o primeiro funcionou no git

**Comment by Andreabenf** [comment]
Podemos fechar então?
