### ISSUE TITLE
Refatorar conteúdos inseridos

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#162]
Refatorar conteúdos inseridos até o presente instante que estejam fora do padrão aceitado quanto a quantidade de linhas.

**Tarefas**

- [x] Refatorar conteúdos inseridos de forma a minimizar a quantidade de linhas de conteúdo, tentando resumir ao máximo a explicação ao usuário.

**Critérios de aceitação**

- [x] Bot respondendo aos questionamentos do usuário
- [x] Conteúdos refatorados

**Comment by heylisten64** [comment]
Irei refatorar os conteúdos das issues #43, #66, #68, #87, #129 .

**Comment by iurisevero** [comment]
Posso ficar com os #47 #117 #114

**Comment by pedroeagle** [comment]
Vou refatorar a issue #101

**Comment by Andreabenf** [comment]
irei refatorar as issues #44 e #69

**Comment by Andreabenf** [comment]
Galera, só lembrando que como vamos trabalhar na mesma issue, sempre deem um pull antes de commitar

**Comment by iurisevero** [comment]
@gustable42 tava olhando a parte de variáveis e não vi muito o que mudar. Reduzi os exemplos e tirei algumas palavras nos outros. Depois dá uma olhada, ver se consegue tirar algo.

**Comment by iurisevero** [comment]
@heylisten64 estava o tópico de curiosidades, acho que daria certo separar as mensagens como textos diferentes. Acho que resolveria o problema nesse caso.

**Comment by heylisten64** [comment]
sim sim! tinha pensado nisso já! assim que chegar em casa eu altero

**Comment by heylisten64** [comment]
## utter_sobre_aix:

    - text: |
	    Você ainda não me conhece?! Por onde é que você navegava 
	    esse tempo todo? Eu sou a cabra Aix e estou aqui para te
	    auxiliar nos seus estudos e garantir sua nota 10 quando
	    o assunto é linguagem de programação Python!

    - text: |
        Então você quer saber mais sobre mim? Vou te contar um
        segredo: sabia que eu fui criada por estudantes da
        Universidade de Brasília? Eu aposto que se você se
        esforçar e estudar muito junto comigo você tambéem 
        será capaz de criar uma ferramenta de estudo tão 
        maneira quanto essa!

    - text: |
        Aí vai uma charada: Quem é, quem é... que te ajuda com
        a sintaxe Python, tira suas dúvidas, e ainda te redireciona
        exercícios de programação? Béem, se você falou seu
        professor, você acertou... Mas sabia que eu também posso
        te ajudar com isso?

    - text: |
        Já vi que você não me conhece muito béem... Mas aposto
        que você vai gostar de mim! Inclusive, se quiser me
        apresentar aos seus amigos, fala para eles que eles
        precisam ter um desses sistema operacionais: Linux, 
        Windows ou MacOS. E não esqueça, você tambéem precisa
        do ambiente Jupyter instalado! 
        Ah!! E agora também estou no telegram!

    - text: |
        A cabra que te manda exercícios na hora... que tira
        suas dúvidas sem nenhuma demora... que está todo tempo
        junto com você... Essa cabra sou eu!

    - text: |
        Quer saber uma curiosidade sobre mim? Sabia que meu nome 
        veio da mitologia romana? Acontece que há muito tempo
        atrás quem amamentou o deus Júpiter foi a cabra Aix.
        Por eu ter sido criada integrada nessa plataforma
        Jupyter, nasceu a ideia do meu nome! Quanta imaginação,
        não?

## utter_curiosidades_python:
    - text: |
        O nome Python não foi inspirado no réptil, 
        mas sim no grupo humorístico britânico Monty Python.

    - text: |
        Existe um poema da linguagem Python chamado Zen do Python
        que resume as boas práticas.

    - text: |
        Tenta usar o comando "python" e depois "import this" no
        terminal... você vai ver algo béem legal!!

    - text: |
        O Python serviu de inspiração para muitas linguagens
        novas!!

    - text: |
        Python foi feita com base na linguagem ABC, com A de
        aix, Bée de bode e C de capim!

    - text: |
        Você sabia que o Python foi considerado a 3ª linguagem
        "mais amada" segundo a pesquisa conduzida pelo Stack
        Overflow em 2018?!

##  utter_manter_conversa:
    - text: |
        Bée bée... o que temos pra hoje?

    - text: |
        Sobre o que você deseja conversar agora, meu consagrado?

    - text: |
        E então, qual a sua maior dificuldade em Python?

    - text: |
        Sobre o que mais você deseja sabéer?

    - text: |
        Béeleza? Gostaria de mais alguma informação?

    - text: |
        Em que mais eu posso ser útil? Bée
##   utter_sobre_laços:
    - text: |
        Estruturas de repetição são funções capazes de iterar
        determinada ação. Nelas, você pode determinar uma meta
        e uma instrução. Ou seja, você vai realizar determinada
        ação repetidas vezes até alcançar o resultado que deseja! 
        Mas não seja béesta, tenha cuidado, pois você pode cair em
        um loop infinito! Assim, para conseguir fazer isso,
        temos os laços for e while da linguagem Python. Ficou
        béem claro?

    - text: |
        Você já tentou contar até 10 no python? Tenta aí!
        Se você utilizou uma função print para cada número,
        tenho que te contar um segredo: dá para fazer isso
        com um só print! Como? Béem... você vai utilizar os
        laços, que, basicamente são capazes de reproduzir 
        determinada ação. Temos como estruturas do Python o
        WHILE e o FOR. Quer saber mais sobre eles? Posso 
        te dar alguns exemplos, se desejar!

Aqui estão as alterações que fiz até agora... Pretendo adicionar mais templates na utter sobre laços #87 além de alguns outros templates na de exemplo de laços #129, junto a alguns recursos visuais para facilitar o aprendizado. Comentei aqui no caso de algum de vocês tiverem mais alguma ideia pra esses conteúdos, já que é bom uma opinião diferente sobre. Qualquer ideia é bem vinda! =)
E se precisarem de algo também na refatoração de vocês, é só gritar! hahah @iurisevero @pedroeagle @Andreabenf @gustable42 

edit **utter_sobre_aix**

**Comment by heylisten64** [comment]
Ordenei a ordem na domain para que fosse mais fácil compararmos os conteúdos visando uma melhor refatoração...

**Comment by iurisevero** [comment]
Separei as intents e stories nas seguintes pastas:
* main.md - com conteúdos gerais
* sobre.md
* exercicio.md
* exemplo.md
* conteudo_extra.md

de acordo com a divisão feita pela @heylisten64 no domain

**Comment by pedroeagle** [comment]
Edições que realizei no sábado na utter_sobre_condicionais:
# Utter:
     Bom, uma estrutura condicional são ações que podem ou não serem executadas no seu programa.
     É necessário que uma condição seja testada para que que essas ações sejam executadas ou não.
     SE a condição é satisfeita, executamos o que foi definido. SE NÃO, pulamos e continuamos o programa.

**Comment by Andreabenf** [comment]
Acabei de ver aqui que o iuri ja tinha refatorado a issue #69.
Será que ja podemos abrir pra review e tentar pr hj de noite?

**Comment by heylisten64** [comment]
É o que planejo andré! vou só trabalhar nos recursos visuais que a Kamilla tinha pedido! Talvez acrescentar algo nas issues de vocês... ainda temos tempo pra essa issue!

**Comment by iurisevero** [comment]
Acredito que esteja tudo pronto. Vou dar um pull na devel para resolver possíveis conflitos e abrir o PR!

**Comment by heylisten64** [comment]
Trabalharei os recursos visuais nas utters de exemplos, apenas, por enquanto. Se necessário, verei a possibilidade de elaborar para outros tópicos.
