### ISSUE TITLE
Preparar Release 1

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#163]
Preparar release 1 (apresentação, documentos...)

**Tarefas**

- [x] Decidir tópicos a serem abordados
- [x] Montar apresentação
- [x] preparar ambiente de apresentação da Aix (Jupyter e Telegram)

**Critérios de aceitação**

- [x] Adicionar apresentação no github Pages

**Comment by heylisten64** [comment]
https://view.genial.ly/5cc3beebdecf900f57ed5010/presentation-aix-chatbot-de-aprendizado-pythob o slide da nossa apresentação tá feito aqui!

**Comment by heylisten64** [comment]
Resolvemos tudo da apresentação em reuniões presenciais e por hangouts no domingo, na segunda, na terça e na quarta. Retoques finais para a R1 :1st_place_medal:
