### ISSUE TITLE
Elaborar documento de arquitetura

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#17]
Elaborar documento de arquitetura

**Tarefas**

- [x] Criar estrutura de documento no Github Pages
- [x] Levantar dados do documento com o grupo de MDS
- [x] Utilizar documento da [IBM](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwjl7cre9pjhAhUDErkGHb2eA_IQFjAAegQIARAC&url=https://www.dca.ufrn.br/~anderson/FTP/dca0120/modelodocarquiteturasoftware.doc&usg=AOvVaw2P9L4xfD4kcFo0YtBNmuu8) como apoio

**Critérios de aceitação**

- [x] O documento deve estar devidamente adicionado ao Github pages do grupo
- [x] Documentar na issue o  link do arquivo onde se pode encontrar o documento.

**Comment by iurisevero** [comment]
Galera, tava lendo o documento de arquitetura da IBM e acredito q os tópicos mais relevantes são 1,2,3,4 e 8.
10 e 11 são importantes também, assim como alguns outros, mas acredito de devemos deixá-los mais pro futuro.
A etapa 7, de implantação faz referência aos pipelines, então ,sem dúvidas, voltaremos depois no nosso documento para atualizá-lo

**Comment by iurisevero** [comment]
Se todos estiverem d acordo com essa divisão, eu gostaria de ficar com a parte 3 e ajudar quem ficar com a parte 1

**Comment by iurisevero** [comment]
https://hackmd.io/FCFH4CrkTya1ZBrckPKk9A
Link pra nota do hackmd, bora tentar editar por aqui xD

**Comment by iurisevero** [comment]
Iniciei a branch com o documento de arquitetura e já fiz uma parte do texto

**Comment by iurisevero** [comment]
@GuiMarques98 todas ferramentas descritas no GCS  devem entrar como Tecnologia na parte de metas e restrições do documento?
Flake8, Git, Flask... entre outras

**Comment by iurisevero** [comment]
Adicionei alguns casos de uso no documento, de acordo com as funcionalidades descritas no documento de visão e com as discutidas durante a reunião de hoje.
Caso lembrem de alguma outra, complementem lá

**Comment by Lucas362** [comment]
> https://hackmd.io/FCFH4CrkTya1ZBrckPKk9A
> Link pra nota do hackmd, bora tentar editar por aqui xD

Galera, sobre essa disponibilização de links para o público, recomendo que tenham alguma forma de backup (mesmo que o HackMD disponibilize um log do documento, todo cuidado é pouco), pois esse link permite a qualquer um editar ;)

**Comment by Andreabenf** [comment]
Belezinha!

**Comment by Andreabenf** [comment]
Galera, bora usar tbm os docs desse projeto aqui ( https://github.com/fga-eps-mds/2017.2-Receita-Mais )
A documentação ta boa e concisa.

**Comment by gustable42** [comment]
@GuiMarques98 Existe algum outro requisito não funcional além dos citados na documentação do Receita Mais que seria conveniente para nosso projeto, ou aqueles já abrangem todo o tópico?
