### ISSUE TITLE
Bot não reage corretamente com o comando /start

### ISSUE THREAD

**Issue by mateusnr** [fga-eps-mds/2019.1-Grupo-1#205]
**Descreva o bug**
Quando você abre um chat de um bot pelo username (no caso desse bot @Aix_chatbodebot), ele oferece a opção de iniciar e quando você clica, ele manda o comando `/start` para o bot, mas a resposta que vem é de que ele não está entendendo o comando.

**Comportamento esperado**
Uma mensagem de boas-vindas ou coisa do tipo.

**Comportamento encontrado**
Mensagens variadas do tipo "não entendi"

**Como reproduzir**
1. Digite `/start` no chat do bot e mande

**Comment by Lucas362** [comment]
Muito obrigado pela contribuição, esse erro será averiguado e solucionado assim que possível
