### ISSUE TITLE
Adicionar tópico com a definição do que são vetores

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#207]
Adicionar conteúdo referente ao tópico definição do que são vetores
**Tarefas**

- [x] Criar conteúdo referente a ação de explicar sobre vetores
- [x] Inserir conteúdo referente a ação de explicar sobre vetores. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
## Array
### Definição
* Um array é uma estrutura de dados homogênea que mantém uma série de elementos de dados de mesmo tipo. Pode-se acessar os elementos individuais armazenados no array por meio de uma posição de índice associada, geralmente numérica. 
* No geral, os arrays possuem tamanho fixo, ou seja, número de posições definida; em algumas linguagens de programação, existem estruturas de arrays que possuem tamanho variável. Vamos estudar aqui os arrays tradicionais, de tamanho especificado.

### Classificação
* Os arrays são classificados de acordo com a sua dimensão de armazenamento de dados, como segue:
	* Unidimensional: Vetor
	* Bidimensional: Matriz
	* Tridimensional: Cubo

## Vetores
### Definição:
* É um conjunto de elementos consecutivos, do mesmo tipo e que podem ser acessados individualmente, a partir de um único nome
* Vetor (array uni-dimensional) é uma variável que armazena várias variáveis do mesmo tipo.
* Um vetor é uma sequência de dados ocupando posições consecutivas de memória e por isso existe uma ordem natural 
* Um vetor é um array unidimensional, ou seja, de uma única dimensão; é análogo a uma linha única de dados em uma planilha ou tabela

### Conteúdo Extra:
* [Curso Python #17 - Listas (Parte 1)](https://www.youtube.com/watch?v=N1hTsbW50eM&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=10&t=0s)
* [Vetores em Python](https://pt.stackoverflow.com/questions/202753/vetores-em-python)
* [Introdução aos vetores em Python](https://www.ime.usp.br/~leo/mac2166/2017-1/introducao_vetores_python.html)

### Exercícios:
* [Substituição em Vetor I](https://www.urionlinejudge.com.br/judge/pt/problems/view/1172)
* [Preenchimento de Vetor I](https://www.urionlinejudge.com.br/judge/pt/problems/view/1173)
* [Seleção em Vetor I](https://www.urionlinejudge.com.br/judge/pt/problems/view/1174)
* [Troca em Vetor I](https://www.urionlinejudge.com.br/judge/pt/problems/view/1175)
* [Exercício Python #078 - Maior e Menor valores na Lista](https://www.youtube.com/watch?v=q8Z1cRdJnfk&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=11&t=0s)
* [Exercício Python #080 - Lista ordenada sem repetições](https://www.youtube.com/watch?v=QDpwjBYRcVE&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=13&t=0s)
* [Exercício Python #081 - Extraindo dados de uma Lista
](https://www.youtube.com/watch?v=SXJKAVVlvGA&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=14&t=0s)

### Referência
* VETORES E MATRIZES, Prof. Felipe Duerno
* https://dicasdeprogramacao.com.br/o-que-sao-vetores-e-matrizes-arrays/
* https://www.ime.usp.br/~leo/mac2166/2017-1/introducao_vetores_python.html
* http://www.bosontreinamentos.com.br/logica-de-programacao/17-logica-de-programacao-vetores-definicao-e-declaracao/

**Comment by iurisevero** [comment]
## intent:sobre_vetores
- o que são vetores
- me fale sobre vetor
- quero saber o que é um array
- explique o que é um array
- desejo saber o que é um vetor
- vetores
- array unidimensional
- discorra a respeito de vetor
- quero que me diga algo sobre vetor
- poderia me explicar sobre vetores
- você sabe o que são vetores

## utter_sobre_vetores:
Um vetor é um conjunto de elementos consecutivos que podem ser acessados por um mesmo nome. Isto ééé várias regiões na memória em sequência!
Um vetor também pode ser chamado de Array Unidimensional.

**Comment by KahCosta** [comment]
Achei que está bem legal! mas seria legal inserir um pouco mais de imagens afim de reduzir um pouco o texto de explicação

**Comment by iurisevero** [comment]
Para facilitar a distribuição do conteúdo e diminuir a quantidade de conflitos na hora do Pull Request, irei trabalhar as 4 issues que dizem respeito a vetores em uma branch só.

**Comment by KahCosta** [comment]
ok!
