### ISSUE TITLE
Adicionar tópico com exemplos de utilização de vetores

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#208]
Adicionar conteúdo referente ao tópico com exemplos de utilização de vetores

**Tarefas**

- [x] Criar conteúdo referente a ação de apresentar exemplos de utilização de vetores na linguagem python.
- [x] Inserir conteúdo referente a ação de apresentar exemplos de vetores. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
## intent:exemplo_vetores
- gostaria de ver exemplos sobre vetor
- exemplos de vetores
- você tem algum exemplo de vetores
- código usando vetor
- exemplo prático de vetor
- como fica um array na prática
- exemplifique vetores
- poderia me mostrar um exemplo de vetor
- desejo ver exemplos de vetores
- quero exemplos de array unidimensional 
- me dê um exemplo de vetor

## utter_exemplo_vetores:
Béeem, um exemplo de vetor? Imagine que eu quero contar quantos fenos eu comi na semana. Como eu faria isso? Com um vetor de fenos por dia!! Ficaria mais ou menos assim:
```
    fenos_por_dia = [3, 3, 4, 3, 2, 3, 3]
```
E se eu quiser saber quantos fenos eu comi no Domingo é só acessar o vetor na posição 0!
```
    print(fenos_por_dia[0])
    # 3
```
Lembrando que as posições começam a ser contadas a partir 0.

**Comment by iurisevero** [comment]
Achei que seria interessante inserir a seguinte imagem no texto de exemplo para vetores, mas, como dito no comentário de matrizes, manter a explicação original.

![](https://i.imgur.com/soiRg1i.png)
