### ISSUE TITLE
Adicionar tópico com linkagem estática para conteúdo extra sobre vetores

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#210]
Adicionar conteúdo referente ao tópico linkagem estática para conteúdo extra sobre vetores

**Tarefas**

- [x] Pesquisar link referente a utilização de vetores na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre a utilização de vetores.

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
## intent:conteudo_extra_vetores
- tem algum link pra entender array?
- mais conteúdo sobre vetores
- links externos para vetores
- links sobre vetor
- mais informações sobre vetores
- conteudo aprofundado de vetores
- mais sobre array unidimensional
- tem links sobre vetores?
- sites vetores
- link array
- conteúdos extra sobre arrays unidimensionais
- nao entendi vetores, algum site?
- me dá mais conteúdo sobre vetores, pf

## utter_conteudo_extra_vetores:
Não entendeu muito béem? Pesquisei um links muito legais para você! Tem uma vídeo aula e duas explicações escritas.
* Curso Python #17 - Listas (Parte 1)(https://www.youtube.com/watch?v=N1hTsbW50eM&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=10&t=0s)
* Vetores em Python(https://pt.stackoverflow.com/questions/202753/vetores-em-python)
* Introdução aos vetores em Python(https://www.ime.usp.br/~leo/mac2166/2017-1/introducao_vetores_python.html)
