### ISSUE TITLE
Adicionar tópico com linkagem estática para sugestão de exercício sobre uso de vetores

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#211]
Adicionar conteúdo referente ao tópico linkagem estática para sugestão de exercício sobre uso de vetores

**Tarefas**

- [x] Pesquisar link referente a sugestão de exercícios referentes ao uso de vetores na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre sugestão de exercício sobre utilização de vetores. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
## intent:exercicios_vetores
- desejo fazer exercícios sobre vetores
- exercício vetor
- link de exercícios sobre arrays
- quero exercicios de vetores
- questões sobre vetores
- treinar arrays
- atividades de vetor
- URI array unidimensional
- me mostra exercícios sobre array 
- poderia me passar questões sobre vetores
- gostaria de fazer exercícios sobre vetor

## utter_exercicios_vetores:
Então você se sente pronto para praticar?! Muito béem, dê uma olhada nesses exercícios, tem em vídeo e em texto tambéem, mas tome cuidado que é mais difícil que comer capim!
* Substituição em Vetor I(https://www.urionlinejudge.com.br/judge/pt/problems/view/1172)
* Preenchimento de Vetor I(https://www.urionlinejudge.com.br/judge/pt/problems/view/1173)
* Exercício Python #078 - Maior e Menor valores na Lista(https://www.youtube.com/watch?v=q8Z1cRdJnfk&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=11&t=0s)
* Exercício Python #080 - Lista ordenada sem repetições(https://www.youtube.com/watch?v=QDpwjBYRcVE&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=13&t=0s)

**Comment by KahCosta** [comment]
ta ok!
