### ISSUE TITLE
Adicionar tópico com a definição do que são matrizes

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#212]
Adicionar conteúdo referente ao tópico definição do que são matrizes

**Tarefas**

- [x] Criar conteúdo referente a ação de explicar sobre matrizes
- [x] Inserir conteúdo referente a ação de explicar sobre matrizes. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
## Array
### Definição
* Um array é uma estrutura de dados homogênea que mantém uma série de elementos de dados de mesmo tipo. Pode-se acessar os elementos individuais armazenados no array por meio de uma posição de índice associada, geralmente numérica. 
* No geral, os arrays possuem tamanho fixo, ou seja, número de posições definida; em algumas linguagens de programação, existem estruturas de arrays que possuem tamanho variável. Vamos estudar aqui os arrays tradicionais, de tamanho especificado.

### Classificação
* Os arrays são classificados de acordo com a sua dimensão de armazenamento de dados, como segue:
	* Unidimensional: Vetor
	* Bidimensional: Matriz
	* Tridimensional: Cubo


## Matrizes
### Definição:
* Vetores são arrays unidimensionais e matrizes são
arrays bidimensionais
*  Uma matriz é uma coleção de variáveis de mesmo tipo, acessíveis com um único nome e armazenados contiguamente na memória. A individualização de cada variável de um vetor é feita através do uso de índices. Os Vetores são matrizes de uma só dimensão.
* Uma vez que um vetor/lista é armazenado consecutivamente na memória, então podemos armazenar vários vetores também consecutivamente para obter algo que represente (e seja tratado como) matriz. 

### Conteúdo Extra:
* [Curso Python #17 - Listas (Parte 2)](https://www.youtube.com/watch?v=YV_JQmZNFsk&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=17&t=0s)
* [Introdução aos vetores em Python](https://www.ime.usp.br/~leo/mac2166/2017-1/introducao_vetores_python.html)
* [Matrizes IC-UFF](http://www2.ic.uff.br/~vanessa/material/prog-python/07-Matrizes.pdf)
* [Aula 11 - Te´orica: Matrizes UFRJ](https://www.cos.ufrj.br/~bfgoldstein/python/compI/slides/aula11_teorica.pdf)

### Exercícios:
* [Exercício Python #086 - Matriz em Python](https://www.youtube.com/watch?v=EGmlFdwD4C4&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=20&t=0s)
* [Exercício Python #087 - Mais sobre Matriz em Python](https://www.youtube.com/watch?v=QhS829x6up4&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=21&t=0s)
* [Linha na Matriz](https://www.urionlinejudge.com.br/judge/pt/problems/view/1181)
* [Coluna na Matriz](https://www.urionlinejudge.com.br/judge/pt/problems/view/1182)
* [Acima da Diagonal Principal](https://www.urionlinejudge.com.br/judge/pt/problems/view/1183)


### Referência
* VETORES E MATRIZES, Prof. Felipe Duerno
* https://www.inf.pucrs.br/~pinho/LaproI/Vetores/Vetores.htm
* https://www.ime.usp.br/~leo/mac2166/2017-1/introducao_vetores_python.html
* http://www.bosontreinamentos.com.br/logica-de-programacao/17-logica-de-programacao-vetores-definicao-e-declaracao/

**Comment by iurisevero** [comment]
## intent:sobre_matrizes
- o que são matrizes
- me fale sobre matriz
- quero saber o que é um array bidimensional
- explique o que é um array bidimensional
- desejo saber o que é um matriz
- matrizes
- array bidimensional
- discorra a respeito de matriz
- quero que me diga algo sobre matriz
- poderia me explicar sobre matrizes
- você sabe o que são matrizes

## utter_sobre_matrizes:
Uma matriz pode ser representada como um vetor de vetores, ou seja, ela também é uma coleção de variáveis acessíveis com um único nome e armazenados contiguamente na memória.
Um matriz também pode ser chamado de Array Bidimensional.

**Comment by KahCosta** [comment]
Gostei! como falei na issue sobre vetores tente adicionar imagens de forma que possa auxiliar na redução do texto explicativo

**Comment by iurisevero** [comment]
Para facilitar a distribuição do conteúdo e diminuir a quantidade de conflitos na hora do Pull Request, irei trabalhar as 4 issues que dizem respeito a matrizes em uma branch só.

**Comment by KahCosta** [comment]
ok!
