### ISSUE TITLE
Adicionar tópico com exemplos de utilização de matrizes

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#213]
Adicionar conteúdo referente ao tópico com exemplos de utilização de matrizes

**Tarefas**

- [x] Criar conteúdo referente a ação de apresentar exemplos de utilização de matrizes na linguagem python.
- [x] Inserir conteúdo referente a ação de apresentar exemplos de matrizes. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
## intent:exemplo_matrizes
- gostaria de ver exemplos sobre matriz
- exemplos de matrizes
- você tem algum exemplo de matrizes
- código usando matriz
- exemplo prático de matriz
- como fica um array na prática
- exemplifique matrizes
- poderia me mostrar um exemplo de matriz
- desejo ver exemplos de matrizes
- quero exemplos de array bidimensional 
- me dê um exemplo de matriz

## utter_exemplo_matrizes:
Você quer ver uma matriz na prática? Vou te dar um exemplo!
Digamos que eu queira marcar quantas dúvidas eu tirei em um mês, para isso poderia fazer uma matriz de dúvidas por dia, separando por semanas para ficar mais fácil de ler.
```
    duvidas_por_mes = [ [0, 4, 7, 9, 5, 3, 1],
                        [0, 0, 2, 4, 3, 2, 2],
                        [1, 2, 4, 3, 7, 1, 1],
                        [0, 5, 6, 7, 7, 5, 0] ]
```
Sendo as linhas referentes as semanas e as colunas os dias! E para acessar as dúvidas de segunda da primeira semana seria: 
```
    print(duvidas_por_mes[0][1])
    # 4
```
Lembrando que as posições começam a ser contadas a partir 0.

**Comment by iurisevero** [comment]
Pensei em adicionar a seguinte imagem no texto de exemplo, como sugerido pela @KahCosta no comentário de feedback.
![](https://i.imgur.com/7c8UasQ.png)

Acho que seria uma boa manter também o texto para que o usuário possa ver como é escrita essa estrutura em python.

**Comment by KahCosta** [comment]
ótimo!
