### ISSUE TITLE
Adicionar tópico com linkagem estática para conteúdo extra sobre matrizes

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#214]
Adicionar conteúdo referente ao tópico linkagem estática para conteúdo extra sobre matrizes

**Tarefas**

- [x] Pesquisar link referente a utilização de matrizes na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre a utilização de matrizes.

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
## intent:conteudo_extra_matrizes
- tem algum link pra entender array bidimensional?
- mais conteúdo sobre matrizes
- links externos para matrizes
- links sobre matriz
- mais informações sobre matrizes
- conteudo aprofundado de matrizes
- mais sobre array bidimensional
- tem links sobre matrizes?
- sites matrizes
- link array bidimensional
- conteúdos extra sobre arrays bidimensionais
- nao entendi matrizes, algum site?
- me dá mais conteúdo sobre matrizes, pf

## utter_conteudo_extra_matrizes:
Olha esse links sobre matrizes que eu achei! Neles explica muito béem!!! Tem três aulas em texto para você e uma vídeo aula, se preferir.
* Curso Python #17 - Listas (Parte 2)(https://www.youtube.com/watch?v=YV_JQmZNFsk&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=17&t=0s)
* Introdução aos vetores em Python(https://www.ime.usp.br/~leo/mac2166/2017-1/introducao_vetores_python.html)
* Matrizes IC-UFF(http://www2.ic.uff.br/~vanessa/material/prog-python/07-Matrizes.pdf)
* Aula 11 - Teórica: Matrizes UFRJ(https://www.cos.ufrj.br/~bfgoldstein/python/compI/slides/aula11_teorica.pdf)

**Comment by KahCosta** [comment]
ótimo!
