### ISSUE TITLE
Adicionar tópico com linkagem estática para sugestão de exercício sobre uso de matrizes

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#215]
Adicionar conteúdo referente ao tópico linkagem estática para sugestão de exercício sobre uso de matrizes

**Tarefas**

- [x] Pesquisar link referente a sugestão de exercícios referentes ao uso de matrizes na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre sugestão de exercício sobre utilização de matrizes. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
## intent:exercicios_matrizes
- desejo fazer exercícios sobre matrizes
- exercício matriz
- link de exercícios sobre arrays bidimensionais
- quero exercicios de matrizes
- questões sobre matrizes
- treinar arrays bidimensionais
- atividades de matriz
- URI array bidimensinal
- me mostra exercícios sobre array bidimensional
- poderia me passar questões sobre matrizes
- gostaria de fazer exercícios sobre matriz

## utter_exercicios_matrizes:
Quer praticar seus conhecimentos sobre matriz..? Tenho uns exercícios béem legais para você!!
* Exercício Python #086 - Matriz em Python(https://www.youtube.com/watch?v=EGmlFdwD4C4&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=20&t=0s)
* Exercício Python #087 - Mais sobre Matriz em Python(https://www.youtube.com/watch?v=QhS829x6up4&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH&index=21&t=0s)
* Linha na Matriz(https://www.urionlinejudge.com.br/judge/pt/problems/view/1181)
* Coluna na Matriz(https://www.urionlinejudge.com.br/judge/pt/problems/view/1182)

**Comment by KahCosta** [comment]
acho que você pode aumentar um pouco o vocabulário para intent de exercicios_matrizes
