### ISSUE TITLE
Documentar pipeline de deploy

### ISSUE THREAD

**Issue by Yoshida-Eduardo** [fga-eps-mds/2019.1-Grupo-1#221]
**Tarefas**

- [x] Adicionar documentação descrevendo a pipeline de deploy atual.

**Critérios de aceitação**

- [x] Documentação estar disponibilizada no github pages.
- [x] Documentação deve refletir a atual pipeline.

**Comment by KahCosta** [comment]
@Yoshida-Eduardo pode documentar o link para acesso ao doc do pipeline de deploy aqui?
