### ISSUE TITLE
Evoluir intents de acordo com feedback dos usuários

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#222]
Evoluir intents e utters de modo a aumentar o vocabulário do bot.

**Tarefas**

- [x] Evoluir arquivo de intents
- [x] Construir imagens para utilização nas utters utilizadas no bot

**Critérios de aceitação**

- [x] Bot se comunicando bem por meio de diversos tipos de entrada do usuário.
- [x] Bot lidando com imagens nas utters de forma a reduzir os textos presentes na explicação.

**Comment by heylisten64** [comment]
Vou continuar a elaboração das imagens, como eu já estava fazendo em outras issues! Quanto a revisão das intents, parece que agora o rasa tá diferenciando acentuação, vamos checar isso! 
Prestar atenção quanto a intents semelhantes em utters diferentes também!

**Comment by KahCosta** [comment]
refatorem todas as intents colocando exemplos com e sem acento

**Comment by heylisten64** [comment]
Verifiquei a acentuação em actions, extra, exemplos e sobre. Porém, vendo as intents acho que tem muuuuita coisa a ser melhorada. Esse link pode nos ajudar: https://github.com/lappis-unb/tais/wiki/Intents-Eficientes

**Comment by heylisten64** [comment]
para facilitar, coloquei em tópicos o mais importante a ser levado em conta para refatorar as intents:

* Elaborar para que cada Intent tenha PELO MENOS 20 exemplos, sendo 10 de perguntas e 10 palavras-chaves sobre o tema
* Criar frases curtas, sem letras maiúsculas, sem erros ortográficos;
* Observar sinais de pontuação, duplicata;
* Evitar o uso excessivo de pronomes ou formas repetidas de se perguntar;
**P.S:** existem casos que não se pode se livrar totalmente da construção com o uso de pronomes, nestes casos deve-se ficar atento e balancear as Intents que possuam essa particularidade.
* Pensar em como o usuário perguntaria sobre aquele tema;
*  Tente ao máximo não repetir pronomes ou formas de perguntar nos exemplos da Intent;

**Comment by heylisten64** [comment]
O que eu sugiro é refazer todas as intents conforme essas regras, uma a uma e ir olhando o desenvolvimento da equipe ao final, para ver se pode acrescentar algo que está lá! Além de deixarmos em blocos palavra-chave e perguntas, para ficar mais organizado.

**Comment by Andreabenf** [comment]
Eai galera, tive uns feedbacks sobre o menu ajuda, vou dar uma arrumada

**Comment by Andreabenf** [comment]
Só lembrando que estamos todos trabalhando na mesma branch, então sempre lembrem de dar push e pull

**Comment by heylisten64** [comment]
Houve uma "invasão" na branch já que muitas mudanças foram requisitadas após o feedback dos usuários kkk

**Comment by iurisevero** [comment]
Como ficou decidido na daily, eu alterei a utters para tentar guiar o usuário durante a conversa, mostrando todas funcionalidades da Aix.
O fluxo para o qual o usuário é guiado é o mesmo que colocamos de base para as stories de "full_path" que criamos! Ele segue o seguinte padrão:
informações sobre o conteúdo -> exemplos de utilização -> links de conteúdo extra -> links de exercícios
Ao final do fluxo, é explicitado ao usuário a possibilidade do bot se conectar no StackOverflow
(eu tinha comentado isso mais cedo, mas acho que minha internet caiu na hora de publicar, já que o comentário não apareceu)

**Comment by heylisten64** [comment]
processo de criação - exemplo de condicionais
![image](https://user-images.githubusercontent.com/43069991/57009230-d48c2c00-6bcb-11e9-8ec4-48e08ad29969.png)

**Comment by heylisten64** [comment]
![Untitled - 7](https://user-images.githubusercontent.com/43069991/57009575-bc1d1100-6bcd-11e9-9c3e-d97bc880dfee.png)

**Comment by heylisten64** [comment]
Para o exemplo de **condicionais**:
![Condicionais-01](https://user-images.githubusercontent.com/43069991/57010199-d658ee00-6bd1-11e9-92dc-02c556380a26.png)

**Comment by heylisten64** [comment]
Para o exemplo de **variáveis**:
![Variaveis-01](https://user-images.githubusercontent.com/43069991/57011190-e58e6a80-6bd6-11e9-9fd9-c8c91e6d1210.png)

**Comment by KahCosta** [comment]
ficoou muito bom Gabi!

**Comment by heylisten64** [comment]
Amigos, na hora da criação da intent, eu tava conversando com o @Andreabenf , peço que façam desse modo para que mantenhamos o padrão e não precisemos ficar refatorando as intents. Sigam o passo a passo e dará tudo certo:
* escolham palavras chaves (já escolhemos algumas para cada arquivo)
* implementem nas palavras chaves o conteúdo
* diferenciem acentuações 
* EVITEM AO MÁXIMO pronomes e frases com muito frufru, coloque apenas a parte essencial da frase para ela entrar na utter
* vale a pena dar uma olhada no conteúdo refatorado por mim e pelo andré, pra tomar base para outras issues!

@iurisevero @gustable42 @pedroeagle

**Comment by heylisten64** [comment]
> para facilitar, coloquei em tópicos o mais importante a ser levado em conta para refatorar as intents:
> 
> * Elaborar para que cada Intent tenha PELO MENOS 20 exemplos, sendo 10 de perguntas e 10 palavras-chaves sobre o tema
> * Criar frases curtas, sem letras maiúsculas, sem erros ortográficos;
> * Observar sinais de pontuação, duplicata;
> * Evitar o uso excessivo de pronomes ou formas repetidas de se perguntar;
>   **P.S:** existem casos que não se pode se livrar totalmente da construção com o uso de pronomes, nestes casos deve-se ficar atento e balancear as Intents que possuam essa particularidade.
> * Pensar em como o usuário perguntaria sobre aquele tema;
> * Tente ao máximo não repetir pronomes ou formas de perguntar nos exemplos da Intent;

relembrando destes tópicos também!
