### ISSUE TITLE
Evolução de cumprimento da Aix

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#223]
Tratar conteúdos gerais que podem vir a ser tratados pelo bot.

**Tarefas**

- [x] Refatorar utter de cumprimento afim de especificar as funcionallidades do bot de uma maneira melhor.
- [x] Avaliar uma melhor maneira de implementar essa melhora por meio da uuter de fallback
- [x] Avaliar implementação de comandos

**Critérios de aceitação**

- [x] Bot cumprimentando usuário de forma a tornar o diálogo intuitivo para o usuário de todas as funcionalidades dispostas no bot.

**Comment by Andreabenf** [comment]
Vou começar a trabalhar nessa issue baseado no feedback que tivemos hoje após a R1

**Comment by Andreabenf** [comment]
Como a maior crítica foi o usuário não saber o que fazer de primeira, irei me concentrar em deixar o cumprimento da Aix após o "oi" inicial bem completo e demonstrativo

**Comment by Andreabenf** [comment]
Além de mudar o cumprimento, deixando mais intuitivo o "proximo passo" a ser tomado pelo usuário, eu criei o /help para sanar qualquer dúvida restante do usuário
