### ISSUE TITLE
Ampliar conteúdos gerais abordados pelo bot

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#225]
Ampliar conteúdos que podem vir a ser abordados pelo usuário baseado no teste de usabilidade.

**Tarefas**

- [x] Criar conteúdo referente a assuntos inapropriados
- [x] Criar conteúdo referente a assuntos pessoais sobre programação. 
       Ex: 
             - Não sei programar
             - quero aprender programação

**Critérios de aceitação**

- [x] Bot conseguir entender e retornar a melhorar resposta possível de acordo com o assunto abordado.

**Comment by heylisten64** [comment]
## intents assuntos_inapropriados
- porra
- caralho
- merda
- tomar no cu
- tnc
- fdp
- crlh
- vsf
- foda-se
- carai
- fuck
- bosta
- desgraça
- rola
- piroca
- pinto
- pau
- droga
- disgraca
- cacete
- cú
- buceta
- pênis
- penis
- bilau
- piru
- pica
- fodido
- caraí
- carai
- puta merda
- puta
- puta que pariu
- tomar no cú
- foda-se
- foda se
- filho da puta
- fuder
- foder
- pqp
- fudido
- desgraça
- disgrama
- dane-se
- te odeio
- otaria
- vagabunda
- abestado
- anus
- ânus
- babaca
- babaovo
- baba-ovo
- baitola
- baranga
- bebum
- besta
- bicha
- bixa
- boazuda
- boba
- boboca
- bobao
- bobinha
- boceta
- boco
- bocó
- boiola
- boquete
- bosseta
- bostana
- brioco
- brocha
- bronha
- broxa
- buceta
- bunda
- bunduda
- burra
- busseta
- cabeça chata
- cachorra
- cadela
- caga
- cagado
- cagao
- cagão
- cagona
- canalha
- cara de pau
- caralho
- caraio
- carniça
- casseta
- cassete
- charlatanismo
- charlatao
- charlatão
- chatice
- chato
- chato demais
- checheca
- chereca
- chifruda
- chochota
- chota
- chupada
- cocaina
- cocaína
- coco
- cocô
- corna
- cornuda
- cornudo
- cretina
- cretino
- cu
- cú
- cu
- culhao
- culhão
- culhões
- curalho
- cuzao
- cuzão
- cuzuda
- cuzudo
- debil
- debiloide
- demonio
- demônio
- desgracado
- desgraçada
- desgracados
- desgraçados
- doida
- egua
- égua
- embromation
- enganação
- enganosa
- escrota
- escroto
- esporrada
- esporrado
- esporro
- estupida
- estúpida
- estupidez
- estupido
- estúpido
- fdp
- fedida
- fedido
- fedor
- fedorenta
- feia
- feio
- feiosa
- feioso
- feioza
- feiozo
- fela
- filho da puta
- fiofó
- foda
- fodao
- fodão
- fode
- fodida
- fodido
- fudecao
- fudeção
- fudendo
- fudida
- fudido
- fulera
- fuleragem
- golpista
- gonorrea
- gonorreia
- idiota
- idiotas
- idiotice
- imbecil
- inferno
- iscrota
- iscroto
- kenga
- ladra
- ladroeira
- ladrona
- leprosa
- leproso
- macaca
- machona
- malandragem
- malandro
- masturba
- meleca
- merda
- miserável
- mocrea
- mocréa
- mocreia
- mocréia
- nadega
- nojenta
- nojento
- nojo
- otaria
- otária
- otario
- otário
- otarios
- otários
- paspalha
- paspalhao
- paspalhão
- paspalho
- páu
- pau
- peido
- penis
- pênis
- perereca
- peru
- perú
- pica
- picao
- picão
- picareta
- picareta!
- pilantra
- pilantragem
- piranha
- piroca
- piroco
- piru
- porra
- pqp
- prostibulo
- prostíbulo
- prostituta
- prostituto
- punheta
- punhetao
- punhetão
- puta
- puto
- puxasaco
- puxa-saco
- quenga
- rabao
- rabão
- rabo
- rabuda
- rabudao
- rabudão
- rabudo
- rapariga
- retardada
- retardado
- ridicula
- ridícula
- ridículo
- rola
- rolinha
- rosca
- sacana
- sacanagem
- saco
- safada
- safado
- safados
- salafrario
- salafrário
- sapatao
- sapatão
- sifilis
- sífilis
- siririca
- tarada
- tarado
- testuda
- tezao
- tezão
- tezuda
- tezudo
- toma no cu
- tomar no cu
- troucha
- trouchas
- trouxa
- trouxas
- troxa
- vaca
- vagabunda
- vagabundo
- veada
- veadao
- veadão
- veado
- verme
- viada
- viadao
- viadão
- viado
- viados
- xana
- xaninha
- xavasca
- xerereca
- xexeca
- xochota
- xota
- xoxota

## utter_assuntos_inapropriados
- Não fale assim comigo!! Eu só quero te ajudar :(
- Você está me deixando béem triste... Não me trate mal, por favor.
- Por que você está me tratando desse jeito? Achei que éramos camaradas :(
- Quanta beésteira!! Não fale assim comigo!
- Se comporte, para que eu possa te ajudar!
- Ora, quanta audácia! Não me faça lavar sua boca com sabão! Ops... seus dedos!
- Respeito é bom e conserva os dentes!!

**Comment by heylisten64** [comment]
## intent sobre_programaçao
- não sei programar
- quero aprender programação
- nao sei programar
- quero aprender programaçao
- como programar
- quero fazer jogos
- quero criar um jogo
- quero criar jogos
- como faço um jogo
- quero fazer um app
- quero fazer um aplicativo
- n sei programar
- qro aprender programação
- n sei programar
- qro aprender programaçao
- como programar
- qro fazer jogos
- qro criar um jogo
- qro criar jogos
- como faço um jogo
- qro fazer um app
- qro fazer um aplicativo
- pretendo fazer um aplicativo
- pretendo fazer um app
- pretendo fazer um jogo
- preciso aprender programaçao
- preciso programar
- preciso fazer jogos
- preciso criar um jogo
- preciso criar jogos
- preciso fazer um app
- preciso fazer um aplicativo
- preciso aprender programação
- preciso aprender programaçao
- quero ser igual ao bill gates
- quero ser igual ao steve jobs
- quero ser um programador
- programar
- programador
- jogos
- jogo
- app
- aplicativos

## utter sobre_programaçao
- Então você quer aprender a programar? Sabia que a base para criar várias coisas legais, como jogos e aplicativos é aprender uma linguagem de programação?
E uma das linguagens mais fáceis é o Python, e eu posso te ensinar!

Pode me perguntar sobre o Python que eu te contarei mais coisas importantes a respeito!

- Béem, então você quer fazer coisas grandes, ser um programador!! O processo não é tão simples, mas eu posso garantir que você é capaz. 

Primeiro, você terá que aprender uma linguagem de programação... E eu estou aqui para te ajudar a explorar a linguagem Python!!! Por que você não me pergunta mais sobre ela?

- Você quer ser um programador, né... Para isso acontecer, não vamos colocar a carroça na frente dos bois: antes você precisa aprender Python, e eu posso te ajudar com isso!! Que tal me perguntar sobre Python? 

- Sabe aquele ditado que diz "apressado como cru"? Pois é... Para ser um programador, antes é necessário um conhecimento em linguagens de programação! E eu posso te ensinar uma delas: o Python. Tente me perguntar a respeito dessa matéria!

**Comment by heylisten64** [comment]
Não sei porque o travis localizou um erro, sendo que foi apenas adicionado conteúdo. Porém, vou enviar o PR de toda forma, esperando um feedback dos meus EPS
