### ISSUE TITLE
Construir hello world

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#226]
Auxiliar o usuário na construção do seu primeiro programa hello world na linguagem python.

**Tarefas**

- [x] Criar conteúdo referente a auxiliar o usuário na construção do primeiro programa hello world
- [x] Fazer isso por meio da criação de intents para cada ação do bot 
      Ex: 
            - intent para importar bibliotecas
            - intent para criar main
            - intent para printar linha 
            ....
       
**Critérios de aceitação**

- [x] Bot capaz de guiar usuário na criação do primeiro hello world
- [x] bot capaz de responder usuário fora do contexto de criação do hello world porem em um contexto externo caso tenha duvida sobre como printar uma linha em python por exemplo.

**Comment by pedroeagle** [comment]
vou adicionar essa imagem após ensinar fazer o hello world
![hello_world](https://user-images.githubusercontent.com/45996980/57019461-fd78e500-6bfc-11e9-8ea8-717ff4e61c34.png)

**Comment by pedroeagle** [comment]
eu gostaria de testar se a imagem está sendo enviada como deveria mas o jupyter-notebook não está funcionando no server local :/
