### ISSUE TITLE
Adicionar tópico com a definição do que são arquivos

### ISSUE THREAD

**Issue by Lucas362** [fga-eps-mds/2019.1-Grupo-1#228]
Adicionar conteúdo referente ao tópico definição do que são arquivos

**Tarefas**

- [x] Criar conteúdo referente a ação de explicar sobre arquivos
- [x] Inserir conteúdo referente a ação de explicar sobre arquivos. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by Andreabenf** [comment]
Galera, vou criar uma branch chamada issue_228_sobre_arquivos que será a main branch sobre arquivos.
aqui iremos resolver todas as issues #228 #229 #230 #231

**Comment by gustable42** [comment]
Estou criando o conteúdo das utters até agora está assim:

Arquivos são recursos para que informações e valores possam ser armazenados de forma permanente.
São usados para gravar informações que não podem ser perdidas quando a execução do programa terminar!
Quer um exemplo para entender melhor? Peça um 'exemplo de arquivos'; 

Está muito superficial?

**Comment by gustable42** [comment]
Reformulei a utter para ser mais didática

O arquivo é como um livro. Para usá-lo, você tem que abrí-lo. Depois de usar, você o fecha. Com ele aberto, você pode ler ou escrever nele. Todo livro tem um nome único, assim como os arquivos! Para abrir um arquivo, você especifica o nome e indica se você quer ler ou escrever nele.

Quer um exemplo para entender melhor? Peça um 'exemplo de arquivos'.
