### ISSUE TITLE
Adicionar tópico com exemplos de utilização de arquivos

### ISSUE THREAD

**Issue by Lucas362** [fga-eps-mds/2019.1-Grupo-1#229]
Adicionar conteúdo referente ao tópico com exemplos de utilização de arquivos 

**Tarefas**

- [x] Criar conteúdo referente a ação de apresentar exemplos de utilização de arquivos na linguagem python.
- [x] Inserir conteúdo referente a ação de apresentar exemplos de arquivos. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by gustable42** [comment]
Estou criando os conteúdo e me veio uma dúvida se devo entrar de forma mais aprofundada ensinando as funções mais comuns em relação a manipulação de arquivos, ou só dou um exemplo mais por alto, como esse:

Seu programa gera o horário que ele foi executado para usar em relatórios.
Caso grave esse valor numa variável, ela se perderá assim q o programa for fechado!
A solução é criar um arquivo de texto, gravar aquele horário e salvá-lo!
