### ISSUE TITLE
Adicionar tópico com linkagem estática para conteúdo extra sobre arquivos

### ISSUE THREAD

**Issue by Lucas362** [fga-eps-mds/2019.1-Grupo-1#230]
Adicionar conteúdo referente ao tópico linkagem estática para conteúdo extra sobre arquivos

**Tarefas**

- [x] Pesquisar link referente a utilização de arquivos na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre a utilização de arquivos.

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by gustable42** [comment]
Então você quer virar o mago dos arquivos, néee!?
Aqui vai alguns links externos com explicações mais aprofundadas sobre o tema!

https://aprendacompy.readthedocs.io/pt/latest/capitulo_11.html
https://panda.ime.usp.br/pensepy/static/pensepy/10-Arquivos/files.html
http://blog.evaldojunior.com.br/aulas/python/2009/02/08/curso-de-python-aula-12.html

Montei a Utter dessa forma, bem simples e com os links listados
