### ISSUE TITLE
Adicionar tópico com linkagem estática para sugestão de exercício sobre uso de arquivos

### ISSUE THREAD

**Issue by Lucas362** [fga-eps-mds/2019.1-Grupo-1#231]
Adicionar conteúdo referente ao tópico linkagem estática para sugestão de exercício sobre uso de arquivos

**Tarefas**

- [x] Pesquisar link referente a sugestão de exercícios referentes ao uso de arquivos na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre sugestão de exercício sobre utilização de arquivos. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by gustable42** [comment]
Ainda não achei exercícios com essa abordagem de manipular arquivos, assim que achar, termino a utter
