### ISSUE TITLE
Adicionar cobertura de testes no projeto.

### ISSUE THREAD

**Issue by GuiMarques98** [fga-eps-mds/2019.1-Grupo-1#234]
Configurar e escrever os testes da Aix.

**Tarefas**

- [x] Configurar o coverage para testar a Aix.
- [x] Escrever os testes para o coverage.

**Critérios de aceitação**
- [x] Rodar os testes do coverage.
- [x] Escrever os testes do coverage até 50%.
- [x] A condição necessária pode ser a nível de comportamento ou resultado

**Comment by KahCosta** [comment]
@GuiMarques98 Como está o andamento da cobertura de testes no projeto?

**Comment by GuiMarques98** [comment]
Já foram feitos alguns testes @KahCosta e só é necessário configurar para aparecer tanto no _coverage_ e no _coverall_.

**Comment by GuiMarques98** [comment]
Estamos utilizando as ferramentas de _unittest_, _coverage_ do Python e foi decidido de criar um pacote a parte para realizar os testes em todo o Bot.

**Comment by GuiMarques98** [comment]
Comandos para cobertura de testes e verificar quanto está sendo ela:

`pytest --cov-config=.coveragerc --cov=bot --cov=actions && coverage report`

**Comment by GuiMarques98** [comment]
Como fazer e executar testes no ambiente.

Antes de tudo é necessário criar um arquivo dentro da pasta `tests/` com o nome de `test_xxxx.py` sendo `xxxx` o nome do arquivo q será testado. Entrando no arquivo são necessárias as seguintes linhas no inicio:

```Python
import logging
import os,sys,inspect

import pytest

currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)

from bot.xxx import yyy # xxx é o arquivo que vc testará e yyy o nome da função ou Classe
```

A ferramenta que estamos utilizando é o [pytest](https://pytest.org/) e um bom tutorial é [esse](https://semaphoreci.com/community/tutorials/testing-python-applications-with-pytest) menos a parte do `Continuous Testing on Semaphore CI`. Exemplo de teste:

```Python
# /tests/test_algo.py
def test_algo():
    x = True
    assert x == True
```


__Editado__: Para rodar basta dar build no bot e depois rodar o comando `docker run aixchatbot/aix-bot pytest --cov-config=.coveragerc --cov=.`

**Comment by pedroeagle** [comment]
pra dar build no bot é necessário esse comando: docker build -q -t aixchatbot/aix-bot -f ./docker/bot.Dockerfile .
