### ISSUE TITLE
Aix não conecta da UnB com o UnB wireless

### ISSUE THREAD

**Issue by GuiMarques98** [fga-eps-mds/2019.1-Grupo-1#244]
**Descreva o bug**
A Aix no Jupyter Notebook na UnB não conecta por estar bloqueado no firewall da Universidade.

**Comportamento esperado**
Conectar ao site https://aixbot.me/chat/livechat.

**Comportamento encontrado**
Firewall bloqueando o site.

![image](https://user-images.githubusercontent.com/23389315/56983745-c9e57e80-6b5a-11e9-9b83-aee5070f987c.png)

**Como reproduzir**
Passos para reproduzir o bug:
1. Estar conectado ao UnB Wireless em algum campus da UnB.
2. Entrar no site https://aixbot.me/chat/livechat
3. Veja o erro

**Comment by Yoshida-Eduardo** [comment]
Inicialmente imaginei que houvesse algum problema relacionado a alguma porta utilizada pelo serviço, então configurei o nginx para utilizar somente a porta padrão(80) para conexões http, mas o problema ainda persistiu.

**Comment by Yoshida-Eduardo** [comment]
Baseado na mensagem de erro aparentemente havia um problema pelo fato do site estar na categoria Not Rated, a qual aparentemente estava bloqueada pelo Fortinet. Realizei o rating do site na plataforma do Fortinet, recebemos a categoria de "Information Technology", entretanto seguimos com o mesmo problema. 
![imagem](https://user-images.githubusercontent.com/37124267/57003637-8ca2e000-6b9e-11e9-9eca-b6e53d167e86.png)
Entrei em contato com o suporte do Fortinet acerca do bloqueio, aparentemente não há nenhum problema com a classificação do website.
![imagem](https://user-images.githubusercontent.com/37124267/57003739-1652ad80-6b9f-11e9-8c61-2716ec2350d1.png)
Com base na mensagem de erro conclui-se que a categoria a qual o website pertence foi bloqueada pelo administrador do webfilter da Wifi da UnB, creio que seja necessário contactar o CPD para tratar o problema.

**Comment by icaropires** [comment]
@Yoshida-Eduardo Tive o mesmo problema com o meu projeto. Também fiz o rating do site no Fortiguard, eles aprovaram e funcionou aqui.

Tentei acessar o site apontado por vocês, agora, daqui da UnB e não foi bloqueado:

![image](https://user-images.githubusercontent.com/18473249/57024432-f1941f80-6c0a-11e9-8c22-e73fcae3f044.png)


Sugiro apagar as informações de cache e cookies do browser de vocês e tentar novamente.

**Comment by Yoshida-Eduardo** [comment]
@icaropires obrigado pela resposta, fico feliz em saber que não vou precisar entrar em contato com o CPD, coisa que nem adiantaria muito kkkkkk. Mas entao, por hora alguns serviços ainda não foram configurados para ssl, vc conseguirá acessar a página normalmente via http.

**Comment by GuiMarques98** [comment]
O site http://aixbot.me está funcionando corretamente entretando as imagens não estão sendo carregadas corretamente na janela do bot no jupyter portanto a _issue_ não será fechada.
