### ISSUE TITLE
Refatorar Fluxo de forma a manter usuário na conversa

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#260]
Refatorar as utters do bot afim de manter o usuário na conversa de forma que o usuário percorra um caminho de aprendizado, porém tenha a opção de pular de um conteúdo para o outro sem ter que passar por todas as etapas do conteúdo (exercicios..conteúdo extra) e que todas essas transições estejam intuitivas para o usuário.

**Tarefas**

- [x] Guiar usuário para acessar o conteúdo do bot
- [x] Guiar usuário para acessar os sub tópicos de conteúdo do bot

**Critérios de aceitação**

- [x] Usuário conseguir seguir um fluxo induzido pelas interações com o bot sem se perder nas funcionalidades dispostas no bot

**Comment by pedroeagle** [comment]
será mapeado no conteúdo de exercícios e exemplo.
o que é Python -> conteúdo variáveis
conteúdo sobre variáveis -> hello world
conteúdo sobre variáveis especifico -> hello world
hello world -> condicionais
condicionais -> vetor
vetor -> matrizes
matrizes -> repetição
repetição -> função
função -> arquivos
arquivos -> importar bibliotecas

**Comment by pedroeagle** [comment]
Resolvemos essa issue em conjunto por meio de uma call. Cada commit foi feito em conjunto embora em pcs diferentes.
