### ISSUE TITLE
Refatorar fluxo de forma a induzir melhor a escrita do usuário a cada interação

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#261]
Refatorar as utters de forma a induzir melhor o usuário a como requisitar algo ao bot.

**Tarefas**

- [x] Refatorar utter de forma a exemplificar melhor a forma como o usuário deve requisitar uma ação ao bot.

**Critérios de aceitação**

- [x] Bot conseguir induzir da foma correta de escrita do usuário durante a interação

**Comment by pedroeagle** [comment]
ontem realizei a refatoração até a linha 407 do arquivo de domain.

**Comment by pedroeagle** [comment]
refatorei as linhas que faltavam na domain. seria interessante se lessem todas as frases pra ver se não esqueci de alguma coisa ou digitei algo errado etc..

**Comment by pedroeagle** [comment]
por sugestão do @iurisevero adicionei comentários que dividem os conteúdos inseridos por tipos, deixando assim mais organizados.
os comentários são assim: 
"# ============================ NAVEGAÇÃO PRINCIPAL ============================ #"
"# ============================ SOBRE ============================ #"
"# ============================ CONTEÚDO EXTRA ============================ #"
