### ISSUE TITLE
Trabalhar no slot do stackoverflow

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#262]
Estudar e aplicar melhorias quanto a utilização do slot presente na ação de pesquisa da integração com a ferramenta stackoverflow.

**Tarefas**

- [x] Estudar melhores formas de se trabalhar com slots 
- [x] Aplicar melhoria quanto a utilização do slot em nossa funcionalidade de pesquisa na plataforma stackoverflow.

**Critérios de aceitação**

- [x] Bot capaz de identificar assunto a ser pesquisado na plataforma sem ter que induzir a maneira correta de se perguntar ao usuário

**Comment by KahCosta** [comment]
@arthurTemporim estudou a viabilidade da aplicação de uma meneira de resolver isso ainda com o uso de slots!

**Comment by iurisevero** [comment]
Fiz diversos teste nos slots, seguindo o padrão de que o bot tem maior eficiência captando palavras inicializadas com letra maiúscula. Fiz um "relatório" sobre, provavelmente ficara documentado na parte de estudos.

**Comment by heylisten64** [comment]
Adicionei parte do estudo de slots, que poderá ser incrementado posteriormente, conforme os avanços dos desenvolvedores da equipe!!
