### ISSUE TITLE
Estudar ferramenta Kibana e ElasticSearch 

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#265]
Estudar o funcionamento das ferramentas para análise de dados Kibana e ElasticSearch para refinar melhor os dados recebidos pelo bot.

**Tarefas**

- [x] Estudar funcionamento das ferramentas Kibana e ElasticSearch 
- [x] Identificar dados relevantes a serem levantados para melhoria de conversação do bot.
- [x] Documentar estudo e dados identificados para relevantes para análise e aplicação de melhorias 

**Critérios de aceitação**

- [x] Documento criado e postado na Pages da AIx

**Comment by iurisevero** [comment]
Tava dando umas pesquisada e vi que o próprio site da Elastic tem uns links de introdução as ferramentas.
[Elastic Search](https://www.elastic.co/pt/webinars/getting-started-elasticsearch?elektra=home&amp;storm=banner)
[Kibana](https://www.elastic.co/pt/webinars/getting-started-kibana?baymax=rtp&elektra=products&storm=kibana&iesrc=ctr)

**Comment by heylisten64** [comment]
Dei uma olhada no conteúdo inserido, e acho que está ótimo!
