### ISSUE TITLE
Estudo de tecnologia (Boilerplate) 

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#28]
Estudar estrutura do boilerplate para aplicação na Aix

**Tarefas**

- [x] Estudar estrutura de arquivos de inserção e configuração de conteúdo
- [x] Entender o funcionamento do Rasa por meio do que foi aplicado no Boilerplate

**Critérios de aceitação**
- [x] Descrever conhecimentos mínimos adquiridos a partir do estudo do reposítório afim de minimizar problemas futuros quanto ao funcionamento do bot.
- [x] Documentar aprendizado no Github Pages

**Comment by KahCosta** [comment]
Link para acesso ao repositório do [Boilerplate](https://github.com/lappis-unb/rasa-ptbr-boilerplate)

**Comment by iurisevero** [comment]
Galera, tive um erro no docker-compose do Rasa, acredito que por um erro meu na hora de instalar o docker, recebia a mensagem:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)

O @Andreabenf me passou os links:
https://www.digitalocean.com/community/tutorials/como-instalar-e-usar-o-docker-no-ubuntu-16-04-pt
https://docs.docker.com/compose/install/
que forneceram a resolução para o problema

**Comment by Lucas362** [comment]
@iurisevero muito obrigado por compartilhar, provavelmente será muito útil para alguém futuramente
