### ISSUE TITLE
Instalação Python

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#282]
Guiar e tirar dúvidas do usuário quanto a existência de um ambiente de desenvolvimento python.

**Tarefas**

- [x] Questionar usuário quanto a existência de um ambiente de desenvolvimento configurado
- [x] Indicar dependências do ambiente de desenvolvimento
- [x] Coletar dados sobre o ambiente de desenvolvimento do usuário ( saber se a máquina que o usuário opera é de 32 ou 64 afim de conseguir indicar os comandos corretos)
- [x] Guiar usuário na instalação das dependências python

**Critérios de aceitação**

- [x] Bot capaz de guiar usuário na instalação de um ambiente de desenvolvimento

**Comment by heylisten64** [comment]
A ideia que a @KahCosta tinha dado era de criar uma intent pra afirmaçao... porém, não sei como funcionaria, já que a utter seria bem específica.... não bastasse esse problema, acredito que uma intent dessa iria trazer mais trabalho de refatorar outras intents também, que traria varias semelhanças com as intents do manter conversa. por isso pensei em fazer bem simplificado tipo: Agora vamos instalar python! mas antes verifique se vc tem do jeito x... caso não faça: y

**Comment by Lucas362** [comment]
> A ideia que a @KahCosta tinha dado era de criar uma intent pra afirmaçao... porém, não sei como funcionaria, já que a utter seria bem específica.... não bastasse esse problema, acredito que uma intent dessa iria trazer mais trabalho de refatorar outras intents também, que traria varias semelhanças com as intents do manter conversa. por isso pensei em fazer bem simplificado tipo: Agora vamos instalar python! mas antes verifique se vc tem do jeito x... caso não faça: y

Considero esta uma saída válida e digna de teste, vão em frente :wink:

**Comment by heylisten64** [comment]
# Template

Instalar o Python no sistema Linux é beém fácil! Antes, cheque se você já tem Python instalado com o seguinte comando no terminal: 

`python -V `

É importante que você tenha a versão atualizada, o Python3 no caso.
Caso você ainda não tenha o python já instalado, digite no prompt: 

`sudo apt-get install python3.6`

Para a instalação do Visual STudio, o ambiente de desenvolvimento, digite no prompt: 

`uname -m`

para verificar se você deve usar o comando para 32 bits:

`wget "https://go.microsoft.com/fwlink/?LinkID=760681" -O vscode.rpm`

ou de 64 bits:

`wget "https://go.microsoft.com/fwlink/?LinkID=760867" -O vscode.rpm`

**Comment by heylisten64** [comment]
A demora foi devido a semana conturbada, com muitas provas e a competição na tarde de sábado. :(
Mas ainda assim, foi entregue a tempo da sprint!
Aguardo o feedback da equipe de eps!
