### ISSUE TITLE
Teste no arquivo fallback

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#283]
Aplicar teste unitário no arquivo de fallback

**Tarefas**

- [x] Testar funções do arquivo de fallback

**Critérios de aceitação**

- [x] Funções do arquivo de fallback testadas com no mínimo 90% de cobertura de teste.

**Comment by heylisten64** [comment]
O Gui colocou um material pra testes nas branches bem [aqui](https://github.com/fga-eps-mds/2019.1-Aix/issues/234), vale a pena dar uma olhada...
