### ISSUE TITLE
Teste no arquivo validator

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#284]
Aplicar teste unitário no arquivo validator

**Tarefas**

- [x] Testar funções do arquivo validator

**Critérios de aceitação**

- [x] Funções do arquivo de validator testadas com no mínimo 90% de cobertura de teste.

**Comment by pedroeagle** [comment]
consegui fazer o arquivo de teste do validator.py porém está com uma taxa de erros igual a 1/16. pra mim que essa taxa deveria ser 0 visto que não há tantas funções assim. existe alguma possibilidade de descobrir em qual caso está dando erro?
