### ISSUE TITLE
Teste no arquivo Connector

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#285]
Aplicar teste unitário no arquivo connector

**Tarefas**

- [x] Testar funções do arquivo connector

**Critérios de aceitação**

- [x] Funções do arquivo connector testadas com no mínimo 90% de cobertura de teste.

**Comment by Lucas362** [comment]
Como dito na issue #286,  foi decidido que de primeiro ordem, a implementação deste teste será cancelada.
