### ISSUE TITLE
Teste no arquivo run-rocketchat

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#286]
Aplicar teste unitário no arquivo run-rocketchat

**Tarefas**

- [x] Testar funções do arquivo de run-rocketchat

**Critérios de aceitação**

- [x] Funções do arquivo de run-rocketchat testadas com no mínimo 90% de cobertura de teste.

**Comment by heylisten64** [comment]
O Gui colocou um material pra testes nas branches bem [aqui](https://github.com/fga-eps-mds/2019.1-Aix/issues/234), vale a pena dar uma olhada...

**Comment by Andreabenf** [comment]
Gabi, dei uma olhada no tutorial do guilherme e já criei o arquivo fonte para nossos testes na branch issue_286_teste_run-rocketchat.
Hoje mais tarde a gente começa a trabalhar juntos

**Comment by heylisten64** [comment]
durante a aula, o conselho que a professora deu foi priorizar os testes do chatbot mesmo, e não do rasa, ja que nos falta mt bagagem a respeito do código do boilerplate... achamos melhor congelar essa issue, organizando nossas prioridades, que seria a geraçao da matriz de erros do chatbot e, se possivel, tentar absorver mais informaçoes do codigo em questao, o qual tivemos muitos empecilhos para entender para conseguir gerar os testes

**Comment by Lucas362** [comment]
Baseado no feedback descrito no comentário acima, foi decidido que de primeiro ordem, a implementação deste teste será cancelada.
