### ISSUE TITLE
Refatoração para aumento da manutenabilidade do código

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#288]
Aumentar qualidade de código de acordo com métricas definidas no documento GQM e documento de qualidade.

**Tarefas**

- [x] duplicação
- [x] quantidade de linhas por classe
- [x] tamanho das linhas
- [x] quantidade de método por classe

**Critérios de aceitação**

- [x] Aumento de manutenabilidade de código

**Comment by Andreabenf** [comment]
Gustavo, ja pode ir lendo o [Documento de qualidade](https://fga-eps-mds.github.io/2019.1-Aix/gerencia/2019/04/26/documento-de-qualidade/) e o [GQM](https://fga-eps-mds.github.io/2019.1-Aix/gerencia/2019/04/19/gqm/) para podermos refatorar tudo certinho
