### ISSUE TITLE
Estudo e definição de compilação de código do bot

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#289]
Estudar e definir como será implementado a funcionalidade de compilação do bot
**Tarefas**

- [x] Definir escopo (O que o bot será capaz de fazer e como)
- [x] Definir Arquitetura/Devops
- [x] Definir entradas e saídas

**Critérios de aceitação**

- [x] Escopo e tarefas seguintes da funcionalidade definidas.

**Comment by GuiMarques98** [comment]
Existem alguns pluggins para compilar código _client-side_ para não sobrecarregar o servidor como o [Skulpt](http://www.skulpt.org/). Então seria necessário um front end com interação com o iframe do RocketChat.

**Comment by Lucas362** [comment]
> Existem alguns pluggins para compilar código _client-side_ para não sobrecarregar o servidor como o [Skulpt](http://www.skulpt.org/). Então seria necessário um front end com interação com o iframe do RocketChat.

Então a ideia nesse caso seria criar um ambiente online q compile código (de forma client-side, diferente do jupyter q executa no servidor) e integrar o bot lá?

**Comment by GuiMarques98** [comment]
> > Existem alguns pluggins para compilar código _client-side_ para não sobrecarregar o servidor como o [Skulpt](http://www.skulpt.org/). Então seria necessário um front end com interação com o iframe do RocketChat.
> 
> Então a ideia nesse caso seria criar um ambiente online q compile código (de forma client-side, diferente do jupyter q executa no servidor) e integrar o bot lá?

Exatamente, como esse ambiente é um ambiente com JavaScript seria facil evoluir e até mesmo pegar os erros de código do usuário.

**Comment by Lucas362** [comment]
> Exatamente, como esse ambiente é um ambiente com JavaScript seria facil evoluir e até mesmo pegar os erros de código do usuário.

É uma saída interessante, até o momento é a melhor opção apresentada. Recomendo uma reunião presencial para definição arquitetural dessa solução. Estou dando esta discussão como encerrada neste ponto, e a próxima reunião seria para amadurecimento da ideia!
