### ISSUE TITLE
Aplicação do teste de usabilidade

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#290]
Aplicar teste de usabilidade na versão 1.0 da Aix com a participação de 5 a 7 pessoas.

**Tarefas**

- [x] Requisitar pessoas para participação do teste de usabilidade
- [x] Definição do dia/horário da aplicação do teste de usabilidade
- [x] aplicação do teste de usabilidade baseado no planejamento 
- [x] Usuários realizando tarefas pré-determinadas no planejamento
- [x] Levantamento de melhorias a serem aplicadas no bot

**Critérios de aceitação**

- [x] Cada usuário participante do teste de usabilidade deve ser acompanhado de ao menos 1 integrante da Equipe Aix
- [x] Os integrantes da Equipe Aix deve ir anotando observações feitos no decorrer do teste
- [x] Ao finaldo teste deve ser elaborado um documento com todas as observações e melhorias a serem aplicadas no bot

**Comment by KahCosta** [comment]
Link para acesso ao roteiro da aplicação do teste de usabilidade [Aqui](https://docs.google.com/document/d/114q1EO93Ha5fhBI4aD5uwLEpsGbsJjuZmxptcukz3fU/edit)

**Comment by Lucas362** [comment]
Documento relatando o teste de usabilidade pode ser encontrado em nossa documentação de produto em nosso github pages
