### ISSUE TITLE
Teste do uso de Slots para Intents

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2019.1-Grupo-1#291]
Atualizar o bot para que ele use os Slots para detectar qual conteúdo o usuário deseja saber sobre ao invés de diversas intents repetidas para cada conteúdo abordado pelo mesmo.

**Tarefas**

- [x] Atualizar as intents para habilitar o uso de slots
- [x] Modificar stories para novo formato
- [x] Fazer teste para verificar o funcionamento

**Critérios de aceitação**

- [x] Matriz de confusão da Aix estar melhor do que no modelo anterior

**Observações**
- A branch dessa issue ficará aberta para testes futuros.

**Comment by iurisevero** [comment]
Após fazer diversos testes com o uso de Slots para substituir as intents relatei que eles não resolveriam no são problema, apenas substituiriam por outro, visto que, para que eles funcionem, é necessário que o usuário escreva o conteúdo de forma capitalizada, ou seja, com a primeira letra de cada palavras em maiúsculo.
No entanto, pensei em uma outra solução possível. Para determinar qual o tipo do conteúdo do slot seria necessário fazer uma análise do texto captado e direcionar a utter correta, isso poderia ser feito por if-elses em uma custom action. Expandindo essa ideia, podemos verificar a possibilidade de implementar isso para frase inteira ao invés de apenas para o slot, tendo o mesmo resultado, e, para melhorar, poderíamos passar o conteúdo definido para um slot e, a partir dele, melhorar o fluxo de conversa para os casos em que o usuário não especifique o conteúdo.
Uma possível falha nessa aplicação seria o usuário digitar o conteúdo errado e receber como resposta uma utter não esperada.

**Comment by Lucas362** [comment]
Opa, fico feliz por não ter q substituir as intents kk.
Acho bastante válida a sua ideia, e no mínimo merece ser testada. Vai fundo mano.
Mas o seguinte trecho me preocupou um pouco:
```
Uma possível falha nessa aplicação seria o usuário digitar o conteúdo errado e receber como resposta uma utter não esperada.
```
Isso é em relação à implementação q idealizou ou é em relação ao q já temos?

**Comment by iurisevero** [comment]
Na verdade, as intents continuam sendo substituidas kkkk
E quanto a falha, ela seria após a implementação, porém, na aplicação atual, se o usuário não especificar o conteúdo, ou escrever errado, as respostas do bot são Fallback ou algo errado

**Comment by Lucas362** [comment]
```
Na verdade, as intents continuam sendo substituidas kkkk
```
Oh não kkkk.

Acho q vale a pena tentar, msm com o possível erro.

**Comment by iurisevero** [comment]
Terminei de ajustar a custom action para determinar as intents e estava ajustando as palavras chave para cada conteúdo, porém durante essa ação percebi a inviabilidade dessa ideia. O que estava sendo implementado substituía, falando d modo geral, a função do NLU no bot, já que estávamos realizando essa interpretação de forma manual e, devido a isso, mais passível ao erro.
Deste modo, gostaria de saber se posso fechar a issue e definir essa pesquisa com resultado falho. @Lucas362 

Obs: As ideias experimentadas nessa Issue podem ser utilizadas futuramente em outros problemas, porém, como já temos um documento de estudo a respeito de Slots, não há o que se documentar a partir deles.

**Comment by Lucas362** [comment]
> Terminei de ajustar a custom action para determinar as intents e estava ajustando as palavras chave para cada conteúdo, porém durante essa ação percebi a inviabilidade dessa ideia. O que estava sendo implementado substituía, falando d modo geral, a função do NLU no bot, já que estávamos realizando essa interpretação de forma manual e, devido a isso, mais passível ao erro.
> Deste modo, gostaria de saber se posso fechar a issue e definir essa pesquisa com resultado falho. @Lucas362
> 
> Obs: As ideias experimentadas nessa Issue podem ser utilizadas futuramente em outros problemas, porém, como já temos um documento de estudo a respeito de Slots, não há o que se documentar a partir deles.

@iurisevero vlw pelo esforço, por sorte não foi em vão pois o conhecimento adquirido provavelmente será útil mais adiante.
