### ISSUE TITLE
Teste da Custom Action de Pesquisa do StackOverflow

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2019.1-Grupo-1#299]
Aplicar teste unitário na classe ActionPesquisaStackoverflow, do arquivo de actions.

**Tarefas**

- [ ] Testar funções da classe de pesquisa

**Critérios de aceitação**

- [ ] Funções da classe ActionPesquisaStackoverflow testadas com no mínimo 90% de cobertura de teste.

**Comment by iurisevero** [comment]
Os testes foram implementados a partir do tutorial recomendado pelo @GuiMarques98 , que pode ser visto [aqui](https://semaphoreci.com/community/tutorials/testing-python-applications-with-pytest), e tiveram um cobertura de 70% devido ao fato de que uma das funções da classe de pesquisa não possui retorno e tem como ação apenas o tracker e o dispatcher do [Rasa](http://github.com/rasaHQ/), deixando o teste inviável.
Das 4 funções, 3 foram testadas e aprovadas nos testes unitários, concluindo o objetivo da issue.

O resultado do teste pode ser visto abaixo.

```
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.4.1, py-1.8.0, pluggy-0.11.0
rootdir: /home/iuri/Área de Trabalho/Faculdade/semestre_4/MDS/2019.1-Aix
plugins: cov-2.7.1
collected 6 items                                                              

tests/test_action_pesquisa_stackoverflow.py ....                         [ 66%]
tests/test_fallback.py ..                                                [100%]

=============================== warnings summary ===============================
/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_inspect.py:75
/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_inspect.py:75
  /usr/local/lib/python3.6/dist-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
    return _inspect.getargspec(target)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
----------- coverage: platform linux, python 3.6.7-final-0 -----------
Name                 Stmts   Miss Branch BrPart  Cover
------------------------------------------------------
actions/actions.py      43     11     10      1    70%

===================== 6 passed, 2 warnings in 6.38 seconds =====================
```

**Comment by Lucas362** [comment]
Levando em consideração o q foi dito, a parcela de cobertura está aceitável.
