### ISSUE TITLE
Atualização do documento de qualidade de acordo com testes aplicados

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#310]
Atualizar documento de qualidade de acordo com os testes unitários realizados na sprint passada.

**Tarefas**

- [x] Atualizar documentação
- [x] Especificar documentos e arquivos no qual foram aplicados os testes unitários
- [x] Atualizar imagens referentes aos testes de usabilidade aplicados na sprint passada.
- [x] Documentar sobre manutenabilidade no documento de qualidade

**Critérios de aceitação**

- [x] Documento de qualidade revisado
- [x] Documento de qualidade atualizado

**Comment by KahCosta** [comment]
@Lucas362 precisamos definir quais os testes adicionar no nosso documento de qualidade

**Comment by KahCosta** [comment]
Precisamos especificar os testes de unitários e os testes estáticos que realizamos

**Comment by KahCosta** [comment]
No caso seria especificar a cobertura de teste e os arquivos no qual foi realizado o teste de unitário e estático neh?

**Comment by Lucas362** [comment]
Isso, acredito q podemos colocar a coleta como uma tabela com o q foi testado e o quanto foi coberto dele, q tal?
