### ISSUE TITLE
Comunicação com parte gerenciadora da API do URI para análise de viabilidade técnica de integração

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#312]
Comunicação com parte gerenciadora da API do URI para análise de viabilidade técnica de integração.

**Tarefas**

- [x] Enviar Email para saber sobre permissão e receber autorização de utilização da API

**Critérios de aceitação**

- [x] Documentar na issue a resposta obtida

**Comment by GuiMarques98** [comment]
Entramos em contato com o [URI](https://www.urionlinejudge.com.br/) pelo link de [contato](https://www.urionlinejudge.com.br/judge/pt/contact) e estamos aguardando a resposta.

Segue o e-mail:
![image](https://user-images.githubusercontent.com/23389315/58328898-a801b380-7e09-11e9-8b0d-e27286d012b4.png)

**Comment by Lucas362** [comment]
Bom trabalho! Issue concluída
