### ISSUE TITLE
Integração Aix com UVA online judge para envio de feedback

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#316]
Realizar integração do UVA com o bot afim de possibilitar o envio do feedback do exercício proposto e submetido pelo bot

**Tarefas**

- [x] Documentar estudo realizado da API com relação a implementação de feedback para o usuário.
- [x] Integrar API de forma que o usuário consiga receber o feedback do exercício submetido

**Critérios de aceitação**

- [x] Usuário receber feedback do exercício quanto ao que foi submetido
- [x] Estudo da API utilizada documentado para facilitação da compreensão de todo o time.

**Comment by iurisevero** [comment]
Durante o estudo da API do uHunt foi percebido que a integração não será tão difícil quanto esperado, o que levou a redução do estimate da issue. Deve ser levado em consideração a criação da issue #326
