### ISSUE TITLE
Integração Aix com UVA online judge para submissão de exercício

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#317]
Realizar integração do UVA com o bot afim de possibilitar a submissão de exercício.

**Tarefas**

- [x] Estudar viabilidade de aplicação de API do UVA
- [x] Documentar estudo realizado da API
- [x] Integrar API de forma que o usuário consiga submeter um exercício por meio do bot

**Critérios de aceitação**

- [x] Usuário conseguir submeter um exercício sugerido pelo próprio bot
- [x] Estudo da API utilizada documentado para facilitação da compreensão de todo o time.

**Comment by iurisevero** [comment]
Aqui estão alguns links interessantes para olharmos que irão auxiliar no desenvolvimento dessa issue:
[API do uHunt](https://uhunt.onlinejudge.org/api)
[UVACommandLine](https://github.com/scvalencia/UVACommandLine)

**Comment by iurisevero** [comment]
Durante o estudo da API do uHunt foi percebido que a integração não será tão difícil quanto esperado, o que levou a redução do estimate da issue. Deve ser levado em consideração a criação da issue #326
