### ISSUE TITLE
Realizar a construção estática de envio de exercício do UVA online judge

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#318]
Realizar a construção estática de envio de exercícios no formato de PDF do UVA no bot

**Tarefas**

- [x] Selecionar os exercícios para cada conteúdo que o bot é capaz de dialogar no UVA
- [x] Selecionar níveis diferentes para cada conteúdo presente no bot (Estruturas de Repetição: Nível 1, Nível 2...)
- [x] Reestruturar utter de sugestão de exercícios de forma a possibilitar e induzir o usuário a solicitar os exercícios de cada conteúdo de acordo com o nível.(Apresenta os níveis de exercícios existentes e pede para que o usuário selecione o desejado)
- [x] Criar utter para cada envio de arquivo em pdf para cada nível de exercício para determinado conteúdo.

**Critérios de aceitação**

- [x] Usuário ser capaz de selecionar o nível de exercício que deseja solucionar e submeter no bot
- [x] Usuário consiga de forma intuitiva entender que pode escolher o nível de exercício que deseja solucionar
- [x] Usuário receber pdf com o exercício proposto

**Comment by heylisten64** [comment]
Pensei em dividirmos os temas pra acharmos os links, o que acha, @Andreabenf ? Temos os seguintes:
* sobre_variaveis
```
 
 sobre_inteiros
 sobre_pontos_flutuantes
 sobre_caracteres
 sobre_booleanos
 
```
* sobre_condicionais
* sobre_arquivos
* sobre_repeticao
* sobre_funcao
* sobre_vetores
* sobre_matrizes
* sobre_hello_world
* sobre_importar_bibliotecas

**Comment by heylisten64** [comment]
são 9, temas. Posso ficar com 5, os seguintes, para achar exercícios semelhantes: **variáveis**, **condicionais**, **repetição**, **hello word** e **vetores**.

**Comment by heylisten64** [comment]
me habilito a traduzir os problemas que você achar também, e como alguns não são obrigatórios (como a prática de função), podemos colocar uma resolução utilizando o conteúdo para prática. Caso você tenha uma ideia melhor, me avise o quanto antes!

**Comment by Andreabenf** [comment]
Poxa, gabi. Achei ótimo!
Agora que vimos que é possível fazer tudo funcionar, bora começar a fazer!

**Comment by Andreabenf** [comment]
Gabi, tava procurando problemas aqui, e vi que não faz muito sentido procurar um exercicio de Hello World. O que você acha?

**Comment by Andreabenf** [comment]
Olha, acaba que de exercicios possiveis de achar no uva, só consigo pensar nos seguintes conteúdos:

    sobre_variaveis
    sobre_condicionais
    sobre_repeticao
    sobre_vetores
    sobre_matrizes

**Comment by Andreabenf** [comment]
Dei uma olhadas nesse aqui bem faceis. O que você acha?

https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=24&page=show_problem&problem=2827 (vetores e condicionais)

https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=24&page=show_problem&problem=2493 (condicionais)

https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=24&page=show_problem&problem=2113 (Variaveis e condicionais)

https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=24&page=show_problem&problem=514 (vetores)

**Comment by Andreabenf** [comment]
Esse de vetor aqui também é bem facil https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=24&page=show_problem&problem=2899

**Comment by Andreabenf** [comment]
Sem contar que todos de vetores, ja contém repetição dentro né?
Então podemos dividir esses varios de vetores para os de repetição. andre acorda pf

**Comment by heylisten64** [comment]
> Gabi, tava procurando problemas aqui, e vi que não faz muito sentido procurar um exercicio de Hello World. O que você acha?

então, eu pensei que poderia achar um exercício como já vi no URI, mas não sei se tem no UVA que é só de printar resultado sabe? Seria bem simples...

**Comment by heylisten64** [comment]
> Olha, acaba que de exercicios possiveis de achar no uva, só consigo pensar nos seguintes conteúdos:
> 
> ```
> sobre_variaveis
> sobre_condicionais
> sobre_repeticao
> sobre_vetores
> sobre_matrizes
> ```

então, eu acho que de bibliotecas dá pra acrescentar, e de funções. mas como falei no comentário lá em cima que disse, que seria legal a gente colocar alguma resolução junto que utilize função, por exemplo

**Comment by heylisten64** [comment]
> Sem contar que todos de vetores, ja contém repetição dentro né?
> Então podemos dividir esses varios de vetores para os de repetição.

Sim, mas acho que seria mais legal selecionar exercícios mais especificos... pois é possivel utilizar repetição sem vetor, acho que seria o ideal pra introduzir o conteudo de laços. Introduzir dois conteúdos ficaria muito confuso pro usuário

**Comment by heylisten64** [comment]
Outra coisa, observando os exercícios, como o UVA não apresenta exercícios para INICIANTES mesmo, seria válido colocar um arquivo pra dicas de cada questão...

**Comment by heylisten64** [comment]
por exemplo, esses exercícios, que são bem fáceis, e ainda tem um conteudo de iniciante pra preparar o usuário!!

## Hello World

[hello world nível 1](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=817&page=show_problem&problem=3922)
hello world nível 2
hello world nível 3

```
    utter_desafio_hello_world:
    - text : |
      Vamos praticar o que foi ensinado agora, com um desafio! Você pode me mandar sua resposta que te direi se
      está certo ou não! Começaremos com o nível 1:

      NÍVEL 1: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=817&page=show_problem&problem=3922
      
      Já podemos seguir pro próximo conteúdo sugerido, meu pequeno júpiter: Estruturas condicionais. É só perguntar o que são estruturas condicionais que eu te explico.

```

## Laços

[laços nível 1](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=79&page=show_problem&problem=2030`)
[laços nível 2](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=12&page=show_problem&problem=960)
[laços nível 3](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=7&page=show_problem&problem=516)
[conteudo de dica](https://www.youtube.com/watch?v=B3F0IjH5WAM)

```
  utter_desafio_repeticao:
    - text: |
        Então você quer um desafio pra testar todo o conhecimento já visto até então... Certo! Quero ver
        você resolver alguns exercícios um pouco mais complexos, a começar pelo nível 1. Você pode me enviar
        a submissão por aqui mesmo, que te retornarei um feedback! Aqui está o exercício:

        NÍVEL 1: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=79&page=show_problem&problem=2030%60

        Tambéem não se esqueça de continuar sua carreira de desenvolvedor python me perguntando sobre funções!

```

## Funções 

[funções nível 1](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=233&page=show_problem&problem=1862)
[funções nível 2](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=120&page=show_problem&problem=2267)
funções nível 3
resolução utilizando funçao

```
  utter_desafio_funcao:
    - text: |
        Agora vamos testar em problemas mais complexos! Vamos ter problemas de vários níveis...
        Começando pelo nível 1, você pode me mandar seu código para eu te dar um feedback! Vamos tentar?

        NÍVEL 1: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=233&page=show_problem&problem=1862
    
        E oras, agora que você acabou o conteúdo de funções, que tal me perguntar sobre arquivos?

```
## Variáveis
* Pendente
variáveis nível 1
variáveis nível 2
variáveis nível 3

## Condicionais
* Pendente
condicionais nível 1
condicionais nível 2
condicionais nível 3

## Vetores 

[vetores nível 1](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=829&page=show_problem&problem=4459)
[vetores nível 2](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=24&page=show_problem&problem=2899)
[vetores nível 3](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=829&page=show_problem&problem=342)

```
  utter_desafio_vetores:
    - text: |
        Béem vamos dificultar um pouco mais!! Quero ver você conseguir fazer essa questão aqui, lembrando que é
        apenas o nível 1!! Você pode me mandar a submissão que eu te digo se está certo! Lá vamos nós:

        NÍVEL 1: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=829&page=show_problem&problem=4459
        
        Você está evoluindo rápido! Se preferir podemos seguir pro próximo conteúdo sugerido: matrizes. É só perguntar o que são matrizes que te explico.
```
## Matrizes

[matrizes nível 1](https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=2201)
matrizes nível 2
matrizes nível 3

```
  utter_desafio_matrizes:
    - text: |
        Agora que você já fez os exercícios mais fáceis, vou te dar alguns desafios... Vamos começar pelo nível 1!
        Posso receber a sua submissão e te dizer se está certo ou não! Vamos nessa!

        NÍVEL 1: https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=2201

        Se você já entendeu certinho, podemos seguir pro próximo conteúdo sugerido: Arquivos. É só perguntar o que são arquivos que eu te explico.

```
## Bibliotecas
* Pendente quanto a implementação
[bibliotecas nível 1](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=124&page=show_problem&problem=535)
bibliotecas nível 2
bibliotecas nível 3
resolução importando bibliotecas

**Comment by heylisten64** [comment]
Olhei suas questões mas o problema é que temos que ter cuidado pra não abordar outros conteúdos que o usuário não vai ter visto no nosso fluxograma, como laços que é bem recorrente nas questões de competição. Vou editando o comentário acima conforme for achando questões boas pros conteúdos... Se achar alguma pode editar o meu comentario também! e me dar um toque no telegram pra debatermos se é uma questão boa para inciantes que aborde o tema correspondente!

**Comment by Andreabenf** [comment]
Eu e a @heylisten64 vimos que o UVA não é muito viável para inciantes que não sabem laços de repetições. E também existe o problema de que não existem "níveis" no UVA, o que torna dificil nivelar os exercícios.
Então após uma conversa com a @KahCosta decidimos fazer o máximo possivel, levando em conta que ficarão algumas coisas em pendência. (Como por exemplo: não ter niveis em todos os exercicios)

**Comment by heylisten64** [comment]
utter_desafio_repeticao:
    - text: |
        Então você quer um desafio pra testar todo o conhecimento já visto até então... Certo! Quero ver
        você resolver alguns exercícios um pouco mais complexos, a começar pelo nível 1. Você pode me enviar
        a submissão por aqui mesmo, que te retornarei um feedback!

        Aqui está o exercício: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=79&page=show_problem&problem=2030%60

        Também não se esqueça de continuar sua carreira de desenvolvedor python me perguntando sobre funções!

**Comment by heylisten64** [comment]
- [x] primeiro criar as utter desafio, redirecionando para o próximo tema e implementar toda domain
- [x] criar intents e stories das utter desafios
- [ ] redirecionar nas de exercicio para as utter desafios
