### ISSUE TITLE
Documentar Riscos

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#32]
Criar documento referente ao levantamento de Riscos da disciplina
**Tarefas**

- [x] Criar documento de riscos existentes no desenvolvimento do projeto 

**Critérios de aceitação**

- [x] Documento revisado e documentado no Github Pages
- [x] Link do documento disponível na issue

**Comment by Lucas362** [comment]
Foi decidido a criação de um documento de detalhamento de riscos como pontapé inicial para a criação do plano de gerenciamento de riscos
