### ISSUE TITLE
Refatoração da GhPages

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#323]
Refatorar GhPages de acordo conteúdos inseridos afim de atomizar o conjunto de documentos presentes.

**Tarefas**

- [x] Atomizar a criação de tópicos do conjunto de documentos
- [x] Criar fluxo de conversa para divulgar Aix na página inicial

**Critérios de aceitação**

- [x] GhPages atualizada

**Comment by KahCosta** [comment]
vamos adicionar um gif de interação entre a AIx e o usuário?

**Comment by KahCosta** [comment]
@heylisten64 acha que consegue fazer esse gif?

**Comment by heylisten64** [comment]
acho que consigo sim!

**Comment by heylisten64** [comment]
![Peek 25-05-2019 11-41](https://user-images.githubusercontent.com/43069991/58370895-48c3a200-7ee2-11e9-8548-414fc0db668f.gif)

**Comment by heylisten64** [comment]
Como não recebi muitos requisitos, talvez não seja exatamente assim que você quer. Mas de qualquer forma, eu fiz a partir do Peek Animated:
```
sudo add-apt-repository ppa:peek-developers/stable
sudo apt-get update
sudo apt-get install peek
```
É bem fácil de fazer e bem intuitivo!

**Comment by KahCosta** [comment]
@heylisten64 , acha que rola de fazer simulando uma cv com a Aix?

**Comment by heylisten64** [comment]
![Peek 31-05-2019 15-54](https://user-images.githubusercontent.com/43069991/58731438-ad886c00-83bc-11e9-83ed-3fef54a7406a.gif)

**Comment by Lucas362** [comment]
Acredito que uma boa opção seria um gif com desktop para a opção do jupyter e outro gif com mobile para o telegram

**Comment by heylisten64** [comment]
![jupyter](https://user-images.githubusercontent.com/43069991/58740006-19ca9600-83e4-11e9-898f-b1c08534cb4e.gif)

**Comment by heylisten64** [comment]
Pensei em trazer um pouco do nosso documento de visão de forma dinâmica, com a utilizaçao dos gifs que vocês citaram pra nossa page principal
adicionar um pouco mais além das funcionalidades, deixar bem claro pra quem o nosso produto é destinado como a parte interessada etc
acho que isso ajudaria a vender melhor nosso produto....
pra isso pensei em fazer ilustrado, em gif também a nossa parte interessada
colocando professores, empresas, escolas etc ilustrados em um gif
segue o modelo de ilustração
![parte interessada 1](https://user-images.githubusercontent.com/43069991/58741418-beea6c00-83ee-11e9-95aa-ed71b1c57fa9.png)

**Comment by heylisten64** [comment]
Ai cabe a vocês decidirem se é algo que vale a pena acrescentar
acho q seria bom pegar três (o número como critério estético mesmo) tópicos mais importantes pra apresentar nosso produto
observando o nosso documento de visão eu percebi os seguintes tópicos importantes:
* parte interessada: Instituições físicas acadêmicas, empresas privadas, professores, plataformas digitais.
* usuarios: Estudantes de cursos da computação, alunos de outras áreas interessados na interdisciplinariedade, profissionais autônomos.
* ambiente do usuario: telegram e jupyter

**Comment by KahCosta** [comment]
Muito bom Gabi! acho que pode ser criado um tpico com a divulgação para professores e alunos e um outro topico para divulgação das tarefas da AIx

**Comment by heylisten64** [comment]
* parte interessada
![image](https://user-images.githubusercontent.com/43069991/58768424-3c3dea00-8571-11e9-8f62-038c6cd5eef4.png)

**Comment by heylisten64** [comment]
* parte interessada
https://giphy.com/gifs/RHPj2DDPeg1GsXB7LI
![image](https://user-images.githubusercontent.com/43069991/58768453-e1f15900-8571-11e9-8525-5d5bfbf09004.png)

**Comment by heylisten64** [comment]
## PARTE INTERESSADA
![picasion com_ebf1424d51c2b9dd684367ef86357973](https://user-images.githubusercontent.com/43069991/58768455-fc2b3700-8571-11e9-9b2c-923cd059284b.gif)
## FUNÇÕES
![picasion com_77be490d381148aea3e0d6bc34a83aec](https://user-images.githubusercontent.com/43069991/59073690-03449480-8853-11e9-9465-d8516b36a129.gif)

## AMBIENTES
![picasion com_d091e05f52482014c1ff412da64371f7](https://user-images.githubusercontent.com/43069991/58769201-0bfb4900-857b-11e9-9d1b-7bce9012f032.gif)

**Comment by heylisten64** [comment]
### imagens do primeiro gif
![EMPRESAS](https://user-images.githubusercontent.com/43069991/58768501-a3a86980-8572-11e9-997e-336145108e59.jpg)
![PLATAFORMAS](https://user-images.githubusercontent.com/43069991/58768502-a3a86980-8572-11e9-9e4c-760a6f04b667.jpg)
![ESCOLAS](https://user-images.githubusercontent.com/43069991/58768503-a7d48700-8572-11e9-90aa-04fa2cde9f32.jpg)
![PROFESSORES](https://user-images.githubusercontent.com/43069991/58768504-a7d48700-8572-11e9-9845-2675c59b332d.jpg)
### imagens do segundo gif
![func1](https://user-images.githubusercontent.com/43069991/58995328-be4f2e00-877e-11e9-9512-b7ab64767755.jpg)
![FUNC2p](https://user-images.githubusercontent.com/43069991/58998946-56084880-878e-11e9-9015-b20247df0c4c.jpg)
![FUNC3_](https://user-images.githubusercontent.com/43069991/59065079-d2eefd00-8836-11e9-8c13-e4b9c48c0b52.jpg)
![FUNC4_](https://user-images.githubusercontent.com/43069991/59070083-4d724980-8844-11e9-91e2-11d059221aba.jpg)
![FUNC5_](https://user-images.githubusercontent.com/43069991/59072682-74ce1400-884e-11e9-866a-3c3729e8d8d7.jpg)
![FUNC6_](https://user-images.githubusercontent.com/43069991/59073523-71d52280-8852-11e9-93b8-61e54e0e48a5.jpg)



### imagens do terceiro gif
![TELEGRAM](https://user-images.githubusercontent.com/43069991/58769213-1ae1fb80-857b-11e9-886e-4a2d35e52a30.jpg)
![JUPYTER](https://user-images.githubusercontent.com/43069991/58769214-1ae1fb80-857b-11e9-8c12-52ead08e63f4.jpg)

**Comment by heylisten64** [comment]
@KahCosta você pode listar pra mim tudo que entra nas funcionalidades? vou tentar colocar ilustrado também, mas pra não esquecer nada se você puder fazer isso pra mim, agradeceria bastante!! e se tiver ideias de ilustração pra cada função, é só me avisar

**Comment by heylisten64** [comment]
* pensando nas funcionalidades temos:

- [x]  ilustração concluída
**Funcionalidade:** Pesquisa no stackoverflow.
**Ilustração:** Lupinha + logo do stack.

- [x]  ilustração concluída
**Funcionalidade:** Sobre. 
**Ilustração:** livro aí na capa coloca "python" e a logo

- [x]  ilustração concluída
**Funcionalidade:** Exemplos, exemplos na prática. 
**Ilustração:** computador vscode

- [x]  ilustração concluída
**Funcionalidade:** Conteúdo extra. 
**Ilustração:** pilha de livros

- [x]  ilustração concluída
**Funcionalidade:** Exercícios. 
**Ilustração:** lista de exercício.

- [x]  ilustração concluída
**Funcionalidade:** Conexão com o UVA. 
**Ilustração:** uva.

Se estiver faltando alguma funcionalidade, me avisem pfv!

- [x] FUNDO ffffffff
- [x] FUNDO ffeeeeee

![picasion com_dd1d39a3883f9185a05ad40f30e0fb4d](https://user-images.githubusercontent.com/43069991/59074226-75b67400-8855-11e9-8e17-b46d09c9c1af.gif)

**Comment by Lucas362** [comment]
> ## PARTE INTERESSADA
> ![picasion com_ebf1424d51c2b9dd684367ef86357973](https://user-images.githubusercontent.com/43069991/58768455-fc2b3700-8571-11e9-9b2c-923cd059284b.gif)
> 
> ## FUNÇÕES
> ## AMBIENTES
> ![picasion com_d091e05f52482014c1ff412da64371f7](https://user-images.githubusercontent.com/43069991/58769201-0bfb4900-857b-11e9-9d1b-7bce9012f032.gif)

Excelente trabalho, as artes ficaram muito boas

**Comment by Lucas362** [comment]
Seria possível a criação de gifs com o fundo transparente ou na seguinte cor: #EEEEEE? Para melhor se adequar à alguns blocos presentes em nossa página

**Comment by heylisten64** [comment]
![picasion com_dd1d39a3883f9185a05ad40f30e0fb4d](https://user-images.githubusercontent.com/43069991/59074245-86ff8080-8855-11e9-8a1d-93d6e3457aa7.gif)

![parte_interessada](https://user-images.githubusercontent.com/43069991/58772392-28a17c00-858f-11e9-9246-78e758ba0df6.gif)

![ambiente](https://user-images.githubusercontent.com/43069991/58772875-4bcd2b00-8591-11e9-981a-54db73e39c0f.gif)

da uma olhada se é essa cor!
