### ISSUE TITLE
Integração Aix com UVA online judge para realização de login do usuário

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2019.1-Grupo-1#326]
Possibilitar o login do usuário no site do UVA Online Judge a partir da Aix, o que irá permitir a submissão e o feedback de códigos.

**Tarefas**

- [x] Estudar viabilidade de aplicação de GET e POST no site do UVA
- [x]  Documentar estudo realizado do site
- [x]  Integrar o UVA de forma que o usuário consiga fazer login por meio do bot

**Critérios de aceitação**

- [x]  Usuário conseguir logar no site pelo próprio bot
- [x]  Estudo do site documentado para facilitação da compreensão de todo o time.

**Comment by iurisevero** [comment]
Durante a integração da API foi percebido que a parte de login do usuário não é disponibilizada, tendo que ser feita por fora, o que fez necessário criar essa nova issue que influencia diretamente nas issues #317  e #316

**Comment by iurisevero** [comment]
Para validar o login foi utilizado o código, em JavaScript, [uva-node](https://github.com/lucastan/uva-node), e a partir dos estudos realizados em cima dele, pelo @Andreabenf, será formulado uma forma de fazer o login pelas CustomActions.

**Comment by iurisevero** [comment]
Após analisarmos os repositórios do [UVACommandLine](https://github.com/scvalencia/UVACommandLine) e do [uva-node](https://github.com/lucastan/uva-node) percebemos que no primeiro a submissão de questões não era efetivada, já no segundo era possível submeter corretamente. (20/05/2019)
A princípio não estávamos conseguindo entender o por quê disso, mas após analisarmos os parâmetros passados para o post request de cada um foi percebido que o código do UVACommandLine não utilizava os cookies do site para suas ações, isso foi percebido pelo o @Andreabenf. (21/05/2019)
Após isso fizemos um pareamento, o @Andreabenf, a @KahCosta, o @Lucas362  e eu, para tentarmos consertar a submissão e arrumar o login. Pareamos na faculdade e ficamos por volta de 2h aprendendo como requisitar os cookies do site e fazendo testes de request com o cookie, para verificar se a submissão acontecia de forma eficaz. Conseguimos realizar o login utilizando os cookies, porém a submissão continuava quebrando, o que tornava nossa conquista inválida.
Depois das 2h de pareamento o @Andreabenf e o @gustable42  se juntaram com o @GuiMarques98 para tentar resolver o problema, porém o site do UVa Online Judge saiu de ar e impossibilitou o trabalho. (22/05/2019)
Hoje o @Yoshida-Eduardo estudou o problema e, a partir dos dados já obtidos, encontrou uma possível solução para o mesmo que está sendo testada.
Assim que confirmamos a solução, a implementação no projeto será iniciada, o que irá possibilitar o andamento das outros issues que se correlacionam com essa. (23/05/2019)

**Comment by gustable42** [comment]
Também foi considerada a utilização do micro-serviço relacionado as requisições ao UVA ser desenvolvido em JS devido a API desenvolvida em Node ter dado resultados mais satisfatório. Entretanto, com essa solução do @Yoshida-Eduardo dando certo, descartaremos a ideia do JS.

**Comment by iurisevero** [comment]
Estudando meios que pedir ao usuário o username e a senha do UVa para fazermos o login encontrei o [Forms](https://rasa.com/docs/rasa/core/forms/) do Rasa que parece suprir as necessidades atuais. Começarei a branch da issue iniciarei alguns testes quanto a utilização do mesmo.

**Comment by Andreabenf** [comment]
A viabilidade da issue acaba de ser confirmada pelo @Yoshida-Eduardo .
Começarei a trabalhar com o @iurisevero na branch para efetuar um login de forma eficiente e conseguir manter uma sessão
