### ISSUE TITLE
Adicionar tópicos de códigos na prática relacionados aos exemplos de cada conteúdo

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#334]
Adicionar tópicos de códigos na prática relacionados aos exemplos de cada conteúdo. 

**Tarefas**

- [ ] Incluir aos exemplos um código relacionado aos exemplos, para o usuário testar durante a compilação
- [ ] Adaptar o que foi acrescentando ao fluxograma de utters

**Critérios de aceitação**

- [ ] Aix ser capaz de responder este tópico
- [ ] Conteúdo não reduzir precisão de resposta para outro tópico
- [ ] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
Fiz um rascunho de código para os exemplos que damos ao usuário, o que acha?

**Exemplo de variáveis**
```
# Fórmula de Bháskara
# Equação: -5x^2 + 4x + 1 = 0
a = -5
b = 4
c = 1
delta = b*b - 4*a*c

# a operação ** no python representa
# exponencial, ou seja x**2 == x*x
x1 = (-b + delta**1/2)/(2*a)
x2 = (-b - delta**1/2)/(2*a)

print("x' =", x1)
print("x'' =", x2)
```
```
# nome da variável = conteúdo da variável
username = "username@email.com"
senha = "digitos1234"

print('Meu username é:', username, 'e minha senha... É segredo!')
```

**Exemplo de conficional**
```
# Veja como a estrutura condicional
# responde aos diferentes valores de x

x = 2
if x == 2:
	print("amo feno")
elif x == 5:
	print("amo python")
else:
	print("amo a Aix")

x = 5
if x == 2:
	print("amo feno")
elif x == 5:
	print("amo python")
else:
	print("amo a Aix")

x = 10
if x == 2:
	print("amo feno")
elif x == 5:
	print("amo python")
else:
	print("amo a Aix")
```

**Exemplo de repetição**
* For:
```
distancia_do_feno_para_celeiro = 5
quantidade_de_passos = 0

# a função range() cria um intervalo de 
# 0 até o valor passado para ela,
# sem contar com o próprio valor
for i in range(distancia_do_feno_para_celeiro):
	quantidade_de_passos = quantidade_de_passos + 1

print(quantidade_de_passos)
```

* While:
```
distancia_do_feno_para_celeiro = 5
quantidade_de_passos = 0

while(distancia_do_feno_para_celeiro > 0):
	distancia_do_feno_para_celeiro = distancia_do_feno_para_celeiro - 1
	quantidade_de_passos = quantidade_de_passos + 1

print(quantidade_de_passos)
```

**Exemplo de Função**
```
def oi(nome):
    return 'Oi, ' + nome + '!'

nome = 'João'
cumprimento = oi(nome)
print(cumprimento)
```

**Exemplo de Arquivos**
```
# Para escrever em um arquivo
arquivo = open('bodes-mais-legais.txt', 'w')
texto = "Aix Chatbot"
arquivo.write(texto)
arquivo.close()

# Para ler um arquivo
arquivo = open('bodes-mais-legais.txt', 'r')

# É necessário fazer um loop no arquivo
# para passar por todas suas linhas
for linha in arquivo:
	print(linha)
```

**Exemplo de Vetores**
```
fenos_por_dia = [4, 3, 3, 2, 3, 4, 5]
# Quantos fenos comi no domingo
print(fenos_por_dia[0])

# Passar por todos dias da semana
for feno in fenos_por_dia:
	print('Eu comi', feno, 'fenos esse dia!')
```

**Exemplo de Matrizes**
```
duvidas_por_mes = [ [0, 4, 7, 9, 5, 3, 1],
                    [0, 0, 2, 4, 3, 2, 2],
                    [1, 2, 4, 3, 7, 1, 1],
                    [0, 5, 6, 7, 7, 5, 0] ]

# Quantas dúvidas eu tirei na
# segunda-feira da primeira semana
print(duvidas_por_mes[0][1])

# Para ver todos os dias do mês
for semana in duvidas_por_mes:
	for duvida in semana:
		print('Esse dia eu tirei', duvida, 'dúvidas!')
```

**Exemplo de importar biblioteca**
```
import math
valor = 9

# A função sqrt é uma função da
# biblioteca 'math', por isso
# é necessário colocar o 'math.'
# antes de chamá-la
raiz_quadrada = math.sqrt(valor)

print('A raíz quadrada de', valor, 'é', raiz_quadrada, '!!!')
```

**Comment by iurisevero** [comment]
## Intents

**intent:codigo_em_python_variaveis**
- código variáveis
- códipo python variáveis
- variáveis em python
- código de variáveis
- codigo de inteiros
- exemplo prático de variáveis
- exemplo pratico de pontos flutuantes
- variáveis no python
- double no python
- variaveis em código
- char em codigo
- código em python de variáveis
- codigo em python de booleanos
- implementação com variaveis
- implementacao com strings
- exemplifique em código variáveis
- exemplifique em codigo int
- como funcionam variáveis no código
- como funcionam float no codigo
- implemente um código com booleanos
- implemente um exemplo de variáveis
- me mostre um código com variáveis
- demonstre inteiros na prática
- demonstre strings na pratica
- demonstre um código em python que possua variáveis


## Utters

**utter_codigo_em_python_variaveis**
- text: |
	Então você quer um exemplo mais palpável de variáveis?
	Dá uma olhada nesse código aqui, ele é béem legal e dá atée para 
	você colar ele no terminal e ver como fica!!!

	``` código ```

	Que tal um conteúdo mais detalhado? Tenho vários links de conteúdo extra sobre variáveis, só me pedir!
    Bée..Tente usar as seguintes palavras para me ajudar a te entender: saber mais, conteudo extra, variáveis

    Se já está entendendo tudo direitinho, você pode me perguntar sobre 'Hello World!'!


> Para os outros conteúdos é só adaptar um pouco os textos. Para intents dá pra só trocar as palavras chaves.

**Comment by Andreabenf** [comment]
Caracas, ficou muito bom

**Comment by Andreabenf** [comment]
#### exemplo de input de dados

NOME = input("Digite o nome: ")
IDADE = input("Digite a idade: ")
MEDIA_ESCOLAR=  input("Digite a media escolar: ")
print(str(NOME) + " tem " + str(IDADE) + " anos e possui a media escolar de " + str(MEDIA_ESCOLAR))

**Comment by heylisten64** [comment]
Amigos, a ideia que tive, pra sanar o problema de dois exemplos, por ex, e ficar uma resposta sucinta, eh adicionar no topico de codigos da seguinte forma:
### ("nome" do exemplo) exemplo bhaskara
- imagem do codigo
- codigo.py

mas deveriamos ver a possibilidade de mandar arquivos.py

**Comment by iurisevero** [comment]
> Amigos, a ideia que tive, pra sanar o problema de dois exemplos, por ex, e ficar uma resposta sucinta, eh adicionar no topico de codigos da seguinte forma:
> 
> ### ("nome" do exemplo) exemplo bhaskara
> * imagem do codigo
> * codigo.py
> 
> mas deveriamos ver a possibilidade de mandar arquivos.py

É uma boa, poderemos fazer assim dps de confirmar a viabilidade de enviar arquivos
