### ISSUE TITLE
Refatorar, na saudação, as funcionalidades do bot

### ISSUE THREAD

**Issue by gustable42** [fga-eps-mds/2019.1-Grupo-1#337]
Refatorar as utters de saudação e /help para que as funcionalidades e incapacidades do bot estejam mais claras para o usuário.

**Tarefas**

- [x] Refatorar as Utters mostrando com mais clareza as capacidades do bot.

**Critérios de aceitação**

- [x]  Aix ser capaz de responder de forma clara suas capacidades.

**Comment by pedroeagle** [comment]
Atualizei as utters para os conteúdos mais atuais e adicionei mais algumas intents pro conteúdo que informa as capacidades do bot. Após serem fechadas algumas issues dessa sprint essa issue deverá receber mais atualizações.

**Comment by Andreabenf** [comment]
Agora que o caminho do bot mudou, temos que refatorar mais coisas.
Hoje dia 28/07/2019 iremos ter uma reunião para decidir isso melhor.
Pois agora o bot possui a opção desafios, código python comentado entre outras.

**Comment by pedroeagle** [comment]
é necessário inserir na saudação e nas funcionalidades conteúdos inseridos nessa sprint como conteúdo de strings, entrada do usuário e a existência de um cronograma

**Comment by Andreabenf** [comment]
Galera, eu dei o pull da devel nessa branch 337.
Ai isso corrigiu ela quebrando nos testes.
