### ISSUE TITLE
Refatoração do conteúdo sobre estruturas de repetição

### ISSUE THREAD

**Issue by pedroeagle** [fga-eps-mds/2019.1-Grupo-1#338]
Explicar estruturas de repetição específicas (for e while) nos conteúdos.

**Tarefas**

- [x] Explicar como funciona o for e o while no conteúdo sobre estruturas de repetição de forma separada.

**Critérios de aceitação**

- [ ] O conteúdo deve estar claro e usuário deve compreender bem e saber distinguir cada um.
- [ ] O conteúdo não atrapalhar os conteúdos existentes.

**Comment by iurisevero** [comment]
@pedroeagle como você pensou em fazer essa issue?
Acho que seria massa separarmos o for e o while na explicação, a partir do texto mesmo, e nos exemplos colocar um loop de cada tipo no código. Podíamos adaptar o texto atual com algo no estilo "Esse exemplo pode ser feito tanto com o loop 'for' quanto com o 'while'" e aí, na issue dos códigos, eu crio um exemplo com cada um deles

**Comment by iurisevero** [comment]
**Sobre**
Estruturas de repetição são funções capazes de iterar determinada ação. Nelas, você pode determinar uma meta e uma instrução. Ou seja, você vai realizar determinada ação repetidas vezes até alcançar o resultado que deseja! Para conseguir fazer isso, temos as estruturas de repetição for e while da linguagem Python.
O for funciona com a seguinte estruturação:
    for <variável> in range(<valor>):
       <bloco de ações>
Ou seja, para (for) <variável> no intervalo (in) range(<valor>) realize o seguinte bloco de ações.
Já o while funciona de forma mais simples:
    while <operação booleana>:
        <bloco de ações>
Ou seja, enquanto (while) a operação booleana for verdadeira realize o bloco de ações.

Quer ver os loops em ação? Me peça um exemplo de estruturas de repetição!

**Exemplo**
Imagine que eu, Aix, estou no celeiro e meu feno do lado de fora, no campado. Para chegar lá, precisarei de alguns passos. Cada passo será uma ação minha. No caso, eu terei que executar uma quantia de passos finitos até chegar ao meu objetivo. Repetirei então a minha ação 'dar um passo' até chegar ao meu feno. Funciona mais ou menos assim!
        Quer ver como ficaria o código disso? Só pedir por um exemplo em código que eu te mostro um!
        Bée..Se seu pedido tiver essas palavras específicas me ajudaria bastante a te entender: código, for, while, exemplo prático, estruturas de repetição
        Simples como comer capim!
        E olha, se você estiver se sentindo confiante nesse conteúdo, você pode me pedir para falar sobre funções, que é o próximo conteúdo!


> O exemplo de código ficará por conta da issue #334

**Comment by iurisevero** [comment]
_Exemplo retirado do comentário da issue #334_

**Exemplo de repetição**
* For:
```
distancia_do_feno_para_celeiro = 5
quantidade_de_passos = 0

# a função range() cria um intervalo de 
# 0 até o valor passado para ela,
# sem contar com o próprio valor
for i in range(distancia_do_feno_para_celeiro):
	quantidade_de_passos = quantidade_de_passos + 1

print(quantidade_de_passos)
```

* While:
```
distancia_do_feno_para_celeiro = 5
quantidade_de_passos = 0

while(distancia_do_feno_para_celeiro > 0):
	distancia_do_feno_para_celeiro = distancia_do_feno_para_celeiro - 1
	quantidade_de_passos = quantidade_de_passos + 1

print(quantidade_de_passos)
```

**Comment by pedroeagle** [comment]
> @pedroeagle como você pensou em fazer essa issue?
> Acho que seria massa separarmos o for e o while na explicação, a partir do texto mesmo, e nos exemplos colocar um loop de cada tipo no código. Podíamos adaptar o texto atual com algo no estilo "Esse exemplo pode ser feito tanto com o loop 'for' quanto com o 'while'" e aí, na issue dos códigos, eu crio um exemplo com cada um deles

não havia pensado ainda, podemos fazer da forma como sugeriu

**Comment by iurisevero** [comment]
Acredito que poderíamos deixar o sobre com as seguintes frases:
O for funciona da seguinte forma: para (for) <variável> no intervalo (in range(<valor>)) realize o seguinte bloco de ações.
Já o while funciona de forma mais simples: enquanto (while) a operação booleana for verdadeira realize o bloco de ações.

Para que o texto não fique muito grande, aí a estruturação fica no exemplo prático

**Comment by pedroeagle** [comment]
> Acredito que poderíamos deixar o sobre com as seguintes frases:
> O for funciona da seguinte forma: para (for) <variável> no intervalo (in range()) realize o seguinte bloco de ações.
> Já o while funciona de forma mais simples: enquanto (while) a operação booleana for verdadeira realize o bloco de ações.
> 
> Para que o texto não fique muito grande, aí a estruturação fica no exemplo prático

certo. o exemplo prático é o que ainda será implementado em outra issue, certo?

**Comment by pedroeagle** [comment]
# Conteúdo inserido:
## Sobre:
    Você já tentou contar até 10 no python? Tenta aí! Se você utilizou uma função print para cada número, tenho que te contar um segredo: dá para fazer isso com um só print! 
        Como? Béem... você vai utilizar as estruturas de repetição, que, basicamente são capazes de reproduzir determinada ação. Temos como estruturas do Python o WHILE e o FOR.
        Estruturas de repetição são funções capazes de iterar determinada ação. Nelas, você pode determinar uma meta e uma instrução. Ou seja, você vai realizar determinada ação repetidas vezes até alcançar o resultado que deseja! 
        Para conseguir fazer isso, temos as estruturas de repetição for e while da linguagem Python.
        O for funciona da seguinte forma: para (for) <variável> no intervalo (in range()) realize o seguinte bloco de ações. Dentro de range são informados os valores inicial e final. A cada passo a variável será incrementada em 1.
        Já o while funciona de forma mais simples: enquanto (while) a operação booleana for verdadeira realize o bloco de ações.
        Quer ver os loops em ação? Me peça um exemplo de estruturas de repetição!
        Bée..Se seu pedido tiver essas palavras específicas me ajudaria bastante a te entender: saber mais sobre repetição, for, while, treinar, exercicios
        Simples como comer capim!

## Exemplo:
    Imagine que eu, Aix, estou no celeiro e meu feno do lado de fora, no campado. Para chegar lá, precisarei de alguns passos. 
        Cada passo será uma ação minha. No caso, eu terei que executar uma quantia de passos finitos até chegar ao meu objetivo. Repetirei então a minha ação 'dar um passo' até chegar ao meu feno. Funciona mais ou menos assim!
        Quer ver como ficaria o código disso? Só pedir por um exemplo em código que eu te mostro um!
        Bée..Se seu pedido tiver essas palavras específicas me ajudaria bastante a te entender: código, for, while, exemplo prático, estruturas de repetição
        Simples como comer capim!
        E olha, se você estiver se sentindo confiante nesse conteúdo, você pode me pedir para falar sobre funções, que é o próximo conteúdo!
      image:
        https://user-images.githubusercontent.com/43069991/56447561-626c3b00-62df-11e9-81f3-77963cf19bd5.png

Os exemplos práticos individuais ficaram pra ser adicionados em uma outra issue em que serão adicionados exemplos práticos para outros conteúdos.

**Comment by iurisevero** [comment]
> # Conteúdo inserido:
> ## Sobre:
> ```
> Você já tentou contar até 10 no python? Tenta aí! Se você utilizou uma função print para cada número, tenho que te contar um segredo: dá para fazer isso com um só print! 
>     Como? Béem... você vai utilizar as estruturas de repetição, que, basicamente são capazes de reproduzir determinada ação. Temos como estruturas do Python o WHILE e o FOR.
>     Estruturas de repetição são funções capazes de iterar determinada ação. Nelas, você pode determinar uma meta e uma instrução. Ou seja, você vai realizar determinada ação repetidas vezes até alcançar o resultado que deseja! 
>     Para conseguir fazer isso, temos as estruturas de repetição for e while da linguagem Python.
>     O for funciona da seguinte forma: para (for) <variável> no intervalo (in range()) realize o seguinte bloco de ações. Dentro de range são informados os valores inicial e final. A cada passo a variável será incrementada em 1.
>     Já o while funciona de forma mais simples: enquanto (while) a operação booleana for verdadeira realize o bloco de ações.
>     Quer ver os loops em ação? Me peça um exemplo de estruturas de repetição!
>     Bée..Se seu pedido tiver essas palavras específicas me ajudaria bastante a te entender: saber mais sobre repetição, for, while, treinar, exercicios
>     Simples como comer capim!
> ```
> 
> ## Exemplo:
> ```
> Imagine que eu, Aix, estou no celeiro e meu feno do lado de fora, no campado. Para chegar lá, precisarei de alguns passos. 
>     Cada passo será uma ação minha. No caso, eu terei que executar uma quantia de passos finitos até chegar ao meu objetivo. Repetirei então a minha ação 'dar um passo' até chegar ao meu feno. Funciona mais ou menos assim!
>     Quer ver como ficaria o código disso? Só pedir por um exemplo em código que eu te mostro um!
>     Bée..Se seu pedido tiver essas palavras específicas me ajudaria bastante a te entender: código, for, while, exemplo prático, estruturas de repetição
>     Simples como comer capim!
>     E olha, se você estiver se sentindo confiante nesse conteúdo, você pode me pedir para falar sobre funções, que é o próximo conteúdo!
>   image:
>     https://user-images.githubusercontent.com/43069991/56447561-626c3b00-62df-11e9-81f3-77963cf19bd5.png
> ```
> 
> Os exemplos práticos individuais ficaram pra ser adicionados em uma outra issue em que serão adicionados exemplos práticos para outros conteúdos.

Perfeito!!
