### ISSUE TITLE
Estudo sobre a implementação de form actions 

### ISSUE THREAD

**Issue by Andreabenf** [fga-eps-mds/2019.1-Grupo-1#339]
Será feito um estudo sobre como foi implementado form action no rasa. 
E a partir disso, viabilizar a implementação de um algoritiimo similiar para nossas actions.

**Tarefas**

- [x] Visualizar a documentação do Rasa para ver como foi implementado
- [ ] Documentar estudo realizado da implementação do form action

**Critérios de aceitação**

- [ ] Estudo do forms actions documentado para facilitação da compreensão de todo o time.

**Comment by iurisevero** [comment]
A implementação do FormAction pode ser encotrada [aqui](https://github.com/RasaHQ/rasa-sdk/blob/0.13.1/rasa_core_sdk/forms.py). Atentando ao fato de que nosso projeto utiliza o Rasa Core 0.13.1, versão citada no link.
A implementação está bem comentada e os nomes são compreensíveis, o que diminuirá a dificuldade da issue, porém, é um código muito complexo e extenso, o que faz com que a dificuldade não seja baixa.

**Comment by iurisevero** [comment]
Tava estudando sobre Forms, vi esse link [aqui](https://blog.rasa.com/building-contextual-assistants-with-rasa-formaction/?_ga=2.160985727.373844742.1559067472-1426259208.1555448186) q é mto bom, recomendo a todos.
@heylisten64  @Andreabenf  @pedroeagle  @gustable42 @KahCosta
