### ISSUE TITLE
Refatoração do fluxograma das utters

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#340]
Refatoração do fluxograma das utters, elaborar o mapa e verificar se nada está fora do fluxo.

**Tarefas**

- [x] Criar um documento de um mapa visual do caminho das utters
- [x] Adaptar o fluxograma dentro do bot

**Critérios de aceitação**
- [x] Aix ser capaz de guiar o usuário de forma objetiva
- [x] Mapa visual do caminho voltado para possibilitar adaptações futuras
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
Guys, a utter de exemplo de variáveis tá com uma frase duplicada, praticamente... E a ordem das mensagens tá meio zoada... Tá falando pro usuário ir pra conteúdo extra, depois fala que ele pode ir pra "hello world" também e aí explica como pedir conteúdo extra d forma mais direta... Quando estiverem refatorando essa parte, dá uma olhada nisso!
Seria interessante tirar a frase duplicada e colocar a sugestão de "hello world" depois da explicação de como pedir conteúdo extra

**Comment by heylisten64** [comment]
Antes de fazer qualquer implementação no bot, vou criar o documento de mapa visual do fluxograma, para facilitar o trabalho. A ideia é que a cada conteúdo inserido esse mapa seja implementado para que não aconteça confusões futuras...

**Comment by heylisten64** [comment]
estou elaborando o mapa pelo draw io, apenas adicionando os topicos por enquanto
https://www.draw.io/#G1POlRP3zxJ3c9anUbGIPn--3R2TkAZLAK

**Comment by heylisten64** [comment]
![image](https://user-images.githubusercontent.com/43069991/58510527-4fb31480-816f-11e9-8931-081169e893e5.png)
eu só formatei bonitinho e acrescentei os topicos, deixei eles juntos... pode ter algo fora do lugar mas a ordenação vamos documentar no pareamento hoje mesmo! Apenas informando o processo da issue, caso alguém necessite dela para a conclusão de outras.

**Comment by heylisten64** [comment]
![image](https://user-images.githubusercontent.com/43069991/58603655-e9f68380-8267-11e9-898d-0eed28119dbe.png)
O documento do fluxo feito, passível de formatação, porém o conteúdo criado!

**Comment by heylisten64** [comment]
![image](https://user-images.githubusercontent.com/43069991/58604550-1cee4680-826b-11e9-87ac-85fe96e3f26f.png)
https://www.draw.io/#G1POlRP3zxJ3c9anUbGIPn--3R2TkAZLAK
Aqui está o nosso fluxo, passível a alterações/formatações, mas até então decidimos dessa forma!

**Comment by heylisten64** [comment]
No Feedback do uva terá uma indução para 3 conteúdo: sobre stack, pesquisar, cronograma.
No cronograma não terá indução para nenhum conteúdo específico, mas terá os tópicos de todas as matérias que o usuário pode aprender mais sobre.
Os blocos pretos é que não participarão do fluxo.
Sempre seguindo verticalmente, acabou conteúdo passa para a proxima fileira.

**Comment by heylisten64** [comment]
![image](https://user-images.githubusercontent.com/43069991/58604981-af431a00-826c-11e9-8882-1b5f9728faba.png)
A nossa divisão ocorrerá na seguinte ordem: @heylisten64, @gustable42, @pedroeagle 
respeitando a bolinha vermelha, incluindo esse conteúdo!
A parte branca embaixo fica a critério de quem fazer primeiro ou quem solicitar ajuda

**Comment by pedroeagle** [comment]
como ainda não sabemos com funciona nosso banco de dados vamos sempre mandar dos desafios para o login para que seja feita a submissão no uva.

**Comment by pedroeagle** [comment]
sugestão de conteúdo que indicará o login no uva:
```
Para submeter o seu código é necessário entrar em uma conta do juiz online UVA. Para entrar é só pedir.
          Se seu pedido tiver essas palavras me ajudaria bastante: login uva, conectar no uva
          Não se preocupe se ainda não tem uma conta, é só pedir para se conectar que te ensino ;) 
```

**Comment by gustable42** [comment]
Alguns conteúdos não possuem todos os 6 tópicos. Então alguns tópicos como 'Conteúdo Extra Condicionais' conduz o usuário para 'Sobre repetição' ao invés de 'Desafios condicionais'

**Comment by pedroeagle** [comment]
# Conteúdos a serem adicionados:
## exemplo com código:
- strings
## exercícios:
- importar bibliotecas
- função

## conteúdo extra:
-  importar biblitotecas

## desafio:
- condicionais
- strings
- importar_bibliotecas
- arquivos

**Comment by heylisten64** [comment]
desafio de variaveis em pendencia

**Comment by heylisten64** [comment]
vou mandar o pr, guys!

**Comment by heylisten64** [comment]
deram muuuitos erros quanto ao flake8, o @gustable42 tá arrumando pra q o pr seja aceito
