### ISSUE TITLE
Criar cronograma para usuário iniciante

### ISSUE THREAD

**Issue by pedroeagle** [fga-eps-mds/2019.1-Grupo-1#341]
Criar um cronograma para que um usuário que não tem conhecimento algum possa seguir e aprender python.

**Tarefas**

- [x] Criar conteúdo.
- [x] Informar o usuário que o conteúdo existe.

**Critérios de aceitação**

- [x] O conteúdo não afetar conteúdos existentes.

**Comment by KahCosta** [comment]
Lembrem se de ao final da apresentação do cronograma(que deve ser dinâmico) e claro, induzir o usuário primeiramente a entender o que é python...pois foi assim que mapeamos no nosso fluxograma!

**Comment by KahCosta** [comment]
e depois de induzir o usuário a entender primeiramente o que é Python, apresente a sequencia correta de conteúdos que deve seguir..

**Comment by KahCosta** [comment]
Além disso, lembrem se de refatorar as utters 'finais' de cada conteúdo a fim de ajudar o usuário a tomar a melhor decisão quanto ao proximo conteúdo que segundo nosso cronograma é sugerido

**Comment by heylisten64** [comment]
> Além disso, lembrem se de refatorar as utters 'finais' de cada conteúdo a fim de ajudar o usuário a tomar a melhor decisão quanto ao proximo conteúdo que segundo nosso cronograma é sugerido

Isso será refatorado na issue #340 @KahCosta ! O documento do fluxograma atualizado com os novos conteúdos já tá em andamento, e o link permanecerá ativo no [draw io](https://www.draw.io/#G1POlRP3zxJ3c9anUbGIPn--3R2TkAZLAK) para atualizaçoes futuras

logo após terminarmos, implementaremos na issue citada! 

![image](https://user-images.githubusercontent.com/43069991/58511393-1bd8ee80-8171-11e9-8234-6a4e4527fcb0.png)

nosso processo em andamento, com cada utter implementada... Algumas coisas serão decididas ainda sobre a indução de certos temas a outros no pareamento de hj!

**Comment by heylisten64** [comment]
> Lembrem se de ao final da apresentação do cronograma(que deve ser dinâmico) e claro, induzir o usuário primeiramente a entender o que é python...pois foi assim que mapeamos no nosso fluxograma!

Sobre a parte do cronograma que deve ser **dinâmico** eu tive uma ideia de funcionar como uma agenda, onde tem checks e tudo mais, mas vou ver a viabilidade disso ainda!

**Comment by heylisten64** [comment]
Vamos fazer de forma estática a princípio, amanhã as 10h eu e @pedroeagle vamos parear!
Assim feito de forma estática, vamos procurar a possibilidade de envolver banco de dados no cronograma 👍

**Comment by KahCosta** [comment]
Massa!! a ideia de tentar vincular a funcionalidade de uma agenda no qual no que o usuario for realizando possa ir dando checks é genial! só n sei quanto a viabilidade disso...

**Comment by KahCosta** [comment]
documentem aqui o que decidirem

**Comment by pedroeagle** [comment]
Por enquanto faremos apenas uma lista dos conteúdos a serem seguidos por um usuário iniciante. Depois de descobrirmos como utilizar banco de dados no nosso bot (se já não existe algum) podemos pensar em implementar o que a @heylisten64 sugeriu.

**Comment by pedroeagle** [comment]
o conteúdo foi criado e será inserida a existência dele na issue de refatoração da saudação e /help
