### ISSUE TITLE
Inserir conteúdo sobre strings

### ISSUE THREAD

**Issue by pedroeagle** [fga-eps-mds/2019.1-Grupo-1#342]
Inserir conteúdo sobre strings. O conteúdo envolve: explicação do que é, exemplo, conteúdo extra, links para exercícios seguindo os padrões de histórias de conteúdos já desenvolvidos.

**Tarefas**

- [x] O conteúdo deve ser inserido e mapeado.
- [x] Todos os subconteúdos devem ser inseridos.

**Critérios de aceitação**

- [x] O conteúdo não pode atrapalhar conteúdos existentes.

**Comment by gustable42** [comment]
Estamos mapeando exatamente o que essa issue fará, por enquanto foi acertado que iremos:
-Modificar a utter sobre variáveis para adicionar a possibilidade do usuário pedir por strings
-Criar conteúdo sobre strings;

**Comment by pedroeagle** [comment]
Acabei de criar o conteúdo explicando o que é uma string. Vi que nos exemplos de variáveis se pedirmos um exemplo de inteiro o bot pode dar um exemplo que não é sobre inteiro. O que acham de adicionarmos exemplos de cada um dos tipos individualmente e manter os existentes como um exemplo  geral? Isso pode até mesmo resolver um requerimento do teste de usabilidade que é um exemplo mostrando sintaxe de cada conteúdo.

**Comment by pedroeagle** [comment]
Adicionei um exemplo exclusivo pra strings. O mesmo será feito para os outros conteúdos sobre tipos primitivos.
