### ISSUE TITLE
Seleção e implementação de exercícios do UVA online judge

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#343]
Seleção e implementação de exercícios do UVA online judge, com base nos empecilhos encontrados em tarefas passadas.

**Tarefas**

- [x] Selecionar exercícios em níveis de iniciantes que se adaptam ao fluxograma
- [x] Implementar no bot, com nível 1 de dificuldade
- [x] Exercícios traduzidos em pdf

**Critérios de aceitação**

- [x] Os problemas não apresentarem conteúdos que ainda não foram abordados pelo bot
- [x] O bot ser capaz de apresentar para os usuários os links estáticos divididos em níveis
- [x] Usuário ser capaz de selecionar o nível de exercício que deseja solucionar e submeter no bot
- [x] Usuário consiga de forma intuitiva entender que pode escolher o nível de exercício que deseja solucionar
- [x] Usuário receber pdf com o exercício proposto

**Comment by heylisten64** [comment]
@Andreabenf , acho que seria bom ja irmos procurando exercicios, ja q encontramos os empecilhos na ultima sprint 
tomando cuidado de respeitar o fluxograma, que ja passei pra voce ele +- pronto! 
precisamos de pelo menos um pra condicionais e variaveis!

**Comment by Andreabenf** [comment]
Beleza! Vou ver aqui

**Comment by heylisten64** [comment]
![image](https://user-images.githubusercontent.com/43069991/58750781-be90b600-846c-11e9-9228-6f2d665db3cc.png)
nosso fluxograma atualizado, vamos respeitar ele na hora de inserir os desafios

**Comment by heylisten64** [comment]
o que temos até então:

  utter_desafio_repeticao:
```
    - text: |
        Então você quer um desafio pra testar todo o conhecimento já visto até então... Certo! Quero ver
        você resolver alguns exercícios um pouco mais complexos, a começar pelo nível 1. Você pode me enviar
        a submissão por aqui mesmo, que te retornarei um feedback! Aqui está o exercício:

        NÍVEL 1: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=79&page=show_problem&problem=2030%60

        Tambéem não se esqueça de continuar sua carreira de desenvolvedor python me perguntando sobre vetores!
```

  utter_desafio_vetores:
```
    - text: |
        Béem vamos dificultar um pouco mais!! Quero ver você conseguir fazer essa questão aqui, lembrando que é
        apenas o nível 1!! Você pode me mandar a submissão que eu te digo se está certo! Lá vamos nós:

        NÍVEL 1: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=829&page=show_problem&problem=4459

        Você está evoluindo rápido! Se preferir podemos seguir pro próximo conteúdo sugerido: matrizes. É só perguntar o que são matrizes que te explico.
```

  utter_desafio_matrizes:
```
      - text: |
          Agora que você já fez os exercícios mais fáceis, vou te dar alguns desafios... Vamos começar pelo nível 1!
          Posso receber a sua submissão e te dizer se está certo ou não! Vamos nessa!

          NÍVEL 1: https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=2201

          Para submeter o seu código é necessário entrar em uma conta do juiz online UVA. Para entrar é só pedir.
          Bée..Se seu pedido tiver essas palavras me ajudaria bastante a te entender: login uva, conectar no uva
          Não se preocupe se ainda não tem uma conta, te ensino rapidinho, é só pedir pra se conectar.

          Eai, resposta correta, né? Agora que você aprendeu 100% sobre matrizes, me peça, que te explico sobre como importar bibliotecas!

```
  utter_desafio_hello_world:
```
    - text: |
        Vamos praticar o que foi ensinado agora, com um desafio! Você pode me mandar sua resposta que te direi se
        está certo ou não! Começaremos com o nível 1:

        NÍVEL 1: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=817&page=show_problem&problem=3922

        Já podemos seguir pro próximo conteúdo sugerido, meu pequeno júpiter: Estruturas condicionais. É só perguntar o que são estruturas condicionais que eu te explico.
```

  utter_desafio_funcao:
```
    - text: |
        Agora vamos testar em problemas mais complexos! Vamos ter problemas de vários níveis...
        Começando pelo nível 1, você pode me mandar seu código para eu te dar um feedback! Vamos tentar?

        NÍVEL 1: https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=233&page=show_problem&problem=1862

        Para submeter o seu código é necessário entrar em uma conta do juiz online UVA. Para entrar é só pedir.
        Se seu pedido tiver essas palavras me ajudaria bastante a te entender: login uva, conectar no uva
        Não se preocupe se ainda não tem uma conta, é só pedir para se conectar que te ensino ;)
```

  utter_desafio_input_dados:
```
    - text: |
          Que tal um desafio sobre importar dados?
          Faça o um programinha em python que pega uma string NOME, um int IDADE e um double MEDIA_ESCOLAR.
          Depois printe tudo formatando do jeito que quiser!

          Caso queira o gabarito para conferir, me peça o código python em python de input de dados!
```

**Comment by heylisten64** [comment]
Vou realizar a tradução dos exercícios que temos por enquanto, você pode tentar procurar exercícios para os conteúdos que ficaram faltando?

e não sei se vale deixar a utter de input como desafio, acho que seria melhor deixa-la como exercícios já q o topico de desafio é pra exercícios do UVA que acharmos!

exercícios que estarei traduzindo e passando pra outro pdf:

- [x] [repetição](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=79&page=show_problem&problem=2030%60)
- [x] [vetores](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=829&page=show_problem&problem=4459)
- [x] [matrizes](https://uva.onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=2201)
- [x] [hello_world](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=817&page=show_problem&problem=3922)
- [x] [função](https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=233&page=show_problem&problem=1862)

**Comment by gustable42** [comment]
Encontrei até agora dois exercícios sobre variáveis sem uso de laços de repetições:
- https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=94&page=show_problem&problem=996
- https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=94&page=show_problem&problem=1012

E um com condicionais:
- https://uva.onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=94&page=show_problem&problem=635
