### ISSUE TITLE
Refatoração de intents e utters do bot de acordo com feedback dos usuários

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#348]
Refatoração de intents do bot, conforme o feedback dos usuários.

**Tarefas**

- [x] Evoluir arquivo de intents
- [x] Evoluir arquivo das utters

**Critérios de aceitação**

- [x] Bot se comunicando bem por meio de diversos tipos de entrada do usuário
- [x] Bot transmitindo o conteúdo de forma objetiva e sucinta

**Comment by heylisten64** [comment]
Irei listando os erros encontrados durante a sprint!

1. intents de conteudos inapropriados
![image](https://user-images.githubusercontent.com/43069991/58385635-c0203100-7fc9-11e9-9d56-448d541ff03e.png)

**Comment by heylisten64** [comment]
vamos refatorar as intents dos seguintes arquivos:

codigo em python
conteudo extra
desafio
exemplo
exercicio
main
sobre

A divisão fica a seu critério @gustable42

**Comment by heylisten64** [comment]
nos comentários da issue #222 eu explico bem como fazer pra evoluir as intents.
eu sugiro usar o [sinonimos](https://www.sinonimos.com.br/) também pra algumas palavras
por exemplo

crio a intent pra utter de exercícios de variaveis: quero um exercício sobre variaveis
procuro no site um sinonimo de exercicios, como tarefas etc
adiciono mais uma intent: quero uma tarefa de variaveis

evitar pronomes também é muito importante... deixar a sentença com as palavras chaves apenas!

**Comment by heylisten64** [comment]
> Amigos, na hora da criação da intent, eu tava conversando com o @Andreabenf , peço que façam desse modo para que mantenhamos o padrão e não precisemos ficar refatorando as intents. Sigam o passo a passo e dará tudo certo:
> 
> escolham palavras chaves (já escolhemos algumas para cada arquivo)
> implementem nas palavras chaves o conteúdo
> diferenciem acentuações
> EVITEM AO MÁXIMO pronomes e frases com muito frufru, coloque apenas a parte essencial da frase para ela entrar na utter
> vale a pena dar uma olhada no conteúdo refatorado por mim e pelo andré, pra tomar base para outras issues!

**Comment by gustable42** [comment]
Massa!! Vou ficar com codigo em python, conteudo extra, desafio, exemplo

**Comment by heylisten64** [comment]
certo, então refatorarei os conteudos dos arquivos **exercicio**, **main**, **sobre**!

**Comment by heylisten64** [comment]
Sugiro montar uma intent padrão pra cada topico e ir conectando com os temas :+1: 
e no final treinar o bot e testar todas (ou quase todas) as intents criadas (é trabalhoso mas paciência x.x)
e pras intents que tem poucos exemplos, tentar incluir o máximo possível

**Comment by heylisten64** [comment]
e pras intents que tem poucos exemplos, tentar incluir o máximo possível

**Comment by heylisten64** [comment]
quanto a feedbacks de utters, temos dois requisitos levando o feedback em consideração:

> Visto isso, é importante ressaltar que a Aix faz muitas perguntas dentro da explicação (mesmo retóricas)
> Não sei se tem como por "enter" nas mensagens,

**Comment by heylisten64** [comment]
A refatoração nas utters ficará em pendencia, devido as grandes alterações feitas em outras issues, dariam problemas maiores de conflitos!

**Comment by heylisten64** [comment]
As intents nos arquivos: actions, conteudos vagos, uva.
não foram alteradas por acreditarmos estarem instáveis demais.

**Comment by heylisten64** [comment]
> Irei listando os erros encontrados durante a sprint!
> 
> 1. intents de conteudos inapropriados
>    ![image](https://user-images.githubusercontent.com/43069991/58385635-c0203100-7fc9-11e9-9d56-448d541ff03e.png)

![Captura de tela de 2019-06-02 13-18-06](https://user-images.githubusercontent.com/43069991/58764041-f36a3f00-8538-11e9-8a5c-9c67017e0ad2.png)

**Comment by heylisten64** [comment]
![Captura de tela de 2019-06-02 13-19-17](https://user-images.githubusercontent.com/43069991/58764046-0b41c300-8539-11e9-9db5-e595e86345e2.png)
