### ISSUE TITLE
Configurar github pages 

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#36]
Configurar página do Github Pages do Grupo Aix
 * Tarefas
- [x] Organizar estilo da página com a identidade visual criada 
- [x] criar paginas para cada documento inserido a fim de dividir os tipos de documentos 

 * Critérios de aceitação
- [x] Github Page e configurado

**Comment by GuiMarques98** [comment]
Usarei o [Jerkyll](https://jekyllrb.com/) para fazer o _GH Pages_.

**Comment by GuiMarques98** [comment]
Existe um pequeno problema na implementação de imagens portanto é necessário colocar as imagens no `assets/img/` e para a imagem funcionar no _gp pages_ colocar o seguinte código:

`
{{ site.url }}/assets/img/<nome do arquivo>
`
