### ISSUE TITLE
Contribuir para o travis

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#369]
Contribuir para o **nosso** Travis, com um código capaz de observar a má formatação da domain que impede o treinamento do bot.

**Tarefas**

- [x]  Elaboração de um código capaz de visualizar a formatação da domain.

**Critérios de aceitação**

- [x]  Código capaz de encontrar erros de formatação da domain.
- [x]  Código implementado no Travis.

**Comment by pedroeagle** [comment]
Adicionei um código que procura pela declaração de intents, actions e utters e a definição de utters na nossa domain.yml. como alguns conteudos fogem do padrão criei também uma lista de excessões para evitar problemas. a ideia inicial é que o código procure por definições de utters que não possuem declaração de intents e utters e logo após intents que não possuem utters correspondentes e vice-versa, evitando assim quebrar o bot após um longo período de treinamento.

**Comment by Yoshida-Eduardo** [comment]
Quando forem adicionar o script ao travis ou se tiverem qualquer dúvida me chamem

**Comment by pedroeagle** [comment]
Estudei um pouco mais sobre como 'compilar' nossa domain e acredito que interpretá-la como uma gramática livre de contexto pode ser o mais adequado. Iniciei o código para que isso seja feito, estou apenas tendo um problema na detecção perfeita de um text.
