### ISSUE TITLE
Estudo de viabilidade de agenda

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#370]
Pesquisar o funcionamento do banco de dados do Rasa e, se possível, aplicar a funcionalidade de agenda dentro do cronograma de estudos.

**Tarefas**

- [x]  Entender como funciona o banco de dados do Rasa e documentar em um material de estudo.
- [x] Verificar a possibilidade de adequar o banco de dados para uma nova funcionalidade.

**Critérios de aceitação**

- [x]  Criação do material de estudos, levantando todo o conteúdo verificado durante a sprint.
- [x]  Verificação, com base no que foi levantado da possibilidade da nova funcionalidade.

**Comment by Andreabenf** [comment]
Ao invés de um banco de dados, estive pensando em mexer com uma spreadsheet do google drive.
Já existe uma Api para python que consegue mexer com os dados das células facilmente

**Comment by Andreabenf** [comment]
Seria um método eficiente, fácil e gratuito nesse inicio

**Comment by Andreabenf** [comment]
Foi deste video que tirei essa ideia:
https://www.youtube.com/watch?v=cnPlKLEGR7E

**Comment by Andreabenf** [comment]
usariamos slots para gravar os usernames(que devem ser unicos) e as tarefas a serem feitas.
Assim, poderiamos subir para o spreadsheets os dados

**Comment by heylisten64** [comment]
achei a ideia boa, mas algumas coisas preciso que você me esclareça. 
falarei contigo na daily!

**Comment by Andreabenf** [comment]
# Estudo Agenda 
## (Manter Tracking do que o aluno ja viu)

 ### A ideia é que cada aluno informe um username e uma senha para gente. Deste modo, podemos facilmente mapear uma coluna inteira no spreadsheets do google para este usuário.


### Cada linha será um conteúdo que o Bot oferece para ensinar.

### Ao final e começo de cada conteúdo, o bot pode perguntar se o aluno ja se sente confiante em tal conteúdo. Caso sim, colocamos 1 (na linha do conteudo X coluna do aluno).

### Deste modo, podemos listar os conteúdos não vistos ou não aprendidos completamente.
### A validação seria justamente o user e a senha criados pelo aluno.
