### ISSUE TITLE
Refatorar conteúdo de stories

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#373]
Refatorar o arquivo de stories mantendo coerência com o novo fluxograma criado.

**Tarefas**

- [x]  Refatoração do conteúdo de stories

**Critérios de aceitação**

- [x]  Stories adequadas ao novo fluxograma.
- [x]  Bot se comunicando bem por meio de diversos tipos de entrada do usuário.

**Comment by heylisten64** [comment]
![image](https://user-images.githubusercontent.com/43069991/58765254-84481700-8547-11e9-83af-5f474fc712d7.png)
https://www.draw.io/#G1POlRP3zxJ3c9anUbGIPn--3R2TkAZLAK dei a permissão pra vocês alterarem qualquer coisa, mas lembrando que é esse o fluxo que escolhemos quando fomos alterar o fluxo de indução nas utters! ;) 
qualquer dúvida, é só perguntar! o @gustable42 e o @pedroeagle elaboraram junto comigo o fluxo, então algumas coisas eles tem um conhecimento bom!

**Comment by pedroeagle** [comment]
# Fluxo atualizado:
![image](https://user-images.githubusercontent.com/45996980/58893350-589f6b00-86c6-11e9-956d-83850fe62391.png)
