### ISSUE TITLE
Refatorar utters 

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#375]
Refatorar conteúdos afim de torná-los compactos e objetivos para o usuário, atendendo ao feedback do usuário: com quebras de linhas e diminuição de perguntas retóricas.

**Tarefas**

- [x]   Refatorar templates.

**Critérios de aceitação**

- [x]  Moderação de perguntas retóricas.
- [x]  Maior quantidade de quebras de linhas.
- [x]  Conteúdo resumido ao máximo possível, conservando sua objetividade.

**Comment by Andreabenf** [comment]
Gabi, ja fiz bastante alterações.
Dá uma olhada aí, e vê o que você acha ainda interessante mudar
