### ISSUE TITLE
Estudo de alternativas de mensageiros 

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#376]
Pesquisar alternativas de mensageiros para que o problema com o rocketchat de não suportar funções como imagens e botões seja solucionado.

**Tarefas**

- [x]  Pesquisar opções de mensageiros que possam contornar o problema visto até então.
- [x] Documentar a pesquisa, levantando os prós e contras de outros mensageiros.

**Critérios de aceitação**

- [x]  Documentação da pesquisa.
- [x]  Conclusão de alteração.

**Comment by iurisevero** [comment]
Estava pesquisando por outros mensageiros e encontrei dois que pareciam boas opções.
O [Zílio](https://zulipchat.com/), que é um mensageiro open source com diversas ferramentas e integrações já prontas, além de possuir uma  [REST API](https://zulipchat.com/api/rest) bem documentada.
A segunda opção seria o [Slack](https://slack.com/intl/pt-br/apps), ele se encaixa nos requisitos necessários e também possui uma [API](https://api.slack.com/) bem documentada, apesar de ser menos direta que a do Zulip.
Por fim, eu também estava olhando as funções disponíveis pelo [RocketChat](https://rocket.chat/) e, após analisá-las,  reparei que ele possui diversas funções que não chegamos a explorar, que podem ser vistas em sua [API](https://rocket.chat/docs/developer-guides/rest-api/).

Apesar das outras opções serem muito boas, devido ao nosso espaço de tempo até a entrega do projeto, acredito que a viabilidade de implementar um novo mensageiro seja falsa,  porém é algo que poderia ficar em aberto, para avaliarmos após o fim do semestre, tanto a possibilidade de trocar totalmente o RocketChat quanto a implementação de novas funcionalidades no mesmo.

**Comment by Lucas362** [comment]
Excelente trabalho, acredito que um estudo mais aprofundado na API do Rocketchat possa vir a ser de grande valia para o produto. No mais, a issue já cumpriu com seu dever, ela será fechada no momento :+1:

**Comment by pedroeagle** [comment]
as opções listadas realmente são ótimas mas pra daqui 3 semanas se torna inviável. talvez, se estivéssemos no início do projeto teríamos essa maior liberdade de escolha. se algum dia o projeto for continuado após a disciplina de mds essas opções tornam-se viáveis e capazes de melhorar ainda mais nosso bot.

**Comment by pedroeagle** [comment]
entre as funcionalidades da API do RocketChat vc encontrou alguma que se encaixe em formatar texto ou algo que estejamos precisando?

**Comment by heylisten64** [comment]
Seria legal listar aqui as funcionalidades que poderíamos utilizar no nosso projeto encontradas na API do Rocketchat, e se der dos outros mensageiros também! 
E se tiver achado alguma solução pra suportar imagem no rocketchat, essa teria caráter emergencial pro nosso projeto, porque tinhamos nos comprometido a arrumar essa parte

**Comment by iurisevero** [comment]
> Seria legal listar aqui as funcionalidades que poderíamos utilizar no nosso projeto encontradas na API do Rocketchat, e se der dos outros mensageiros também!
> E se tiver achado alguma solução pra suportar imagem no rocketchat, essa teria caráter emergencial pro nosso projeto, porque tinhamos nos comprometido a arrumar essa parte

Gabi, acredito que a parte de [import](https://rocket.chat/docs/administrator-guides/import/) resolva nosso problema, porém ficaríamos naquela de ter que ajustar pra uma mensagem diferente pro telegram e outra pro rocketchat :/
