### ISSUE TITLE
Criar identidade visual

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#38]
Criar identidade Visual para o bot Aix
 * Tarefas
- [x] Criar arte
- [x] Documento explicando a escolha feita.

 * Critérios de aceitação
- [x] A arte deve estar disponível para uso em ícone, banner...
- [x] Links e imagens disponíveis na issue e gitHub Pages

**Comment by iurisevero** [comment]
@heylisten64 vou pesquisar documentos de identidade visual para ter uma ideia de como fazer o nosso. 
Qualquer ideia de como ela será me avisa! Posso tentar ajudar a criar também

**Comment by heylisten64** [comment]
Então, eu tinha pensado em adotar como mascote do projeto a coruja, por ter relação com sabedoria/inteligência, até que é assim que se representa as deusas Atena e Minerva nas mitologias grega/romana. E tem a questão também de na cadeia alimentar a coruja estar um nível acima da cobra (python), representando um sinal de dominação... estou aberta a sugestão, caso tenha outra também, comenta aqui, pra desenvolvermos o significado e realizar os esboços antes de passar pra um software...

**Comment by heylisten64** [comment]
assim que levantarmos um esboço que agrade a equipe, eu já tento passar pro illustrator, por isso precisamos acelerar esse primeiro processo, pq a parte do illustrator pode ser mais demorada e precisamos agilizar para passar o resultado daqui pra outra issue...

**Comment by iurisevero** [comment]
> Então, eu tinha pensado em adotar como mascote do projeto a coruja, por ter relação com sabedoria/inteligência, até que é assim que se representa as deusas Atena e Minerva nas mitologias grega/romana. E tem a questão também de na cadeia alimentar a coruja estar um nível acima da cobra (python), representando um sinal de dominação... estou aberta a sugestão, caso tenha outra também, comenta aqui, pra desenvolvermos o significado e realizar os esboços antes de passar pra um software...

Acredito que seria melhor manter a cabra, como a @KahCosta havia sugerido, acredito que seja o mascote que a maioria do grupo irá preferir, podemos fazer uma votação na próxima Daily.
Lembrando que essa escolha se baseia na cabra Aix que, na mitologia greco-romana, alimentou Júpiter/Zeus quando o mesmo foi deixado na Terra e isso permitiu que ele sobrevivesse.

**Comment by heylisten64** [comment]
boa! decidimos na daily então!

**Comment by iurisevero** [comment]
Pensando nos outros detalhes, acho que seria interessante usarmos tons de laranja e cinza, assim como o Projeto Jupyter, já que nosso projeto funcionará em conjunto com ele.
Outra opção seria fazer o oposto e pegar cores que contrastem com as citadas.

**Comment by heylisten64** [comment]
acho uma boa! só precisamos saber se essa paleta caberá no esboço que vamos levantar 👍

**Comment by iurisevero** [comment]
Dei uma pesquisada e consegui as cores da logo do Jupyter
![Captura de tela de 2019-03-31 18-36-02](https://user-images.githubusercontent.com/42645264/55295485-f71c0100-53e3-11e9-8073-df503a10a249.png)

**Comment by iurisevero** [comment]
> Dei uma pesquisada e consegui as cores da logo do Jupyter
> ![Captura de tela de 2019-03-31 18-36-02](https://user-images.githubusercontent.com/42645264/55295485-f71c0100-53e3-11e9-8073-df503a10a249.png)

A partir daqui já dá para ter uma ideia das cores que fariam contraste também

**Comment by heylisten64** [comment]
abri um drive pra organizarmos tudo que for coletado, segue o link: https://drive.google.com/drive/folders/1WDhPOzsnz3fAMhH4I8O7ERDA2is6fkLy

**Comment by iurisevero** [comment]
Estou usando os seguintes exemplos de documentos de identidade visual como base para o nosso:
https://botlino.github.io/docs/doc-identidade-visual
https://dulce-work-schedule.github.io/especificacao/identidade_visual.html
https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/idVisual

Achei interessante que o documento do Kalkuli tem tópicos diferentes dos outros dois

**Comment by iurisevero** [comment]
> boa! decidimos na daily então!

Como ficou decidido na reunião, vamos seguir a ideia da cabra Aix mesmo e a partir daí montar a identidade visual do nosso bot.

**Comment by iurisevero** [comment]
Para tipografia da logo, estava olhando o [Google Fonts](https://fonts.google.com/) e gostei bastante da fonte [Roboto Slab](https://fonts.google.com/specimen/Roboto+Slab), poderíamos usar ela no formato Bold pro nome "Aix" na logo e para títulos no site e podemos usar a [Robot0](https://fonts.google.com/specimen/Roboto), em sua forma regular, para os textos gerais e a [Roboto Slab](https://fonts.google.com/specimen/Roboto+Slab), também na forma regular, para destacar palavras no texto.
O que acha @heylisten64 ?

**Comment by heylisten64** [comment]
Gostei da sugestão!

**Comment by iurisevero** [comment]
@heylisten64 
Então vamos fechar a cor no laranja, cinza escuro, vou tentar pegar um cinza claro pra ficar de fundo nos textos e aí já passo para o @GuiMarques98, certo?
Aí a cores usadas para colorir a logo eu adiciono na paleta depois.

**Comment by heylisten64** [comment]
de acordo!

**Comment by heylisten64** [comment]
![3a5da90f-a6d3-4b30-9ca1-d20355461839](https://user-images.githubusercontent.com/43069991/55585156-6489a380-56fc-11e9-9354-470b1d2d7701.jpg)
a elaboração da arte no papel, pra vocês ficarem a parte do processo desde o começo! essa imagem seria pro banner, pra colocar no site etc

**Comment by heylisten64** [comment]
![criação](https://user-images.githubusercontent.com/43069991/55585230-94d14200-56fc-11e9-8bd7-531c9c33c20d.png)
o processo de criação no software que desenvolvi hoje mais cedo!

**Comment by heylisten64** [comment]
ainda está em andamento!

**Comment by heylisten64** [comment]
tive um pequeno problema com a ferramenta illustrator e tive que baixar de novo, isso me atrasou um pouco, mas segue o esboço da logo: 
![image](https://user-images.githubusercontent.com/43069991/55600075-f6ab9f00-5730-11e9-8f01-8bfb68b5f283.png)
