### ISSUE TITLE
Implementação do CustomFormAction

### ISSUE THREAD

**Issue by iurisevero** [fga-eps-mds/2019.1-Grupo-1#380]
Implementar um FormAction adaptado as alterações necessárias para o projeto.

**Tarefas**

- [x] Implementar o CustonFormAction a partir do estudo realizado

**Critérios de aceitação**

- [x] Bot ser capaz de recolher o texto do usuário ao invés de tentar extrair o Slot
- [x] Bot retornar mensagem customizada ao não conseguir extrair o texto

**Comment by KahCosta** [comment]
Bot capaz de 
- realizar login
- submeter arquivos
- dar feedback do exercicio
