### ISSUE TITLE
Personalidade do bot

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#39]
Elaborar documento de estudo e criação de persona.
 * Tarefas
- [x] Criar persona
- [x] Escolher categoria do bot
- [x] Criar documento explicando persona e categoria do bot 

 * Critérios de aceitação
- [x] Documento disponível no github Pages 
- [x] Link disponível na issue

**Comment by Andreabenf** [comment]
Galera, criei uma branch para começarmos o trabalho dessa issue

**Comment by Andreabenf** [comment]
Estou usando como base o conhecimento levantado pelo pessoal da lappis na construção do bot deles (Tais)
https://github.com/lappis-unb/tais/wiki/Estudo-sobre-melhores-pr%C3%A1ticas-de-bots
