### ISSUE TITLE
Criar e documentar Folha de Estilo

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#40]
Criar folha de estilo para apoio e padronização ao desenvolvimento do projeto

**Tarefas**

- [x] Criar documento referente a folha de estilo

**Critérios de aceitação**

- [x] Documentar no github Pages
- [x] Link do documento disponível na issue

**Comment by Lucas362** [comment]
Para programação em Python, será utilizada o guia de estilo padrão PEP8, com algumas alterações que se adequam melhor ao contexto da equipe.

**Comment by Lucas362** [comment]
Folha de estilo criada, lembrando que ela pode ser alterada desde que seja devidamente acordado pelo grupo como um todo (ou uma grande maioria)
