### ISSUE TITLE
Configurar Releases do projeto corretamente

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#402]
Criar releases de acordo com entregas para conseguir visualizar andamento do projeto por meio da ferramenta do github `Release Report`

**Tarefas**

- [ ] Criar releases
- [ ] Especificar Release
- [ ] Criar Tag de Release
- [ ] Linkar release as issues

**Critérios de aceitação**

- [ ] Release criada
- [ ] Possibilidade de análise de andamento de release por meio da ferramenta `Release Report`

**Comment by Lucas362** [comment]
Como todos de EPS foram marcados para esta tarefa, como ficará a divisão de tarefas?

**Comment by Lucas362** [comment]
Como não houve divisão do trabalho, acabei por realizá-lo por completo
