### ISSUE TITLE
Refatorar Arquivos de Actions (Issue Not Found) :)

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#404]
Refatorar Arquivo action.py
**Tarefas**

- [x] Dividir classes do arquivo Actions.py em novos arquivos de customAction
- [x] Formatar linguagem do código
- [x] Acrescentar validação de requests
- [x] Atualizar os testes a partir das alterações feita

**Critérios de aceitação**

- [x] Classes e funções estarem divididas em novos arquivos com conteúdos similares
- [x] CustomActions continuarem funcionando no bot
- [x] Testes unitários continuarem com a cobertura atual

**Comment by iurisevero** [comment]
Estava olhando os códigos e vi que também falta validar as tentativas de request. Irei implementar essas validações durante a refatoração e atualizarei os testes respectivos as variações que ocorrerem.

**Comment by iurisevero** [comment]
> Estava olhando os códigos e vi que também falta validar as tentativas de request. Irei implementar essas validações durante a refatoração e atualizarei os testes respectivos as variações que ocorrerem.

Devido a adição de tarefas na issue, sua pontuação também será atualizada
