### ISSUE TITLE
Aumentar cobertura de teste

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#405]
Refatorar testes unitários a fim de aumentar a cobertura de testes.

**Tarefas**

- [x] Testar API UVA
- [x] Testar StackOverflow

**Critérios de aceitação**

- [x] Aumento na cobertura de testes da Aix

**Comment by iurisevero** [comment]
[Rasa SDK](https://github.com/RasaHQ/rasa-sdk/tree/0.13.1/rasa_core_sdk)
[Tracker](https://github.com/RasaHQ/rasa-sdk/blob/0.13.1/rasa_core_sdk/__init__.py)
