### ISSUE TITLE
Refatoração de direcionamentos

### ISSUE THREAD

**Issue by heylisten64** [fga-eps-mds/2019.1-Grupo-1#407]
Refatorar stories e intents, visando um melhor funcionamento do nosso bot, observando erros de interpretação do nosso bot.

**Tarefas**

- [x] Observar erros de direcionamento do bot.
- [x] Refatorar stories.
- [x] Refatorar intents.

**Critérios de aceitação**

- [x] Bot se comunicando bem por meio de diversos tipos de entrada do usuário.

**Comment by gustable42** [comment]
Problemas ao pedir como instalar o python e quando aciona as custom actions de conteúdo vago de links extras

**Comment by gustable42** [comment]
Ainda estou mapeando erros de direcionamento

**Comment by iurisevero** [comment]
Farei as alterações baseado no fluxo de utters que a @heylisten64 fez.
https://www.draw.io/#G1POlRP3zxJ3c9anUbGIPn--3R2TkAZLAK
![](https://user-images.githubusercontent.com/42645264/59639977-1993ff80-9133-11e9-85fc-2ffa497bb17a.png)
