### ISSUE TITLE
Refatorar analisador da domain

### ISSUE THREAD

**Issue by pedroeagle** [fga-eps-mds/2019.1-Grupo-1#408]
Na sprint passada foi feito um analisador da domain.yml com o objetivo de procurar por erros de sintaxe na domain e assim evitar que o bot seja quebrado. Alguns problemas foram encontrados ao analisar os textos das utters sendo necessário trocar a estrutura geral de textos da domain. Esta refatoração deve conseguir analisar a domain refatorada na issue #401 .

**Tarefas**

- [x] Refatorar o arquivo bot/comp.py

**Critérios de aceitação**

- [x] A refatoração deve ser compatível com a nova domain da issue #401 .
- [x] Se tudo estiver funcionando perfeitamente o analisador deve ser incluso no Travis.

**Comment by pedroeagle** [comment]
Mostrei o analisador para o Fábio (professor de compiladores) e ele falou que era realmente uma boa ideia para evitar problemas mas que não seria necessária implementação, que já existe bibliotecas nativas que fazem essa tarefa. Pesquisando um pouco sobre isso encontrei a [PyYAML](https://github.com/yaml/pyyaml/) que promete essa tarefa. Farei alguns testes nisso.

**Comment by pedroeagle** [comment]
## Um exemplo de utilidade do analisador:
Digamos que um novo conteúdo foi inserido e a pessoa que criou uma nova utter se esqueceu de colocar ':' após o nome da utter como na imagem:
![image](https://user-images.githubusercontent.com/45996980/59316853-d64f1200-8c96-11e9-9c38-0e4938f4c7c4.png)

O analisador "compila" a domain.yml retornando 0 caso não encontre problemas e retornando 1 juntamente com a correção a ser feita como na imagem:
![image](https://user-images.githubusercontent.com/45996980/59316935-32199b00-8c97-11e9-838b-7c4d8ec47e86.png)

A descrição do erro é detalhada dizendo até mesmo que um ':' era esperado na linha 191.

**Comment by Yoshida-Eduardo** [comment]
Parabéns @pedroeagle, dei uma olhada aqui e fiz alguns testes, o código foi consistente em localizar erros e identificar quando o arquivo estava correto. A implementação está bem mais limpa que a versão passada também.

**Comment by Yoshida-Eduardo** [comment]
Eu e o @pedroeagle pareamos para adicionar o comparador ao travis, testamos casos de erro e sucesso, tudo ocorreu corretamente conforme o esperado.
