### ISSUE TITLE
Deploy de ambiente para testes

### ISSUE THREAD

**Issue by Yoshida-Eduardo** [fga-eps-mds/2019.1-Grupo-1#410]
Para evitar que haja o envio de imagens quebradas para o ambiente de deploy(que ocorreu algumas sprints atrás), torna-se interessante um ambiente de testes a partir da devel.  Além de permitir que os desenvolvedores encontrem e corrijam bugs antes que cheguem a produção.

Como o objetivo do ambiente é apenas homologação do bot em si(core, nlu e actions) e dado o elevado custo de manter toda a stack do bot(rocket, jupyter, etc), optou-se por adicionar somente uma instância para o telegram, o que elimina boa parte do peso da stack.

**Tarefas**

- [ ] Obter um token com o botfather
- [ ] Adicionar o environment no rancher
- [ ] Adicionar instância do bot para telegram que receberá o deploy a partir da branch devel
- [ ] Configurar o Travis para deploy contínuo do ambiente de testes

**Critérios de aceitação**

- [ ] Deve haver uma instância do bot no telegram a partir da branch devel

**Comment by Yoshida-Eduardo** [comment]
Em discussão com @Lucas362 e @GuiMarques98 optou-se pela não realização da issue.

Até o momento, dado o elevado custo computacional e tempo necessário, era inviável testar o funcionamento do treinamento do bot na ferramenta de CI. O que, por vezes, ocasionou no deploy de imagens quebradas(erros na domain que impossibilitavam o treinamento do bot) em nosso ambiente de homologação, entretanto, com a conclusão de #408 e após alguns testes realizados no analisador por ela implementado, torna-se possível realizar uma validação da domain na ferramenta de CI para garantir que o treinamento do bot seja viável.

Como o objetivo dessa issue era apenas implementar um ambiente de testes para garantir que a imagem do bot não chegue quebrada(com problemas no treinamento) no ambiente de homologação, e dado seu custo de implementação, optamos por não implementá-la.

Dada a instabilidade até então observada nas imagens, por conta de erros de treinamento, que esperamos que sejam sanadas com a implementação de #408, o deploy era mantido a partir da branch master. Com a implementação do analisador da domain, tornou-se possível garantir uma maior segurança em relação a estabilidade das imagens(domain válida), então optamos por atualizar o deploy para que ocorra partir da branch devel.

**Comment by Lucas362** [comment]
Tendo em mente tudo o que foi dito acima, está issue pode ser considerada concluída, graças a solução alternativa implementada, e ao fato de não possuir custo-benefício alto o suficiente para sua implementação dado o presente contexto. Issue fechada
