### ISSUE TITLE
Deploy do servidor de homologação

### ISSUE THREAD

**Issue by GuiMarques98** [fga-eps-mds/2019.1-Grupo-1#42]
Fazer o deploy do servidor de homologação no [Heroku](https://dashboard.heroku.com/).

**Tarefas**

- [x] Configurar as ferramentas de integração continua.
- [x] Configurar o Heroku para que ele consiga subir o servidor de homologação.

**Critérios de aceitação**

- [x] Servidor de homologação estar no ar no Heroku.

**Comment by GuiMarques98** [comment]
A parte de configuração depende diretamente da _issue_ #46.

**Comment by Yoshida-Eduardo** [comment]
Não foi possível concluir a issue nessa sprint devido a impedimentos relacionados a outras issues(#46), problemas de conflitos relacionados ao fork com boilerplate e incertezas relacionadas a arquitetura que estão sendo discutidas.

**Comment by Yoshida-Eduardo** [comment]
O bot agora está disponível no telegram em https://t.me/Aix_chatbodebot e também em uma instância do jupyter disponível em http://aixbot.me

Documentando o que foi feito e o processo:
Fiz o deploy do bot na Digital Ocean em uma VM com Ubuntu 18.04 e utilizei o Rancher 1.6 para orquestração dos containeres e o nginx para proxy reverso(adicionei o Dockerfile e arquivo de configuração ao repositório, mas obviamente sem os certificados). O deploy da instância do jupyter, por questões de segurança, foi realizada em outra vm e com limitação de recursos para o container do jupyter(uma vez que o jupyter permite que o usuário execute código arbitrário preferi deixar em um host diferente para não trazer riscos ao serviço do bot).  

Tive alguns problemas com o deploy do bot para telegram dada a necessidade de SSL para efetuar o webhook com a api do telegram, apenas para fins de documentação caso alguém tenha a mesma dificuldade precisei concatenar o ca-bundle ao .crt.

Foram necessários também alguns tweaks nos scripts de conexão do rocketchat com o rasa para receber a url do rasa ao invés do valor padrão setado em bot_config.py

Tentei servir a instância do jupyter e o rocketchat via https, entretanto houveram alguns problemas para estabelecer o websocket com o rocketchat e apesar da janelinha do rocketchat ser renderizada na tela o bot aparecia como offline. 
Não foi possível servir a instância do jupyter via https e a do rocketchat via http uma vez que os browsers modernos bloqueiam exibição de [conteúdo misto](https://developer.mozilla.org/pt-BR/docs/Security/MixedContent) , então optou-se continuar com o http por hora. Creio que sejam necessárias algumas mudanças nos scripts de conexão com o rocketchat para que seja possível disponibilizar o bot via https.

**Comment by Yoshida-Eduardo** [comment]
Também adicionei o script para dar push das imagens no Dockerhub, mas ele por hora está desativado. 

Como se trata de um único repositório que gera múltiplas imagens (actions e bot), será necessário definir uma estratégia para efetivação do deploy contínuo pois nem toda build necessariamente deveria gerar ambas as imagens, uma vez que nem sempre ambas as imagens seriam alteradas.

Fiz uma pesquisa sobre o tema e encontrei inicialmente duas possíveis formas de resolver esse problema:
- Realizar um pull nas imagens mais recentes do Dockerhub e utilizá-las como cache para gerar a build no travis ci, dessa forma caso não haja alteração não seria gerada uma nova imagem.
- Implementar um script quer verifica se houve alguma alteração nos diretórios de actions ou bot e gerar a nova imagem apenas se houver alguma alteração.
Realizei apenas uma pesquisa inicial, é necessário aprofundar o estudo para definir a viabilidade de cada solução e caso necessário definir novas soluções.
