### ISSUE TITLE
Refatorar Canvas

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#429]
Refatorar canvas para melhorar especificação

**Tarefas**

- [x] Refatorar tópico referente a público alvo

**Critérios de aceitação**

- [x] Canvas refatorado e atualizado na GhPages

**Comment by heylisten64** [comment]
nosso canvas atual
![image](https://user-images.githubusercontent.com/43069991/59886036-5e44b400-9348-11e9-915c-5bcb3bb39066.png)

https://www.canva.com/design/DADYw_ZtYt0/share/preview?token=90f9c9_oUKvuN4XkU8iXpg&role=EDITOR&utm_content=DADYw_ZtYt0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by heylisten64** [comment]
![image](https://user-images.githubusercontent.com/43069991/59886063-77e5fb80-9348-11e9-9131-653341d8d50d.png)
[nosso canvas atual](https://www.canva.com/design/DADYw_ZtYt0/share/preview?token=90f9c9_oUKvuN4XkU8iXpg&role=EDITOR&utm_content=DADYw_ZtYt0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)

**Comment by heylisten64** [comment]
![Canvas - Aix](https://user-images.githubusercontent.com/43069991/59886479-0c9d2900-934a-11e9-961a-4fa454084d54.png)
@KahCosta aguardo seu feedback.

**Comment by heylisten64** [comment]
Imagem adicionada em assets>img>ghpages.
