### ISSUE TITLE
Adicionar Tópico: Sobre Aix

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#43]
Inserir conteúdo para que o Bot seja capaz de explicar o que é a Aix para o usuário usuário.

**Tarefas**
- [x] Criar conteúdo
- [x] Inserir conteúdo referente a ação de explicar sobre quem e qual a função da Aix

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by KahCosta** [comment]
[Estudo sobre criação de intents eficientes](https://github.com/lappis-unb/tais/wiki/Intents-Eficientes)

**Comment by heylisten64** [comment]
Para os tópicos sobre a chatbode Aix eu levantei as seguintes possibilidades:
- Quem sou eu? (chatbode Aix) 
	> utter resume: curiosidades a respeito do sistema, significado do mascote, da logo, etc. 

- Qual meu propósito? 
	> utter resume: ensinar a linguagem de programação python de um jeito dinâmico e diferente.

- O que sou capaz de fazer? 
	> utter resume: resumo das funcionalidades (ajuda com sintaxe, respostas de dúvidas, indicação de bibliotecas, feedback da compilação).

- Quais as restrições de sistemas para me utilizar? 
	> utter resume: sistema operacional Linux, Windows ou MacOS utilizando o ambiente Jupyter, como instalar etc. 

- De onde eu vim?
	> utter resume: alunos da unb + mensagenzinha motivacional pro usuário, convidando-o para criar projetos semelhantes e assim testar suas capacidades.

**Comment by heylisten64** [comment]
Lembrando que o conteúdo acima será trabalhado mais pra frente, já que nessa sprint será cobrada apenas uma intent básica, onde trará uma espécie de resumão, como ficou decidido pra essa primeira issue de implementação.

**Comment by heylisten64** [comment]
### Sobre Aix
#### Intent:
intent_sobre_Aix
#### Utter:
utter_sobre_Aix
#### Template:
* Você ainda não me conhece?! Por onde é que você navegava esse tempo todo? Eu sou a cabra Aix e estou aqui para te auxiliar nos seus estudos e garantir sua nota 10 quando o assunto é linguagem de programação Python!

* Quer surpreender seu professor com um notão na sua avaliação? Não sabe o que fazer? Calma, que eu estou aqui para te ajudar! Posso corrigir seu código, se você quiser!

* Então você quer saber mais sobre mim? Vou te contar um segredo: sabia que eu fui criada por estudantes da Universidade de Brasília? Eu aposto que se você se esforçar e estudar muito junto comigo você tambéem será capaz de criar uma ferramenta de estudo tão maneira quanto essa!

* Aí vai uma charada: Quem é, quem é... que te ajuda com a sintaxe Python, tira suas dúvidas, e ainda corrige seus exercícios de programação? Béem, se você falou seu professor, você acertou... Mas sabia que eu também posso te ajudar com isso?

* Já vi que você não me conhece muito béem... Mas aposto que você vai gostar de mim! Inclusive, se quiser me apresentar aos seus amigos, pode falar para eles que eles precisam ter o sistema operacional Linux, Windows ou MacOS e o ambiente Jupyter instalado!

* A cabra que corrige seus códigos na hora
que tira suas dúvidas sem nenhuma demora
que está todo tempo junto com você
Essa cabra sou eu!

* Quer saber mais sobre mim? Vou te contar uma curiosidade: sabia que meu nome veio da mitologia romana? Acontece que há muito tempo atrás quem amamentou o deus Júpiter foi a cabra Aix. Por eu ter sido criada integrada nessa plataforma Jupyter, nasceu a ideia do meu nome! Quanta imaginação, não?

**Comment by heylisten64** [comment]
### Sobre Aix
#### Intent:
intent_sobre_Aix
#### Utter:
utter_sobre_Aix
#### Template:
* Você ainda não me conhece?! Por onde é que você navegava esse tempo todo? Eu sou a cabra Aix e estou aqui para te auxiliar nos seus estudos e garantir sua nota 10 quando o assunto é linguagem de programação Python!

* Quer surpreender seu professor com um notão na sua avaliação? Não sabée o que fazer? Calma, que eu estou aqui para te ajudar! Posso corrigir seu código, se você quiser!

* Então você quer saber mais sobre mim? Vou te contar um segredo: sabia que eu fui criada por estudantes da Universidade de Brasília? Eu aposto que se você se esforçar e estudar muito junto comigo você tambéem será capaz de criar uma ferramenta de estudo tão maneira quanto essa!

* Aí vai uma charada: Quem é, quem é... que te ajuda com a sintaxe Python, tira suas dúvidas, e ainda corrige seus exercícios de programação? Béem, se você falou seu professor, você acertou... Mas sabia que eu também posso te ajudar com isso?

* Já vi que você não me conhece muito béem... Mas aposto que você vai gostar de mim! Inclusive, se quiser me apresentar aos seus amigos, pode falar para eles que eles precisam ter o sistema operacional Linux, Windows ou MacOS e o ambiente Jupyter instalado!

* A cabra que corrige seus códigos na hora
que tira suas dúvidas sem nenhuma demora
que está todo tempo junto com você
Essa cabra sou eu!

* Quer saber uma curiosidade sobre mim? Sabia que meu nome veio da mitologia romana? Acontece que há muito tempo atrás quem amamentou o deus Júpiter foi a cabra Aix. Por eu ter sido criada integrada nessa plataforma Jupyter, nasceu a ideia do meu nome! Quanta imaginação, não?

**Comment by heylisten64** [comment]
### Sobre Aix

#### Intent:

intent_sobre_Aix

#### Utter:

utter_sobre_Aix

#### Template:

-   Você ainda não me conhece?! Por onde é que você navegava esse tempo todo? Eu sou a cabra Aix e estou aqui para te auxiliar nos seus estudos e garantir sua nota 10 quando o assunto é linguagem de programação Python!
    
-   Quer surpreender seu professor com um notão na sua avaliação? Não sabée o que fazer? Calma, que eu estou aqui para te ajudar! Posso corrigir seu código, se você quiser!
    
-   Então você quer saber mais sobre mim? Vou te contar um segredo: sabia que eu fui criada por estudantes da Universidade de Brasília? Eu aposto que se você se esforçar e estudar muito junto comigo você tambéem será capaz de criar uma ferramenta de estudo tão maneira quanto essa!
    
-   Aí vai uma charada: Quem é, quem é... que te ajuda com a sintaxe Python, tira suas dúvidas, e ainda corrige seus exercícios de programação? Béem, se você falou seu professor, você acertou... Mas sabia que eu também posso te ajudar com isso?
    
-   Já vi que você não me conhece muito béem... Mas aposto que você vai gostar de mim! Inclusive, se quiser me apresentar aos seus amigos, fala para eles que eles precisam ter um desses sistema operacionais: Linux, Windows ou MacOS. E não esqueça, você tambéem precisa do ambiente Jupyter instalado!
    
-   A cabra que corrige seus códigos na hora  
    que tira suas dúvidas sem nenhuma demora  
    que está todo tempo junto com você  
    Essa cabra sou eu!
    
-   Quer saber uma curiosidade sobre mim? Sabia que meu nome veio da mitologia romana? Acontece que há muito tempo atrás quem amamentou o deus Júpiter foi a cabra Aix. Por eu ter sido criada integrada nessa plataforma Jupyter, nasceu a ideia do meu nome! Quanta imaginação, não?
