### ISSUE TITLE
Refatorar backlog 

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#430]
Refatorar Backlog com a adição da feature referente a implementação do UVA

**Tarefas**

- [ ] Adicionar historias de usuário referente as issues realizadas para a implementação do UVA

**Critérios de aceitação**

- [ ] Backlog atualizado com nova funcionalidade

**Comment by Lucas362** [comment]
As US referentes ao login, envio de exercícios e feedback do UVA já estão presentes no backlog, falta algo para considerar a tarefa concluída?

**Comment by Lucas362** [comment]
Após analisar a situação juntamente com a P.O (@KahCosta ) chegamos à conclusão de que a tarefa pode ser considerada finalizada em seu estado atual
