### ISSUE TITLE
Refatorar intents do /help

### ISSUE THREAD

**Issue by pedroeagle** [fga-eps-mds/2019.1-Grupo-1#439]
Ao solicitar as capacidade do bot ele está retornando como pedir conteúdo. Deve retornar o que pode fazer.

**Tarefas**

- [x] Mandar para o /help caso seja perguntado "o que você pode fazer","o que você é capaz","qual seu nome", "qual seu objetivo".

**Critérios de aceitação**

- [x] O bot deve mandar para o /help ao ser perguntado as funcionalidades.

**Comment by iurisevero** [comment]
Após analisar as utters do /help e do menu ajuda, achei melhor fazer ajustes nelas ao invés de nas intents, visto que o problema foi gerado pelo fato no menu ajuda não estar explicando o que deveria.
