### ISSUE TITLE
Adicionar Tópico: Menu ajuda

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#44]
Inserir conteúdo para que o Bot seja capaz de explicar o menu de ajuda pode oferecer ao usuário.

**Tarefas**
- [x] Criar conteúdo
- [x] Inserir conteúdo referente a ação de explicar o que pode oferecer ao usuário.

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by KahCosta** [comment]
[Estudo sobre criação de intents eficientes](https://github.com/lappis-unb/tais/wiki/Intents-Eficientes)

**Comment by Andreabenf** [comment]
# Menu de ajuda

### Intent:

    intent_menu_ajuda

### Utter:

    utter_menu_ajuda

### Template:
        Eu sou uma cabra béem inteligente e posso te ajudar com muitas coisas!
        Você pode me perguntar tudo sobre essa maravilhosa cobrinha que chamamos de Python!
        Você pode mandar seus códigos! Assim eu posso corrigir eles, te aconselhar alguma Biblioteca legal, explicar onde o quê você errou
        Tem alguma dúvida sobre alguma função da linguagem? Pode perguntar também! Te ajudo na sintaxe e tudo mais. Hahaha!
        Poxa, você pode até achar que eu não expliquei muito béem. Não tem problema. Eu te mando um link que te explica melhor!
        Além disso tudo, que te ajudo no dever de casa! Hahahaha! Só me mandar o exercício e o seu código que eu corrijo!
        É só perguntar! Sou uma Cabra mas eu não mordo.
