### ISSUE TITLE
Refatorar intents

### ISSUE THREAD

**Issue by pedroeagle** [fga-eps-mds/2019.1-Grupo-1#445]
Alguns usuários não conseguiram chegar ao contéudo de strings e funções. Seria bom analisar as outras intents também.

**Tarefas**

- [x] Refatorar intents.

**Critérios de aceitação**

- [x] O bot deve ser capaz de reconhecer melhor o conteúdo solicitado.

**Comment by iurisevero** [comment]
@pedroeagle e eu testamos o bot durante toda sprint e verificamos as intents. Tudo parece estar funcionando corretamente, visto as alterações feitas sprint passada e nas outras issues dessa sprint, e, devido a isso, a issue será fechada.

**Comment by Lucas362** [comment]
Excelente trabalho!Tendo isso em mente vou fechar a issue
