### ISSUE TITLE
Adicionar Tópico: Despedir

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#45]
Inserir conteúdo para que o Bot seja capaz de se despedir do usuário.

**Tarefas**
- [x] Criar conteúdo
- [x] Inserir conteúdo referente a ação de se despedir do usuário

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by KahCosta** [comment]
[Estudo sobre criação de intents eficientes](https://github.com/lappis-unb/tais/wiki/Intents-Eficientes)

**Comment by gustable42** [comment]
Adicionei novos intents a funcionalidade e retirei algumas que não tinham haver com o escopo de despedida
