### ISSUE TITLE
Configurar ferramentas de CI

### ISSUE THREAD

**Issue by GuiMarques98** [fga-eps-mds/2019.1-Grupo-1#46]
Configuração das ferramentas de CI no GitHub.

**Tarefas**

- [x] Configurar as ferramentas de CI.
- [x] Configurar Bot no Telegram para enviar atualizações sobre a CI.

**Critérios de aceitação**

- [x] A equipe de EPS terá que receber as notificações de CI.
- [x] O GitHub terá que ficar configurado com todas as ferramentas de deploy e CI.

**Comment by Yoshida-Eduardo** [comment]
Com decisão minha e do @GuiMarques98 optamos por utilizar o Travis CI para integração contínua. Parte da configuração foi realizada, entretanto com função do fork descrito em #55, foi necessário priorizar a issue #59, afinal não faria sentido realizar a integração e o deploy com o serviço quebrado.

**Comment by Yoshida-Eduardo** [comment]
Meu notebook deu a louca e tirou os assigns, mas já coloquei novamente.
Continuando, tive que resolver uns impedimentos relacionados ao fork do boilerplate(descrito em #55 ), uma vez que o fork foi realizado na master, a branch devel ficou desatualizada em relação a esta e como a devel não estava a par da master no que tange a arquitetura, não seria possível prosseguir no prosseguir na configuração e implementação do CI, uma vez que os scripts para execução da build e testes seriam diferentes. Agora que os impedimentos foram sanados(foi necessário realizar um rebase com o aval do time de EPS) prosseguirei para finalizar a integração contínua.
