### ISSUE TITLE
Dojo: Papéis de Contribuidores

### ISSUE THREAD

**Issue by Yoshida-Eduardo** [fga-eps-mds/2019.1-Grupo-1#5]
Realizar Dojo sobre papéis 

**Tarefas**

- [x] Explicar os diferentes papéis dos contribuidores
- [x] Explicação complementar sobre a metodologia

**Critérios de aceitação**

- [x] A equipe de MDS possuir maior conhecimento sobre os papéis assumidos na metodologia
- [x] A equipe de MDS possuir conhecimento mais aprofundado sobre a metodologia aplicada

**Comment by KahCosta** [comment]
Ao Final do dojo foi apresentado ao time de MDS os papeis de cada integrante do time de EPS:
Product Owner: Kamilla Costa
Scrum Master: Lucas Vitor
Arquiteto: Guilherme Marques
DevOps: Eduardo Yoshida
