### ISSUE TITLE
Dojo: Documento de Arquitetura

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#6]
Realização de dojo como auxilio na construção do documento de arquitetura, que tem como finalidade definir a arquitetura que será trabalhada no projeto.

**Tarefas**

- [x] Explicar o que é arquitetura de um software
- [x] Explicar a importancia da implementação de arquitetura em um software
- [x] Apresentar algumas arquiteturas
- [x] Fazer um overview do documento de arquitetura de um projeto já desenvolvido na disciplina

**Critérios de aceitação**

- [x] A Equipe de MDS deve ter maturidade suficiente para desenvolver o artefato de documento de arquitetura do projeto que será desenvolvido.

**Comment by GuiMarques98** [comment]
Usarei o Documento de Arquitetura do Receita Mais [aqui](https://github.com/fga-eps-mds/2017.2-Receita-Mais/wiki/Documento-de-Arquitetura).

**Comment by GuiMarques98** [comment]
O Dojo de Documento de Arquitetura foi dado usando documentos de outros repositórios e foi dado um overview de como se fazia.
