### ISSUE TITLE
Adicionar tópico para que o bot seja capaz de Manter uma conversa

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#68]
Adicionar conteúdo referente ao tópico manter conversa.

**Tarefas**

- [x] Criar conteúdo referente a ação de manter conversa que tem como finalidade fazer com que o usuário continue uma conversa fluida com o bot.
- [x] Inserir conteúdo referente a ação de manter conversa com o  bot. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by heylisten64** [comment]
Dei uma olhada no conteúdo que o @iurisevero tinha feito na parte de sobre Python. Vou aproveitar algumas coisas do material.

**Comment by heylisten64** [comment]
# Manter uma conversa
* Intent:
intent_manter_conversa
* Utter:
utter_manter_conversa
* Template:
	Qualquer dúvida, é só perguntar! Vamos aprender juntos!!
	Pode falar comigo sobre o que quiser, mas o meu assunto preferido é Python!
	Posso te ajudar se você me der um pouquinho de feno... héehéeh é brincadeirinha... Mas em que mais eu posso ser útil? 
	Bée bée o que temos pra hoje?
	Eu não mordo não! Pode me perguntar... Gostaria de alguma informação?
	Uma das coisas que eu mais gosto é de tirar dúvidas! Sobre o que você deseja saber?
	Qual a sua maior dificuldade em Python? Eu posso te ajudar!
	Sobre o que vamos conversar hoje?

**Comment by heylisten64** [comment]
# Manter uma conversa
 ## Intent:

    intent_manter_conversa

## Utter:

    utter_manter_conversa

## Template:
	Qualquer dúvida, é só perguntar! Vamos aprender juntos!!
	Pode falar comigo sobre o que quiser, mas o meu assunto preferido é Python!
	Posso te ajudar se você me der um pouquinho de feno... héehéeh é brincadeirinha... Mas em que mais eu posso ser útil? 
	Bée bée o que temos pra hoje?
	Eu não mordo não! Pode me perguntar... Gostaria de alguma informação?
	Uma das coisas que eu mais gosto é de tirar dúvidas! Sobre o que você deseja saber?
	Qual a sua maior dificuldade em Python? Eu posso te ajudar!
	Sobre o que vamos conversar hoje?

**Comment by heylisten64** [comment]
Aguardo seu feedback pra implementar @KahCosta

**Comment by KahCosta** [comment]
@heylisten64 acho que tá bem grande... o intuito do manter conversa é ser inserido logo depois do diálogo com o usuário a fim de não deixar 'o assunto morrer'
Seria tipo 'No que mais posso lhe ajudar?' no maximo uma frase entende?

**Comment by heylisten64** [comment]
# Manter uma conversa

## Intent:

```
intent_manter_conversa

```

## Utter:

```
utter_manter_conversa

```

## Template:

```
Bée bée... o que temos pra hoje?
Sobre o que você deseja conversar agora? 
E então, qual a sua maior dificuldade em Python?
Sobre o que você deseja saber?
Gostaria de mais alguma informação?
Em que mais eu posso ser útil?

**Comment by heylisten64** [comment]
Bée bée... o que temos pra hoje?
          Sobre o que você deseja conversar agora, meu consagrado? 
          E então, qual a sua maior dificuldade em Python?
          Sobre o que mais você deseja sabéer?
          Béeleza? Gostaria de mais alguma informação?
          Em que mais eu posso ser útil? Bée bée

**Comment by heylisten64** [comment]
fiquei na dúvida se em stories eu já deveria "conectar" esse tópico aos outros, trilhando os caminhos... mas achei que o fluxograma a gente vai direcionar assim que a maior parte dos conteúdos estiverem elaborados... qualquer coisa, me avise que eu incremento essa parte.
