### ISSUE TITLE
Adicionar tópico com a definição de variável

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#69]
Adicionar conteúdo referente ao tópico variáveis

**Tarefas**

- [x] Criar conteúdo referente a ação de explicar sobre variáveis.
- [x] Inserir conteúdo referente a ação de explicar sobre variáveis. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
Comecei a pesquisar um pouco sobre variáveis, definições, vídeo aulas, blogs e exercícios.
## Variáveis 
* Definição:
	* Uma variável é um nome que damos a um espaço de memória para conter um valor de um determinado tipo.

	* Na programação, uma variável é um objeto capaz de reter e representar um valor ou expressão.

	* Quando nos referimos à variável, do ponto de vista da programação de computadores, estamos tratando de uma região de memória (do computador) previamente identificada cuja finalidade é armazenar os dados ou informações de um programa por um determinado espaço de tempo.

* Tipos:

	* Inteiro: Usadas para armazenar números inteiros;
		* Ex: 2, 10, 366

	* Ponto Flutuante: usadas para armazenar números reais;
		* Ex: 10.5, 6.9, 8.8, 1/2

	* Caractere: Usada para armazenar um caractere;
		* Ex: 'a', '1', '!'

	* Booleana: Usada para armazenar Verdadeiro ou Falso

* Possíveis links para passar para os alunos como referência de conteúdo:
	* [DevCast](https://www.devmedia.com.br/programacao-o-que-e-uma-variavel/38475) sobre variáveis;
	**Vídeo muito bom sobre variáveis, porém é em C#**
	* [Dicas de Programação](https://dicasdeprogramacao.com.br/o-que-e-variavel-e-constante/), explicação de variável em texto;
	* [Curso em vídeo](https://youtu.be/31llNGKWDdo) de Python, aula sobre comandos iniciais e explica variáveis durante isso;
	* [Curso em vídeo](https://youtu.be/hdDHg1p3YVc) de Python, aula sobre tipos primitivos;

* Possíveis exercícios
	* [Curso em vídeo](https://youtu.be/PB254Cfjlyk);
	* [URI](https://www.urionlinejudge.com.br/judge/pt/problems/view/1001);
	* [URI](https://www.urionlinejudge.com.br/judge/pt/problems/view/1002);
	* [URI](https://www.urionlinejudge.com.br/judge/pt/problems/view/1003);

* Referências:
	* https://pt.wikipedia.org/wiki/Vari%C3%A1vel_(programa%C3%A7%C3%A3o), acessado 06/04
	* http://bloghardwaremicrocamp.com.br/manutencao/variaveis-aprendendo-programacao/, acessado 06/04

**Comment by iurisevero** [comment]
Rascunho de Definição de Variável

## Intent
* sobre_variaveis
	* o que e uma variavel
	* o que são variaveis
	* voce sabe sobre variaveis
	* me explique sobre variaveis
	* quais os tipos de variavel
	* que tipos de variaveis existem
	* tipos primitivos de variaveis
	* variaveis em python

## Utter
* sobre_variaveis
	* Pois béem, variável é o nome dado a uma área de memória reservada para guardar as informações ou os dados de um programa por um determinado espaço de tempo. Existem diversos tipos de variáveis, mas o tipos primitivos são:
		* Inteiro, que serve para guardar os valores númericos do conjunto dos inteiros, isto éée, todos números, positivos e negativos, sem casas decimais.
			* Exemplo: -1, 8, 99
		* Ponto Flutuante, que assim como os inteiros, armazena valores numéricos, porém com casas decimais inclusas!!
			* Exemplo: -1.5, 89.54, 61.8845
		* Caractere, que guarda valores alfanuméericos e caracteres especiais, ou seja, letras, números, pontos, acentos, chaves, parênteses.... 
			* Exemplo: 'a', '!', '8'
		* Booleano, que tem como função armazenar Verdadeiro ou Falso.

**Comment by KahCosta** [comment]
Perfeito! mas lembrar que os links n serão disponibilizados aqui nessa utter!

**Comment by gustable42** [comment]
As utters estão bem sucintas, acho q agr o trabalho é só dividí-las em textos menores e tentar deixar esses tópicos menos com cara de tópico, pra parecer q é uma conversa mais próxima da realidade. Vou tentar dar uma adaptada e mando aqui pra gnt decidir melhor como fazê-las

**Comment by gustable42** [comment]
Pois béem, variável é o nome dado a uma área de memória reservada para guardar as informações ou os dados de um programa por um determinado tempo.

Existem vários tipos de variáveis, mas por hora, você vai precisar saber dos tipos primitivos, as mais simples

Uma variável do tipo inteiro, serve para guardar valores numéricos dentro do conjunto de inteiros.
Isto éee, todos números positivos e negatios sem casas decimais
Por exemplo, -1,  8, 99

Existe também as do tipo caractere
Elas guardam valores alfanuméricos e caractéres especiais, então, letras, números, pontos, acentos, chaves, parêntese
Exemplos de caracteres seriam 'a', '8', '!'

A "evolução" do tipo inteiro é o tipo Ponto Flutuente, ele armazena valores numéricos, porém com casas decimais.
Então 3.14150, -1.5, 61.884 são possíveis de serem armazenados numa variável deste tipo

E por fim, o quarto tipo é o booleano, ele serve para armazenar apenas o valor verdadeiro ou falso, é usado em operações lógicas

**Comment by gustable42** [comment]
Vocês acham q ficou mt desestruturado, ou tá bom?

**Comment by iurisevero** [comment]
> Vocês acham q ficou mt desestruturado, ou tá bom?

Curti muito!! Por mim já tá perfeito, só esperar pra ver se a @KahCosta aprova kk

**Comment by iurisevero** [comment]
> Vocês acham q ficou mt desestruturado, ou tá bom?

Curti muito!! Por mim já tá perfeito, só esperar pra ver se a @KahCosta aprova kk

**Comment by gustable42** [comment]
Na moral q vi o do @pedroeagle e do @Andreabenf e eles me deram inspiração pra fazer os exemplos ficarem mais legais

**Comment by gustable42** [comment]
Pois béem, variável é o nome dado a uma área de memória reservada para guardar as informações ou os dados de um programa por um determinado tempo.

Existem vários tipos de variáveis, mas por hora, você vai precisar saber dos tipos primitivos, as mais simples

Uma variável do tipo inteiro, serve para guardar valores numéricos dentro do conjunto de inteiros.
Isto éee, todos números positivos e negatios sem casas decimais
Por exemplo, você pode contar seus fenos com inteiros, 20 fenos, 30 fenos.

Existe também as do tipo caractere
Elas guardam valores alfanuméricos e caractéres especiais, então, letras, números, pontos, acentos, chaves, parêntese
Exemplos de caracteres seriam 'b', 'é', 'e', '!'

A "evolução" do tipo inteiro é o tipo Ponto Flutuente, ele armazena valores numéricos, porém com casas decimais.
Então 3.14150, -1.5, 61.884 são possíveis de serem armazenados numa variável deste tipo

E por fim, o quarto tipo é o booleano, ele serve para armazenar apenas o valor verdadeiro ou falso, é usado em operações lógicas
É verdadeiro que eu gosto muito de feno!

**Comment by gustable42** [comment]
Não pensei em nada pro float, se tiver alguma ideia

**Comment by gustable42** [comment]
O Pedro deu a ideia da gnt fazer um utter sobre variáveis no geral, eai o usuário pode perguntar alguma específica, só aí q a gnt manda os utters dos tipos

**Comment by iurisevero** [comment]
> Não pensei em nada pro float, se tiver alguma ideia

Podia colocar algo como 2.5 kg de capim, massa de Júpiter e peso da Aix kk

**Comment by iurisevero** [comment]
> O Pedro deu a ideia da gnt fazer um utter sobre variáveis no geral, eai o usuário pode perguntar alguma específica, só aí q a gnt manda os utters dos tipos

Pensei nisso tbm, mas aí pensei na possibilidade de a pessoa não lembrar os tipos... Mas podemos ver pra fazer uma storie com esses assuntos em sequência, aí na maioria das vezes a pessoa veria os dois e também teria a possibilidade de ver só um deles

**Comment by gustable42** [comment]
Verdade kkkkkkk
Falei com a Kamilla sobre essa ideia, e ela achou boa e falou pra gnt falar nossas dúvidas pra ela, caso tenhamos

**Comment by iurisevero** [comment]
> Verdade kkkkkkk
> Falei com a Kamilla sobre essa ideia, e ela achou boa e falou pra gnt falar nossas dúvidas pra ela, caso tenhamos

Bora dividir então, vai ficar melhor mesmo!

**Comment by gustable42** [comment]
Vou abrir a branch dessa issue

**Comment by gustable42** [comment]
Galera, estava dando uma olhada no código e a pasta de stories tem um main.md e um catalog.md, e ambos são bem parecidos, qual a diferença deles?

**Comment by gustable42** [comment]
Subi pro github os intents e utters já implementados, se possível, olhem depois pra ver se não tem nada quebrado
