### ISSUE TITLE
Adicionar tópico com exemplos de usos de variáveis em python

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#70]
Adicionar conteúdo referente ao tópico de exemplos de variáveis em python.

**Tarefas**

- [x] Criar conteúdo referente a ação de apresentar exemplos de utilização de variáveis na linguagem python.
- [x] Inserir conteúdo referente a ação de apresentar exemplos de variáveis. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
Rascunho de exemplos de variáveis
## Intent
* exemplos_variaveis
	* voce tem exemplos de variaveis
	* como usar uma variavel
	* como declarar uma variavel
	* me de um exemplo de variavel
	* exemplo de variavel

## Utter
* exemplos_variaveis
	* Então você quer ver como as variáveis funcionam... Não é fácil igual comer capim, mas vou te dar alguns exemplos e você vai entender!!!
	Digamos que você está entrando no seu e-mail, repare que no login existem duas variáveis, seu username e sua senha.
	Num código ficaria mais ou menos assim:
	```
	# variável = conteúdo
	username = "username@email.com"
	senha = "digitos1234"
	```
	Lembrando que no Python não é preciso declarar o tipo da variável, apenas nomeá-la! 

	Outro exemplo possível é uma equação, onde você já tem variáveis!!
	A Fórmula de Bhaskara poderia ser escrita desse jeito:
	```
	# f(x) = -5x^2 + 4x + 1
	# variável = conteúdo
	a = -5
	b = 4
	c = 1
	delta = b*b - 4*a*c
	y1 = (-b + delta**1/2)/(2*a)
	y2 = (-b - delta**1/2)/(2*a)
	```
	Veja quantas variáveis!!! Vou listá-las para você conseguir ver béem melhor.
	* a
	* b
	* c
	* delta
	* y1
	* y2

	Repare que a varíavel e o countéudo que ela armazena são coisas diferentes!!

	Espero ter conseguido ajudar, me deixaria béem feliz!

**Comment by KahCosta** [comment]
show!

**Comment by gustable42** [comment]
Gente, vou fazer duas stories diferentes uma como exemplo e outra como outro exemplo, aí essa segunda só seria triggada, caso o usuário peça outro exemplo

**Comment by gustable42** [comment]
Pq da forma como está a mensagem acaba ficando muito grande, aí vou colocar a parte de Bhaskara como esse outro exemplo

**Comment by iurisevero** [comment]
Só vê direito como faz esse gatilho para acionar o segundo exemplo, se perguntaria no final "precisa de outro exemplo?" e o bot entenderia se sim ou não ou se colocaria em sequência como no caso da explicação de variáveis... Acredito que a @KahCosta possa ajudar mais sobre isso

**Comment by gustable42** [comment]
Pois é, to testando aqui e não está funcionando muito bem

**Comment by gustable42** [comment]
A Kamilla pediu para fecharmos essa issue com apenas uma resposta, e então na próxima sprint a gente implementa essa ideia da resposta encadeada na pergunta sobre outro exemplo
