### ISSUE TITLE
Adicionar tópico com linkagem estática para conteúdo extra sobre variáveis

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#71]
Adicionar conteúdo referente ao tópico de linkagem estática para conteúdo extra sobre variáveis

**Tarefas**

- [x] Pesquisar link referente a utilização de variáveis na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre a utilização de variáveis. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
Rascunho de linkagem estática para conteúdo extra sobre variáveis
## Intent 
* links_variaveis
	* conteudo adicional sobre variaveis
	* links sobre variaveis
	* mais sobre variaveis
	* voce tem links de conteudos sobre variaveis
	* eu quero saber mais sobre variaveis
	* o que voce tem alem sobre variaveis
	* voce tem algum conteudo extra de variaveis


## Utter
* links_variaveis
	* Então você quer um conteúdo a mais... Béem, vou ver o que consigo para você! 
	Achei aqui um blog com uma explicação béem legal de variáveis, [O que é variável e constante?](https://dicasdeprogramacao.com.br/o-que-e-variavel-e-constante/), tem uns exemplos nele tambéem!!
	Esse canal do YouTube parece ser muito bom! Ele tem uma aula sobre comandos iniciais, onde ele resume o que são variáveis, [Primeiros comandos em Python3](https://youtu.be/31llNGKWDdo), e uma aula exclusiva sobre Tipo Primitivos, [Tipos Primitivos e Saída de Dados](https://youtu.be/hdDHg1p3YVc)!!

**Comment by KahCosta** [comment]
tá ok! se conseguir inserir um pouco mais da personalidade do bot no diálogo vai ficar ainda melhor!

**Comment by gustable42** [comment]
Gente, vcs sabem como fazer um link estático ser uma frase comum no Rasa, igual a forma que o Iuri fez aqui na Issue?

**Comment by iurisevero** [comment]
[Nome pro link](url), eu tinha feito assim.
Igual na escrita em markdown

**Comment by gustable42** [comment]
Esse método do Markdown não funcionou, eu vou mudar a abordagem por hora, e quando acharmos a solução, eu mudo no código

**Comment by gustable42** [comment]
https://github.com/RasaHQ/rasa_nlu/issues/2081
Já foi feita uma issue assim no Rasa, e descobri q essa funcionalidade não é oferecida diretamente por ele, mas sim na plataforma que as informações serão mostradas
