### ISSUE TITLE
Adicionar tópico com linkagem estática para sugestão de exercício sobre uso de variáveis

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#72]
Adicionar conteúdo referente ao tópico linkagem estática para sugestão de exercício sobre uso de variáveis

**Tarefas**

- [x] Pesquisar link referente a sugestão de exercícios referentes ao uso de variáveis na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre sugestão de exercício sobre utilização de variáveis. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by iurisevero** [comment]
Rascunho para linkagem de exercícios sobre uso de variáveis
##Intent
* exercicios_variaveis
	* voce sabe algum exercicio sobre variaveis
	* exercicios de variaveis
	* quero resolver exercicios a respeito de variaveis
	* quais exercicios sobre variaveis voce pode me indicar
	* me indique exercicios sobre variaveis

## Utter
* exercicios_variaveis
	* Acha que já está pronto para alguns exercícios? Pois béem, vou ver o que tenho aqui....
	Por que você não tenta esse exercícios do [URI](https://www.urionlinejudge.com.br)?
		* [Extremamente Básico](https://www.urionlinejudge.com.br/judge/pt/problems/view/1001)
		* [Área do Círculo](https://www.urionlinejudge.com.br/judge/pt/problems/view/1002)
		* [Soma Simples](https://www.urionlinejudge.com.br/judge/pt/problems/view/1003)

	Não esquece que para acessar o [URI](https://www.urionlinejudge.com.br) você precisa criar uma conta antes!!
	Também achei esse exercício resolvido no YouTube, [Somando dois números](https://www.youtube.com/watch?v=PB254Cfjlyk&feature=youtu.be), se você preferir!!

**Comment by KahCosta** [comment]
Ótimo!
