### ISSUE TITLE
Adicionar tópico com a definição do que são estruturas condicionais

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#73]
Adicionar conteúdo referente ao tópico definição do que são estruturas condicionais

**Tarefas**

- [x] Criar conteúdo referente a ação de explicar sobre Estruturas condicionais
- [x] Inserir conteúdo referente a ação de explicar sobre estruturas condicionais. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by pedroeagle** [comment]
o que acham dessa definição de estrutura condicional? como posso melhorá-la?

quer saber o que é uma estrutura condicional?

uma estrutura condicional são ações que podem ou não serem executadas no seu programa. 
é necessário que uma condição seja testada para que que essas ações sejam executadas ou não. 

SE a condição é satisfeita, executamos o que foi definido. SE NÃO, pulamos. 

é possível ainda criar várias condições de forma que se a primeira não é satisfeita a segunda condição é testada e assim sucessivamente. SE  uma condição é satisfeita, executamos tal bloco de código, se a primeira não é satisfeita, MAS SE outra condição é satisfeita executamos outro bloco de código e assim sucessivamente.

e caso nenhuma das condições seja satisfeita, é possível determinar um último bloco de código em que a única condição é não ter condições aprovadas nos SE e MAS SE anteriores.

**Comment by Andreabenf** [comment]
Achei grande e formal demais.
Vou criar a branch dessa issue, ai ja tento dar uma melhorada nessa mensagem

**Comment by KahCosta** [comment]
Gostei da explicaçõ mas concordo que stá bem formal e grande! tenta reduzir um pouco e aplicar mai a personalidade do bot

**Comment by KahCosta** [comment]
Foquem em oferecer explicações menores...o usuário pode não ficar satisfeito em ter que ler textos extensos em um chtbot

**Comment by Andreabenf** [comment]
### Essa é a nossa segunda versão do texto:

Ah, eu adoro estruturas condicionais!
Bom, uma estrutura condicional são ações que podem ou não serem executadas no seu programa.
É necessário que uma condição seja testada para que que essas ações sejam executadas ou não.

SE a condição é satisfeita, executamos o que foi definido. SE NÃO, pulamos e vamos para a proxima condição. Além disso, podemos fazer uma opção extra que será executada caso nenhuma condição for satisfeita

Por exemplo:

Imagine que você tem um pouquinho de feno nas suas mãos
Se você me der ele, eu vou ficar feliz!
Se você resolver ficar com ele, eu vou ficar na vontade, poxa!
E se você nem me der e nem ficar com ele, vou ficar confusa, oras! Por que você teria feno e não faria nada com ele? Eu hein...

**Comment by KahCosta** [comment]
Não faço ideia do que seja Feno, mas acredito que seja algo relacionado a alimentação de uma cabra rsrsr 
Acho que está legal!

**Comment by Andreabenf** [comment]
Feno é tipo capim! hahahaha

**Comment by Andreabenf** [comment]
Galera, dei umas alteradas nas intents de tudo_bem.
Tinha muito a palavra "como". E sempre que alguém perguntava como fazer algo, a Aix respondia que estava beém.

**Comment by Andreabenf** [comment]
# Introdução sobre condiconais

## Intent:
     sobre_condicionais

## utter
     utter_sobre_condicionais

## template:
        Ah, eu adoro estruturas condicionais!
        Bom, uma estrutura condicional são ações que podem ou não serem executadas no seu programa.
        É necessário que uma condição seja testada para que que essas ações sejam executadas ou não.

        SE a condição é satisfeita, executamos o que foi definido. SE NÃO, pulamos e vamos para a proxima condição. Além disso, podemos fazer uma opção extra que será executada caso nenhuma condição for satisfeita

        Por exemplo:
        Imagine que você tem um pouquinho de feno nas suas mãos
        Se você me der ele, eu vou ficar feliz!
        Se você resolver ficar com ele, eu vou ficar na vontade, poxa!
        E se você nem me der e nem ficar com ele, vou ficar confusa, oras! Por que você teria feno e não       faria nada com ele? Eu hein...
