### ISSUE TITLE
Adicionar tópico com exemplos de utilização de estruturas condicionais

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#74]
Adicionar conteúdo referente ao tópico com exemplos de utilização de estruturas condicionais

**Tarefas**

- [x] Criar conteúdo referente a ação de apresentar exemplos de utilização de Estruturas condicionais na linguagem python.
- [x] Inserir conteúdo referente a ação de apresentar exemplos de Estruturas condicionais. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by Andreabenf** [comment]
# Introdução sobre condiconais

## Intent:
     sobre_condicionais

## utter
     utter_sobre_condicionais

## template:
        Ah, eu adoro estruturas condicionais!
        Bom, uma estrutura condicional são ações que podem ou não serem executadas no seu programa.
        É necessário que uma condição seja testada para que que essas ações sejam executadas ou não.

        SE a condição é satisfeita, executamos o que foi definido. SE NÃO, pulamos e vamos para a proxima condição. Além disso, podemos fazer uma opção extra que será executada caso nenhuma condição for satisfeita

        Por exemplo:
        Imagine que você tem um pouquinho de feno nas suas mãos
        Se você me der ele, eu vou ficar feliz!
        Se você resolver ficar com ele, eu vou ficar na vontade, poxa!
        E se você nem me der e nem ficar com ele, vou ficar confusa, oras! Por que você teria feno e não       faria nada com ele? Eu hein...

**Comment by Andreabenf** [comment]
# Link para exemplo extra

## intent
       sobre_condicionais_exemplo

## utter
      utter_sobre_condicionais_exemplo

## template 
       Quer saber como escrever uma estrutura condicional em python? Xá comigo, nisso eu sou muito boa!
        Digamos que se você quer que seja printado "amo feno" caso uma variavel x seja igual a 2 e "amo python"
        caso essa variável seja igual 5. Caso x seja tanto diferente de 2 quanto de 5 você quer
        que seja printado "amo a Aix" :
          
          if x == 2:
            print("amo feno")
          elif x == 5:
            print("amo python")
          else:
            print("amo a Aix")
