### ISSUE TITLE
Adicionar tópico com linkagem estática para conteúdo extra sobre estruturas condicionais

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#75]
Adicionar conteúdo referente ao tópico linkagem estática para conteúdo extra sobre estruturas condicionais

**Tarefas**

- [x] Pesquisar link referente a utilização de Estruturas condicionais na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre a utilização de Estruturas condicionais. 

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by pedroeagle** [comment]
achei essa explicação sobre estrutura condicional muito bem organizada e detalhada:

https://www.devmedia.com.br/aprendendo-a-programar-em-python-estruturas-condicionais-if/17358

**Comment by KahCosta** [comment]
Beleza! Mas lembra de estruturar a resposta sempre inserindo a personalidade do bot!

**Comment by Andreabenf** [comment]
Curti muito esse site, Pedro!
Acho 100% viavel deixar ele como exemplo de site patra conteúdo extra

**Comment by Andreabenf** [comment]
Pedro, curti seu link. Mas acho que esse aqui seria melhor:

https://www.w3schools.com/python/python_conditions.asp

Ele tem mais informações, mas mesmo assim mantém a clareza

**Comment by Andreabenf** [comment]
Tava pensando em fazer mensagem como um if, mais ou menos assim:

if Aix_não_sanou_minha_duvida or Quero_mais_informações:
          Eu te ajudo! Ta aqui um link que explica mais mastigado do que meu feno hehehe
          https://www.w3schools.com/python/python_conditions.asp

**Comment by Andreabenf** [comment]
2019-04-09 21:21:31 ERROR    rasa_core.dispatcher  - Couldn't create message for template 'utter_link_conteudo_condicionais'.

Estou me encontrando com esse erro.

**Comment by Andreabenf** [comment]
Arrumei!
Era só erro de formatação.

**Comment by Andreabenf** [comment]
# Link para exemplo extra

## intent
       link_conteudo_condicionais

## utter
      utter_link_conteudo_condicionais

## template 
      Ta querendo saber mais né? Beleza! Até preparei um código aqui para você
          if Aix_não_sanou_sua_duvida or Quer_mais_informações:
              Tudo béem! Ta aqui um link que explica mais mastigado do que meu feno. hehehe
              https://www.w3schools.com/python/python_conditions.asp
