### ISSUE TITLE
 Adicionar tópico com linkagem estática para sugestão de exercício sobre uso de estruturas condicionais

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#76]
Adicionar conteúdo referente ao tópico linkagem estática para sugestão de exercício sobre uso de estruturas condicionais

**Tarefas**

- [x] Pesquisar link referente a sugestão de exercícios referentes ao uso de Estruturas condicionais na linguagem python.
- [x] Inserir conteúdo referente a ação de oferecer um link sobre sugestão de exercício sobre utilização de Estruturas condicionais. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by pedroeagle** [comment]
poderíamos escolher uma única plataforma para todos os exercícios, o que acham? dessa forma o usuário não precisa criar várias contas ao usar nosso bot.

**Comment by Andreabenf** [comment]
Eu acho uma boa!

**Comment by KahCosta** [comment]
Eu acho uma boa o URI! conversem com os demais! acho uma boa idea

**Comment by pedroeagle** [comment]
vou adicionar 3 exercícios. um fácil, um médio e um difícil. segue os link que serão utilizados em ordem de dificuldade crescente:
https://www.urionlinejudge.com.br/judge/pt/problems/view/1052
https://www.urionlinejudge.com.br/judge/pt/problems/view/1035
https://www.urionlinejudge.com.br/judge/pt/problems/view/1037

**Comment by pedroeagle** [comment]
## Linkagem estática para sugestão de exercício sobre uso de estruturas condicionais
### intent
      sobre_condicionais_exercicios
### utter
     utter_sobre_condicionais_exercicios
### template
     Ahh, então você quer praticar estruturas condicionais? Fico tãããoo feliz em saber disso
        A única forma dééé aprender uma linguagem de forma eficaz é treinando!
        Veja esses 3 exercícios:
          Mês - https://www.urionlinejudge.com.br/judge/pt/problems/view/1052
          Teste de seleção 1 - https://www.urionlinejudge.com.br/judge/pt/problems/view/1035
          Intervalo - https://www.urionlinejudge.com.br/judge/pt/problems/view/1037
