### ISSUE TITLE
Refatorar modelagem da Arquitetura

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#78]
Refatorar arquitetura de acordo com alterações feitas pela inserção do boilerplate

- [x] Refatorar documento
- [x] Atualizar documento do Github Pages

**Critérios de aceitação**

- [x] O documento deve estar devidamente revisado e adicionado ao Github pages do grupo
- [x] Documentar na issue o  link do arquivo onde se pode encontrar o documento.

**Comment by GuiMarques98** [comment]
Algumas alterações foram feitas como adicionadas algumas tecnologias, textos alterados pois não condiziam com o escopo do projeto, refatorado completamente as metas e restrições adicionado a visão lógica do projeto.

**Comment by GuiMarques98** [comment]
Também não foi possivel fazer o diagrama de pacotes, pois como a aquitetura não está fechada completamente poderá ocorrer alguns erros então nas próximas sprints reabrirei essa issue ou criarei outra para a nova revisão da arquitetura.

**Comment by Lucas362** [comment]
Ok, como nossa arquitetura ainda não está "redonda", isso já era de se esperar, no momento em que tivermos consolidado nossa arquitetura será requisitada a refatoração do documento. Bom trabalho! :+1:
