### ISSUE TITLE
Documento de elicitação de requisitos

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#79]
Elaborar documento de elicitação de requisitos baseado nas respostas do formulário elaborado.

**Tarefas**

- [x] Criar documento de requisitos
- [x] Adicionar documento ao GitHub Pages

**Critérios de aceitação**

- [x] O documento deve estar devidamente revisado e adicionado ao Github pages do grupo
- [x] Documentar na issue o  link do arquivo onde se pode encontrar o documento.

**Comment by Lucas362** [comment]
Foi criado um documento explicando as técnicas de elicitação utilizadas nesta etapa do desenvolvimento, descrevendo sua implementação e resultados obtidos
