### ISSUE TITLE
Treinamento de tecnologias

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#8]
Treinar equipe de MDS quanto as tecnologias a serem utilizadas.

**Tarefas**

- [x] Treinamento sobre Python
- [x] Treinamento de framework 

**Critérios de aceitação**

- [x] A equipe de MDS deve conseguir compreender as tecnologias e saber desenvolver ao menos o básico.

**Comment by Lucas362** [comment]
Foi ministrado o treinamento de Framework, através da demonstração do desenvolvimento e funcionamento de uma API no framework Flask
