### ISSUE TITLE
Dojo: Arquitetura de microsserviços

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#82]
Explicar sobre aspectos e caracteristicas de uma arquitetura de microsserviços.

**Tarefas**

- [x] Explicar o funcionamento de microsserviços e como se comunicam;
- [x] Mostrar exemplos 

**Critérios de aceitação**

- [x] Equipe de MDS e EPS alinhada quanto ao uso e funcionamento.

**Comment by GuiMarques98** [comment]
O dojo será dado na quinta-feira dia 11/04/2019 as 12:30.
