### ISSUE TITLE
Adicionar tópico com a definição de Estruturas de Repetição

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#87]
Adicionar conteúdo referente ao tópico definição de Estruturas de Repetição

**Tarefas**

- [x] Criar conteúdo referente a ação de explicar sobre estruturas de repetição
- [x] Inserir conteúdo referente a ação de explicar sobre estruturas de repetição. Incluindo arquivos de Domain.yml, intents e utter

**Critérios de aceitação**

- [x] Aix ser capaz de responder este tópico
- [x] Conteúdo não reduzir precisão de resposta para outro tópico
- [x] Documentar na issue o conteúdo inserido

**Comment by heylisten64** [comment]
Dei uma olhada no conteúdo a ser inserido, e a forma como ele é dado em algumas vídeo-aulas e plataformas e tô elaborando uma forma de tornar a matéria mais dinâmica dentro do chatbot, pra sair um pouco do padrão que são chatbots, p/ o usuário não ficar só nos textões. Pensei em talvez usar um recurso visual pra tentar ilustrar a função, mas talvez seja muita viagem da minha parte kkk... de toda forma essa issue vou tentar bolar uma historinha com o mascote pra explicar as funções de repetições

**Comment by heylisten64** [comment]
## Estruturas de repetição
Serão trabalhados os seguintes tópicos nessa issue:
* Definição geral;
* Funções;
* Possíveis links de apoio;
* Possíveis exercícios;
* Referências;

**Comment by heylisten64** [comment]
## Estruturas de repetição
Serão trabalhados os seguintes tópicos nessa issue:
* Definição;
* Sintaxe;
* Recursos visuais para apoio;
* Referências - materiais de estudo e exercícios.

**Comment by heylisten64** [comment]
# Definição:
* Estruturas de repetição são funções capazes de iterar determinada ação. Nelas, você pode determinar um fim, um objetivo e uma instrução. Ou seja,
você vai realizar determinada ação repetidas vezes até alcançar o resultado que deseja. É como se eu precisasse contar até dez em Python: eu não necessitaria
utilizar a função print dez vezes, apenas colocaria ela dentro de uma dessas estruturas, dentro de um loop.

*<botão "entendi?">
<botão "entendi?":NÃO>*

* Não entendeu? Béem, vou explicar de outra forma... Imagine que eu, Aix, estou no celeiro e meu feno do lado de fora, no campado. Não há nenhum obstáculo entre mim e 
a minha comida. No entanto, para chegar lá, precisarei de alguns passos. Cada passo será uma ação minha. No caso, eu terei que executar uma quantidade finita de passos até 
chegar ao meu objetivo: o feno. Repetirei então a minha ação "dar um passo" até chegar a minha comidinha. Funciona mais ou menos assim!

*<gif/recurso visual>*

*<botão "entendi?":SIM>*

# Sintaxe:
* Assim, para que eu consiga fazer isso eu posso utilizar os laços for e while da linguagem Python. A sintaxe no laço for é a seguinte:

  

      for b in range(a, i, x):
		  instrução            
      #instrução fora do laço

Sendo b uma variável que começa em a e irá correr até (i-1), obedecendo o valor de x. O x irá definir a iteração. Caso você omita essa última variável, será definido
por padrão de cada vez executada a tarefa, ser adicionada +1 (+x caso não omita) no b.
**P.S.:** Cuidado com a identação na sintaxe. 

Já a sintaxe do while é mais simples... Vamos contar até dez?

    while a<10:
	    #instrução:
	    print(a)
	    #alterando iterador:
	    a = a + 1
    #instrução fora do laço

**P.S.:** não esqueça de inicializar a variável a com o valor que desejar. No caso, seria 0.

# Referências:
* Precisa de um reforço? 
[Curso em vídeo de Python #013](https://www.youtube.com/watch?v=cL4YDtFnCt4&t=1238s);
 [Curso em vídeo de Python #014](https://www.youtube.com/watch?v=LH6OIn2lBaI&t=1026s);
[Data Science Academy - Curso em português de Python, gratuito](https://www.datascienceacademy.com.br/course?courseid=python-fundamentos);
[Wiki Python](https://wiki.python.org.br/AprendaProgramar)
[Documentação da linguagem Python](https://docs.python.org/3/tutorial/)
Livro: Use a cabeça! Python de Paul Barry - páginas 24 a 28.

* Bora treinar?
[Curso em vídeo - exercícios](https://www.youtube.com/watch?v=NR1RKt6NT8s&list=PLHz_AreHm4dm6wYOIW20Nyg12TAjmMGT-&index=47)
[URI](https://www.urionlinejudge.com.br/judge/en/problems/view/1059)
[URI](https://www.urionlinejudge.com.br/judge/en/problems/view/1060)

@KahCosta pode me dizer se está ok?

**Comment by KahCosta** [comment]
@heylisten64 não vamos ter o uso de botões...pq a rocketchat n permite! eu gostei das ideias de inserir imagens! mas ainda acho que o texto está bem extenso! se conseguir reduzir um pouco seria ótimo

**Comment by KahCosta** [comment]
e essas referencias a links so vao entrar na intent de linkagem...essa no caso é so a de definição mesmo

**Comment by heylisten64** [comment]
tudo bem!! obrigada

**Comment by heylisten64** [comment]
# Introdução sobre laços

## Intent:

```
 sobre_laços

```

## utter

```
 utter_sobre_laços

```

## template:

    Estruturas de repetição são funções capazes de 
    iterar determinada ação. Nelas, você pode determinar 
    uma meta e uma instrução. Ou seja, você vai realizar
    determinada ação repetidas vezes até alcançar o resultado 
    que deseja! Mas não seja béesta, tenha cuidado, pois você
    pode cair em um loop infinito! Assim, para conseguir fazer
    isso, temos os laços for e while da linguagem Python. 
    Ficou béem claro?
* 
* ou
*

    Laços são funções capazes de reproduzir determinada ação.
    Béem, vou explicar de outra forma. Imagine que eu, Aix,
    estou no celeiro e meu feno do lado de fora, no campado.
    Para chegar lá, precisarei de alguns passos. Cada passo 
    será uma ação minha. No caso, eu terei que executar uma
    quantia de passos finitos até chegar ao meu objetivo.
    Repetirei então a minha ação "dar um passo" até chegar
    ao meu feno de cada dia. Funciona mais ou menos assim!

**Comment by heylisten64** [comment]
como entrará só a definição nessa issue, acho que cabe uma outra issue para sintaxe e o restante. Nessa eu segui o modelo da issue #73.
