### ISSUE TITLE
Refatorar Documento de Arquitetura

### ISSUE THREAD

**Issue by KahCosta** [fga-eps-mds/2019.1-Grupo-1#98]
Refatorar documento de arquitetura baseado nas observações feitas pelos monitores da disciplina que estão listadas nas tasks.

**Tarefas**

- [x] Arrumar tabela sobre especificação de caso de uso que está quebrada
- [x] Utilizar verbos na construção do diagrama de caso de uso
- [x] Revisar tópico 'Vantagens' pois a descrição feita não se adequa a realidade do projeto uma vez que não estamos utilizando um broker.

**Critérios de aceitação**

- [x] Documento refatorado e validado pela equipe de EPS
- [x] Documento linkado na issue

**Comment by iurisevero** [comment]
@pedroeagle @Andreabenf @heylisten64 @gustable42 Vou começar as mudanças no documento, certo?
Criar a branch e já ir arrumando o que eu conseguir

**Comment by Andreabenf** [comment]
Belezinha. Irei ajudar já já

**Comment by iurisevero** [comment]
@KahCosta quando você falou da parte de vantagens, era referente a qual parte do arquivo? Estava olhando aqui e não achei.
Aproveitando, tem alguma forma de eu testar se a tabela está sendo montada direito no github pages?
Porque no hackmd e no acesso direto pelo github ela fica normal

**Comment by KahCosta** [comment]
é no próprio doc de arquitetura @iurisevero

**Comment by pedroeagle** [comment]
só corrigindo:
"Revisar tópico 'Vantagens' pois a descrição feita não se adequa a realidade do projeto uma vez que não estamos utilizando um broker."
na verdade é revisar o tópico "qualidade" certo?
